


var tipuesearch = {"pages": [
     
     
     {"title": "Summary", "text": "Jonathan Still&#39;s six criteria for political equality provide a useful structure for evaluating election systems. These provide an escalating set of criteria where a system may pass lower requirements but fail higher ones.Several of his criteria can be grouped into a single Independence test - requiring that the choices of one voter should not change the impact of another. The criteria provide ways of reframing group rights to representation as expressions of individual rights.With the higher criteria, trade-offs between political equality become more apparent. ", "tags": "", "url": "index.html#1.1.anuke.cfmsa.ebixv.l1iwy"},
     
     {"title": "Summary", "text": "Header image: Photo by Ryan Moreno on Unsplash", "tags": "", "url": "index.html#1.2.ohami.vptqm.0fpk_.-uwoz"},
     
     
     
     {"title": "Introduction", "text": "Common definitions of political equality are hard to put into practice. Abstract principles such as &quot;one person, one vote&quot; may appear to be satisfied while allowing substantial inequalities in the process of an election to remain. ", "tags": "", "url": "index.html#2.3.i170x.npg0q.kp_or.qw-fw"},
     
     {"title": "Introduction", "text": "Jonathan Still&#39;s 1981 article &amp;#8216;Political Equality and Election Systems&#39; tried to address this issue by creating tests that dealt with real world problems for equality in elections. This is useful for theoretical clarity, but more generally in the US there is legal interest in testable measures of political equality, as these can form parts of arguments before courts that there are superior ways of detecting and addressing violations of rights than those currently in use. ", "tags": "", "url": "index.html#2.4.gmtgs.wzlbe.7hdia.bjhre"},
     
     {"title": "Introduction", "text": "He came up with a set of six escalating criteria for the political equality of voters in elections:", "tags": "", "url": "index.html#2.5.lheng.edn5e.g3vc5.sj49j"},
     
     {"title": "Introduction", "text": "Universal Equal Suffrage: Everyone is allowed to vote, and everyone gets the same number of votes. Equal Shares: Each voter has the same &quot;share&quot; in the election, defined as what that voter voted on divided by the number of voters who voted on it. Equal Probabilities: Each voter has the same statistical probability of casting a vote which decides the election (under certain assumptions).Anonymity: The result of the election is the same under all possible distributions of the voters among the positions in the structure of the election systemMajority Rule: An alternative favored by a majority of the voters will be chosen by the election system.Proportional Group Representation: Each group of voters receives the same proportion of the seats in the legislative body as the number of voters in the group is of the total electorate.", "tags": "", "url": "index.html#2.6.r1ni5.a7qzs.4x8ev.hacz3"},
     
     {"title": "Introduction", "text": "While these are conceptually useful separations, I think it is fair to say they are not entirely clear on a first read. This set can be reframed as the following points:", "tags": "", "url": "index.html#2.7.pfxwj.vhmjq.ufgdc.z1uvo"},
     
     {"title": "Introduction", "text": "It doesn&#39;t matter who you are, your vote should count the same (Suffrage)It doesn&#39;t matter where you are, your vote should count the same (Shares)It doesn&#39;t matter which party/candidate you vote for, your vote should count the same (Independence)If you change your vote from one party to another, it should have the same impact as anyone else making the same switch (Equal probabilities)If you swap your vote with anyone else, it should make no difference (Anonymity)The weighting of your vote should not change depending how others vote (Majority rule)Everyone should have the representation they want (Proportional Representation)", "tags": "", "url": "index.html#2.8.-cxnv.tdwos.lslao.iwiv9"},
     
     {"title": "Introduction", "text": "There are two major changes in how I understand these criteria versus how Still presents them. The first is that Equal Probabilities, Anonymity and Majority Rule are not relevant to all elections, and so it is more straightforward to present them as different elements of the same general issue, which I&#39;ve labelled Independence. The second is that while Still generally presents these as binary criteria to pass or fail, I think they make more sense as scales where different systems can be graded against a perfect ideal that is almost impossible to practically achieve.", "tags": "", "url": "index.html#2.9.rbdkv.6hdgt.s2ayn.lqakc"},
     
     
     
     {"title": "Universal Suffrage", "text": "It doesn&#39;t matter who you are, your vote should count the same", "tags": "", "url": "index.html#3.10.vwn-z.tdwos.9as-w.2zbfm"},
     
     {"title": "Universal Suffrage", "text": "This is supposed to be the straightforward and easily passed requirement, but the interesting thing about how Still defines this requirement is how quickly he qualifies it:", "tags": "", "url": "index.html#3.11.vbf78.k-m_m.imonu.lilfm"},
     
     {"title": "Universal Suffrage", "text": "&quot;Universal suffrage has never been truly universal, and no one has ever seriously suggested that it ought to be. Children are always excluded, though the age cutoff used has varied. Aliens are often excluded, as are insane people and convicted felons. Yet exclusions of this nature are generally not considered to negate the existence of universal suffrage. Hence, universal suffrage will be interpreted here as meaning universal suffrage subject to the usual exclusions, without further discussion of what the usual exclusions are or ought to be.&quot;", "tags": "", "url": "index.html#3.12.xvfss.apuxb.d4unf.sbxux"},
     
     {"title": "Universal Suffrage", "text": "With this section you get the sense Still is moving quickly to get onto the aspects of the problem he is more interested in. However, starting with &quot;Everyone is allowed to vote, and everyone gets the same number of votes&quot; and then defining down who &quot;everyone&quot; is a fudge to get around that if universal suffrage has its straightforward meaning, no democracy currently pases. This is a troubling result that calls for a more substantial response than to point out that some exclusions are typical and widely accepted (if only because other exclusions have also been typical and widely accepted).", "tags": "", "url": "index.html#3.13.hwclg.0v-wv.ucgxq.ynkfz"},
     
     {"title": "Universal Suffrage", "text": "As I have explored elsewhere, there are serious problems raised by the exclusion of children, especially in places where they make up a substantial proportion of the population. If it is appropriate to exclude felons is an ongoing debate, but in places that incarcerate a large proportion of their population and deny voting rights as a result, this has an impact on the results. The exclusion is not just philosophical but political, and needs to be made transparent.", "tags": "", "url": "index.html#3.14.pwv45.6jen5.6zlgh.coby9"},
     
     {"title": "Universal Suffrage", "text": "The rule of adult mentally-capable non-felon citizens may enfranchise almost everyone or very few people, and so the reasonableness of this rule must vary depending on the underlying facts. Given this, exceptions shouldn&#39;t be defined out and universal suffrage must mean exactly that - every person has the vote.", "tags": "", "url": "index.html#3.15.laazw.ajsfr.rqgnm.6a2my"},
     
     {"title": "Universal Suffrage", "text": "While Still suggests these criteria are either fulfilled or not, this immediately shows why it is more useful to understand them scales for comparison. It is important to know whether 40% or 80% of people have the vote when comparing political equality in different places. What is &amp;#8216;enough&#39; is a question to have arguments about rather than explicitly delimit.", "tags": "", "url": "index.html#3.16.5aoay.xp2xo.yxvlh.sva8q"},
     
     
     
     {"title": "Equal Shares", "text": "It doesn&#39;t matter where you are, your vote should count the same ", "tags": "", "url": "index.html#4.17.gme5g.tdwos.v56ji.2zbfm"},
     
     {"title": "Equal Shares", "text": "This is specifically a problem of elections based on multiple districts/constituencies. When you divide one polity into multiple constituencies you are creating isolated populations of voters. If these constituencies are different sizes, then the people in each do not have equal shares in the election.", "tags": "", "url": "index.html#4.18.x0sea.vffwe.sgbun.iq-nz"},
     
     {"title": "Equal Shares", "text": "This much is generally understood as an issue and is addressed by requirements that constituencies should not vary too much in size (either of population or electors). But similar to universal suffrage, this criteria is rarely met in the wild because Still defines this as equal shares of an election among voters, and it is hard to equalise the number of &amp;#8216;voters&#39; in advance. ", "tags": "", "url": "index.html#4.19.h99tx.bpd0h.yioez.chjfu"},
     
     {"title": "Equal Shares", "text": "If there are two constituencies with equal numbers of eligible voters, but a 40% turnout in one and an 80% turnout in another, one set of voters have double the share in the election. In this situation the common principles used to address the problem have been met, but equal shares is still unsatisfied. Equalising constituencies based on the number of potential voters will approach, but not guarantee equal shares in the actual election.", "tags": "", "url": "index.html#4.20.dgf-p.fd0mh.sgbun.dt07n"},
     
     {"title": "Equal Shares", "text": "There are ways to procedurally address this (for instance, dynamically weighting the voting power of the representative based on turnout, or taking non-participation seriously as something that must have practical effects), but mostly this problem reflects that this criteria is best judged on a spectrum rather than pass/fail. Creating more equal numbers of eligible voters does not necessarily achieve this goal, but is likely to move towards it. ", "tags": "", "url": "index.html#4.21.lq6eh.6hdgt.fvewy.fh6jl"},
     
     
     
     {"title": "Independence", "text": "It doesn&#39;t matter which party/candidate you vote for, your vote should count the same", "tags": "", "url": "index.html#5.22.av-wy.tdwos.9as-w.i0tfz"},
     
     {"title": "Independence", "text": "This criteria is addressing the issue that the previous two (which are more commonly seen) are disconnected from outcomes. There are any number of electoral designs that allow equality of participation, but where the structure distorts outcomes so that people&#39;s preferences are not treated equally even if their votes are.", "tags": "", "url": "index.html#5.23.cblrq.qbltt.snwvh.dubic"},
     
     {"title": "Independence", "text": "Splitting a group that may be able to elect their preferred representative among several different districts is &amp;#8216;diluting&#39; that group&#39;s influence, while allowing their voters to be counted equally. While this language is useful in the sense this is a political action done deliberately to deny others their fair representation, where it runs into difficulty is defining the &amp;#8216;natural&#39; representation of a group to compare this unfair arrangement to. In the US, this involves meeting a set of criteria to show practically preferences are being ignored while an alternate scheme is possible. ", "tags": "", "url": "index.html#5.24.yqc8w.w-qjq.wb8b9.ensyx"},
     
     {"title": "Independence", "text": "The independence criteria gives an equivalent individual right to the idea of group right to an undiluted vote: the effectiveness of one person&#39;s vote should be independent of choices made by others. While obviously voters have to stack together in order to gain representation, there should be no efficiency bonuses as a result of the position or preference of a set of voters.", "tags": "", "url": "index.html#5.25.jkj3m.hhszi.t0nsz.whfas"},
     
     {"title": "Independence", "text": "While this is useful to understand and measure harm to individual voters, putting this into practice has a similar issue to articulation of group rights: you have to decide how much divergence is too much to allow. ", "tags": "", "url": "index.html#5.26.7rfxd.m9rpt.iswxc.ierz6"},
     
     {"title": "Equal probabilities", "text": "If you change your vote from one party to another, it should have the same impact as anyone else doing the same", "tags": "", "url": "index.html#equal-probabilities"},
     
     {"title": "Equal probabilities", "text": "This is a fiddly rule related to situations where an election is happening in multiple constituencies, of different sizes with different weights. For instance, if one constituency had 60,000 people and the representative had six votes, and another had 40,000 people and four votes, technically the equal weights criteria is fulfilled while all decision making power rests in the larger constituency. One person changing their vote in one constituency has much more power to change the overall result of the election than a person in the other making the same move. ", "tags": "", "url": "index.html#5.28.rtngr.ynn0e.rqsxq.1zvcm"},
     
     {"title": "Equal probabilities", "text": "This kind of situation should also be detected by violations of anonymity, which is conceptually easier to understand and applies more generally. ", "tags": "", "url": "index.html#5.29.5u7t9.iwnec.1naeq.virgv"},
     
     {"title": "Anonymity", "text": "If you swap your vote with anyone else, it should make no difference", "tags": "", "url": "index.html#anonymity"},
     
     {"title": "Anonymity", "text": "Like equal shares and equal probabilities this problem is a side-effect of splitting the electorate into multiple constituencies. Voters take part in many smaller elections that feed into the larger one. ", "tags": "", "url": "index.html#5.31.hdni-.ccshw.ovz4m.3fmb6"},
     
     {"title": "Anonymity", "text": "Different electoral systems are differentially sensitive to how these voters are distributed. Ideally, exactly the same voters distributed in any combination should have the same result. Otherwise the result is being driven by the structure of the election rather than the preferences of voters. While being in a particular place will be part of conditions that shape how someone votes, for votes to be independent there should be no multiplying effect of those voters being tightly clustered, or negative effect if they are dispersed. ", "tags": "", "url": "index.html#5.32.l0lxh.3bna2.k3fxs.1kwl3"},
     
     {"title": "Anonymity", "text": "This is a useful rule because it provides a simple test of a particular election result to violations of anonymity: running simulations with random swaps of ballots to see the extent of the effect on the election. ", "tags": "", "url": "index.html#5.33.3e1-k.ynn0e.4bptw.bkl6b"},
     
     {"title": "Majority Rule", "text": "The weighting of your vote should not change depending how others vote", "tags": "", "url": "index.html#majority-rule"},
     
     {"title": "Majority Rule", "text": "This is a rule arguing that any requirements for success other than 50% + 1 are unfair to individual voters because it means that one choice rather than another is counted differently. ", "tags": "", "url": "index.html#5.35.6kooz.ynn0e.x409t.walo3"},
     
     {"title": "Majority Rule", "text": "Any supermajority requirement can be understood as changing the weighting of individual votes depending on who is doing better. A 2/3 requirement means that two-thirds minus one votes are collectively counted as less than one-third plus one. ", "tags": "", "url": "index.html#5.36.ma5qp.1wt4c.lvmuk.tlzuf"},
     
     {"title": "Majority Rule", "text": "Supermajority requirements are stacking the deck, and while there may be principled reasons to allow this (just as there may be principled reasons to exclude some people from the franchise), doing so distorts the equality of voters taking part.", "tags": "", "url": "index.html#5.37.w179j.fpt6s._duyo.6cifi"},
     
     
     
     {"title": "Proportional Representation", "text": "Everyone should have the representation they want", "tags": "", "url": "index.html#6.38.9a7ho.bpln8.jdwq_.c_tjz"},
     
     {"title": "Proportional Representation", "text": "Proportional representation can be understood as a stricter restating of equal shares. This time voters should expect an equal share of a representative they support as opposed to a representative in general. Again, this is taking something generally described a group right (parties should be entitled seats in relation to the votes they received) and reframing it as an individual right: you should have the representation that you want. ", "tags": "", "url": "index.html#6.39.ria_f.9uxwg.npvsw.s0fe6"},
     
     {"title": "Proportional Representation", "text": "In most cases, this rule is an unnecessary addition because it will generally be satisfied by fulfillment of previous rules. If all voters have an equal share, anonymity is satisfied, there are no voting arrangements that distort voter power, or unfair requirements for victory, the result should be similar to those delivered by proportional representation voting systems deliver. ", "tags": "", "url": "index.html#6.40.o5hiq.-wbc5.ayawa.gngfs"},
     
     {"title": "Proportional Representation", "text": "That said, PR systems in the real world do not completely fulfill all criteria. National List PR systems commonly have a threshold for representation higher than the &amp;#8216;natural&#39; percentage required to elect one representative. This violates the principle behind majority rule as votes for these parties are weighted down until there are enough of them to pass the test. The single transferable vote (STV) is often part of constituency systems, and so is vulnerable to both equal shares and anonymity violations (if notably less so than other systems).", "tags": "", "url": "index.html#6.41.ijjp6.he88c.cb1er.s2d_h"},
     
     {"title": "Proportional Representation", "text": "The district magnitude (how many seats are available per district/constituency) has a large impact across systems in how possible it is for holders of minority political opinions to have their choice of representative. If a political party is only supported by 1% of the population, you need at least 100 seats to be able to express that. There is always likely to be a gap between systems that perform better than others against these criteria and perfect fulfilment.", "tags": "", "url": "index.html#6.42.nsnxa.pgzgf.v6xuf.jjrob"},
     
     {"title": "Proportional Representation", "text": "The reasons Still lists this criteria separately is that the previous tests can be met without delivering a proportional result. His example of this is a city council with one large district/constituency, where votes have the choice between two slates of candidates, and whichever one gets more votes gets all the seats. This passes all other tests except for this final one, people do not have equal shares of a representative they voted for because one party slate got all the seats and the other got none. ", "tags": "", "url": "index.html#6.43.-cexu.p9whw.o41g1.ehzd6"},
     
     {"title": "Proportional Representation", "text": "What makes this example more complicated is that it is functionally equivalent to having a city run by an elected mayor. The losing candidate for mayor has no representation if they lost by 1% or 40%, is this also a violation of political equality? Still sidesteps this question by saying it only applies to multi-member elections like city councils that _could _have elected representatives in proportion, but taken seriously this actually implies that elected offices that cannot be distributed proportionally violate political equality.", "tags": "", "url": "index.html#6.44.9ppwh.oenge.v330t.xx22x"},
     
     {"title": "Proportional Representation", "text": "If principles for political equality can judge certain electoral systems as better than others, there is no reason why they should not also prefer council leaders over mayors and prime ministers over presidents. Different structures may deliver superior standards for political equality.", "tags": "", "url": "index.html#6.45.f08wy.u-6aq.v330t.1lj3n"},
     
     {"title": "Proportional Representation", "text": "But this also starts to get into the difficult issue of how power is exercised after an election. While political representation can be distributed equally, political power cannot. If there are two parties competing for council seats or a mayor&#39;s office, one will have a majority of the seats and so a monopoly on power. In this instance, does it matter if the other party is represented at all if they can have no substantive impact on the results?", "tags": "", "url": "index.html#6.46.wlm9c.rjsr3.kgria.jygiq"},
     
     {"title": "Proportional Representation", "text": "I think there is a good case that it does. Political outcomes aside, proportional distribution of seats also represents some official resources to minority views. Resources given to opposition politicians are an important part of critiquing current governance and developing potential alternate ones. It is useful to be able to describe it as an issue of political equality, but it is really an issue of good governance. This reflects that political equality is one of many principles that may be important when designing or evaluating a political system. ", "tags": "", "url": "index.html#6.47.dsluw.u2xxa.kxkhn._asv9"},
     
     
     
     {"title": "Other considerations", "text": "The above has explored (and hopefully simplified) Still&#39;s set of escalating criteria for political equality, giving a framework for understanding how systems may violate political equality while fulfilling more basic definitions. These also show how violation of a group&#39;s right to an undiluted vote or to proportional group representation can be understood as a collective violation of individual rights to aspects of political equality. ", "tags": "", "url": "index.html#7.48._vpox.2uc0p.dkuow.mzx5d"},
     
     {"title": "Other considerations", "text": "The highest criteria asks that everyone gets the representation they want, but politics can also be understood as the practice of managing what happens when not everyone can get what they want. Practical realities mean that perfect fulfillment of all criteria is almost impossible, and that raises the question of how good is good enough. Still suggested &amp;#8216;anonymity&#39; was a high enough target, but the better question might be how much political equality can be delivered alongside other considerations of the political system.", "tags": "", "url": "index.html#7.49.zvb0t.hvci0.1vd19.wklln"},
     
     {"title": "Other considerations", "text": "Political equality is only one possible aspect of a democratic system and it is perfectly valid to have other considerations in mind when designing or evaluating how politics should work. Is it preferable that a mayor be elected by AV versus a council leader in a coalition? In the first instance, you know that the majority of voters prefer them to an alternative, but in the second people&#39;s first preference party may extract policy concessions at the price of a lack of clarity about the outcome during the election. Which is superior?", "tags": "", "url": "index.html#7.50.8xz4i.uceu_.jszjx.nr6o7"},
     
     {"title": "Other considerations", "text": "The first provides a clarity of leadership, even if violating aspects of equality. This may be a desirable feature, or not may not. Many choices are possible and the above is not prescriptive about how politics should be, but how to judge and evaluate one (important) dimension of it. ", "tags": "", "url": "index.html#7.51.bn37f.ydi97.kihdp.ekj7c"},
     
     {"title": "Other considerations", "text": "The key thing to understand from this set of criteria is how many of them sit above the common criteria of &amp;#8216;universal(ish) francise&#39; and &amp;#8216;equal constituencies&#39;. They provide a framework for understanding and describing harm to individuals from systems that can pass both those tests. This may be a deliberate decision against other features of a political system, but it is important to recognise and accept a trade-off has been made, and be honest and transparent about this reality.", "tags": "", "url": "index.html#7.52.__qcl.pisqe.lidv3.qiriu"}
     
     
]};