


var tipuesearch = {"pages": [
     
     
     {"title": "Intro", "text": "b&#39;Five years and an abandoned review later, the changes the Parliamentary Voting System and Constituencies Act 2011 will have on British politics are starting to become clear. &#39;", "tags": "", "url": "index.html#1.4257.rzol6.g-q21.32ngm.1s8j9"},
     
     {"title": "Intro", "text": "b&#39;The Boundary Commissions have released their initial plans and the result is a substantial shake-up to British politics: removing 50 MPs and enforcing the strictest approach to equal constituency populations ever &amp;#8211; with the intention of repeating this process every five years to keep the numbers in check. &#39;", "tags": "", "url": "index.html#1.4777.ntn7e.lt09o.21e_p.wmasd"},
     
     {"title": "Intro", "text": "b&#39;Superficially this all seems reasonable, who could object to equality? But these changes come at a cost. Stricter limits on population come at the expense of the idea that parliamentary constituencies should mirror political and cultural boundaries already in existence.  The basis of the review on electoral registers at the same time as the system of registration has been substantially changed has raised complaints that certain areas and groups of people are being systematically under-represented. &#39;", "tags": "", "url": "index.html#1.3056.gjodw.xa1ck.3xxud.advwo"},
     
     {"title": "Intro", "text": "b&quot;This is short paper laying out the historical context for our current system, and using parallels from the explicitly politicalised methods of drawing boundaries in the US to explore the limits of the UK&#39;s apolitical approach. &quot;", "tags": "", "url": "index.html#1.3791.izxfq.qglna.aqk3v.1waug"},
     
     {"title": "Intro", "text": "b&#39;Key points:&#39;", "tags": "", "url": "index.html#1.2425.xrhvo.xrhvo.q9kkl.utwe5"},
     
     {"title": "Intro", "text": "b&quot;Basing constituencies on population rather than the electoral register is a good idea for improving the accuracy of counts that has roots in historical British practice.The fight between &amp;#8216;organic&#39; and &amp;#8216;mathematical&#39; representation in the UK can mostly be understood as a political fight about who benefits.A weighted voting system can achieve both &amp;#8216;organic&#39; and &amp;#8216;mathematical&#39; principles at the same time while being cheaper &amp;#8211; but this can&#39;t make everyone happy because the argument isn&#39;t really about that.Political equality can&#39;t be achieved solely through meddling with boundaries &amp;#8211; and so arguments about equal populations being fairer need to be treated sceptically. &quot;", "tags": "", "url": "index.html#1.3703.xvajm.nsnmw.te67r.vsytk"},
     
     {"title": "Intro", "text": "b&#39;The problem of constituencies&#39;", "tags": "", "url": "index.html#1.3083.bmati.t3m0h.lp4r1.vkja_"},
     
     {"title": "Intro", "text": "b&quot;Democracy is &amp;#8216;One Person, One Vote&#39;. There&#39;s more to it than that, but in those four words you get across the always radical idea that one person&#39;s vote should never be worth more than another&#39;s. &quot;", "tags": "", "url": "index.html#1.2147.ckxus.j3_a-.pufql.j9j4k"},
     
     {"title": "Intro", "text": "b&quot;But as soon as you have multiple constituencies you have a problem with this. If I&#39;m one of 100 voters in one area, and you&#39;re one of 1000 in another &amp;#8211; my vote is worth more than yours. If you care about everyone&#39;s say being equal you now need to begin a never-ending balancing act that constantly moves the lines to keep the population of constituencies as similar as possible.&quot;", "tags": "", "url": "index.html#1.1174.l6e0r.dyrn3.jyz8w.nqi_u"},
     
     {"title": "Intro", "text": "b&#39;In the United Kingdom these lines are drawn by Boundary Commissions, who are charged with drawing boundaries according to a set of politically-neutral criteria. US states handle apportionment in various different ways - but it tends to be highly political and directed by the state legislature (with the occasional role for governors or outside commissions) with court-imposed requirements that they must fulfil.&#39;", "tags": "", "url": "index.html#1.8719.q74jo.qxcse.kupom.ihndg"},
     
     {"title": "Intro", "text": "b&quot;Whilst there is variation in exactly which metric is being equalised (In the US it is total population including those ineligible to vote, while in the UK it is only those who are explicitly registered to vote) over the past 60 years there has been a move in multiple countries in favour of prioritising the idea of equal population in matters of apportionment. The court-led &amp;#8216;apportionment revolution&#39; in the United States in the 1960s led to a tight focus of apportionment on equal population, Australia abolished the rural loadings (which gave additional representation to rural areas) in the 1980s, and in the UK successive boundary reviews placed a greater emphasis on the principle of equal populations and removed the over-representation of non-English nations as a part of devolution settlements. &quot;", "tags": "", "url": "index.html#1.3518.vhljb.thlyl.ixfyt.5kbdb"},
     
     
     
     {"title": "Organic and Mathematical Approaches", "text": "b&quot;Geographic barriers are a common problem in trying to divide a place into even blocks.  The most obvious examples are under-populated islands separated from the mainland such as India&#39;s Andaman Isles^1 or Orkney and Shetland and The Western Isles in the UK (which were marked as exempt from population equality by the Parliamentary Voting System and Constituencies Act 2011^2). But it&#39;s not just oceans you have to worry about, some areas are so sparsely populated that an equal population would be so vast it would present practical difficulties in representing. While they might have numerically equal representation, their representation would be less effective as a result of the many, small, communities they would be representing.&quot;", "tags": "", "url": "index.html#2.4841.hf945.ad_-q.zpf8e.b1jmi"},
     
     {"title": "Organic and Mathematical Approaches", "text": "b&quot;Here is the essential divide: Should purely &amp;#8216;mathematical&#39; equality be prioritised over all other considerations? Or is there such thing as an organic community that should be represented? &quot;", "tags": "", "url": "index.html#2.505.9p6yh.qvvpg.3xxud.jumra"},
     
     {"title": "Organic and Mathematical Approaches", "text": "b&#39;This idea of community representation is the older form and can be found in requirements to not cross county lines, local government areas, and to take into account the geographical make-up of an area. In the US this has taken on additional meaning as a need to provide community representation for ethnic minority groups since the Voting Rights Act of 1965.^3&#39;", "tags": "", "url": "index.html#2.7085.m70e7.k5gyz._5mue.lbhxw"},
     
     {"title": "Organic and Mathematical Approaches", "text": "b&#39;Until the 1950s the organic view was dominant in the UK. Between 1917 and 1947 there were no boundary alterations (leading to some extreme disparities in electorate size^4) and while the House of Commons (Redistribution of Seats) Act 1944 explicitly prioritised the mathematical over the organic principle, a new act had to be passed several years later removing this prioritisation because the commissions were finding it too difficult to achieve. Balancing out populations while respecting local government boundaries and not increasing the size of the House of Commons proved an impossible task.^5 With successive boundary reviews the mathematical principle has become increasingly prominent, with the review set in motion by the Parliamentary Voting System and Constituencies Act 2011 representing the culmination of this with a requirement to create constituencies within 5% of the average population.^6&#39;", "tags": "", "url": "index.html#2.2083.c7bl4.kjurq.lodu2.i7nmd"},
     
     {"title": "Organic and Mathematical Approaches", "text": "b&#39;In the United States, the drive towards greater mathematical equality was driven by the courts determining the constitutionality of various representation schemes. The 1964 case Reynolds v Sims led to a rule that variance in population between the largest and smallest congressional seats must be less than 1% and struck down provisions within states for separate representation for individual counties regardless of population.^7 The historical dominance (and popularity) of the organic principle creates problems for political equality in that the rules and considerations generated by the organic principle tend to detract from more exact mathematical equality. &#39;", "tags": "", "url": "index.html#2.9982.qvnat.qxcse.dkuow.2qpnw"},
     
     {"title": "Organic and Mathematical Approaches", "text": "b&#39;Working solely on the mathematical principle, there are problems in obtaining the source information required to divide the population evenly. Methods of counting populations are often error-prone at the outset, vary in completeness in different regions and often systematically undercount certain social groups. The next problem is that even assuming a completely accurate count, this can rapidly become out of date. Births, deaths and population movement quickly erode the accuracy of a count and any divisions based on it. Similar problems can be found in both the UK Electoral Registers and US Census. &#39;", "tags": "", "url": "index.html#2.250.efghy.5ng3h.lou7f.nxiqh"},
     
     
     
     {"title": "US population-based approach", "text": "b&#39;In the US, apportionment on the federal level is decided by the total number of people present within the 50 states (whether or not they are citizens) and any federal employees living abroad.^8 The US basis on total population rather than eligible population is the result of a constitutional requirement that &quot;Representatives and direct Taxes shall be apportioned among the several States which may be included within this Union, according to their respective Numbers&quot; and the same article lays out plans for a census every decade to obtain those numbers.^9&#39;", "tags": "", "url": "index.html#3.4533.c80m2.qg61o.bmilf.ybxqw"},
     
     {"title": "US population-based approach", "text": "b&#39;The reason for this method isn\&#39;t a belief that government is there to represent everyone &amp;#8211; but a result of a group wanting over-representation. This clause originally included the famous &quot;three fifths&quot; provision that added 0.6 to the count for every slave present. It was a compromise agreement to inflate the representation of slave states. &#39;", "tags": "", "url": "index.html#3.2417.mejjz.p9whw.eziqm.aqo8a"},
     
     {"title": "US population-based approach", "text": "b&#39;That the method of a census is in the constitution causes problems for modern census takers. A direct count (through household surveys and follow-up visits for non-returns) is likely to return a significant undercount in various areas but this constitutional provision has been taken to rule out the use of modern sampling methods to work around this problem.  Whilst in Department of Commerce v United States House of Representatives the Supreme Court ruled that sampling data could be used within states to create district boundaries, it upheld that the allocation of seats among the states must continue to be determined by directly obtained figures.^10 Most concerning, the resulting undercount is &quot;geographically and demographically uneven&quot;, being more likely to undercount poorer communities, communities of ethnic minorities and migrant workers. In the worst cases it is estimated the undercount may be as high as 50%^11 which as district sizes are required to fall within 1% of the quota size means in some cases US electoral law requires far greater equality than it actually has the means to detect.^12&#39;", "tags": "", "url": "index.html#3.1405.skkwr.32o2a.tmq65.fc5hx"},
     
     
     
     {"title": "UK electorate-based approach", "text": "b&#39;tag:ukelectorate&#39;", "tags": "", "url": "index.html#4.4313.b_nl7.7frbd.6br_-.2jmj7"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;In the UK apportionment is based upon currently registered names on electoral registers rather than the raw population. To find the origins of this we start with a problem in the 19th century. Here we have the idea of &amp;#8216;electors\&#39; for seats, but because rights to a seat in parliament were ancient and populations change, the number of electors per seat could vary between a dozen and 12,000. Those with almost no electors were the &quot;pocket boroughs&quot;, where all the electors were effectively under the control of their local MP and so elections were uncontested. As the problem was talked of in terms of this imbalance between electors, the initial solutions in the first few reform acts involved eliminating the worst of these boroughs and assigning more representation to the new northern industrial towns^13. &#39;", "tags": "", "url": "index.html#4.7404.7dnez.gaidd.wpkeu.higbo"},
     
     {"title": "UK electorate-based approach", "text": "b&quot;It&#39;s tempting to draw a line between talk of imbalance of electors and our current approach - but when the Reform Act of 1867 created a commission to investigate boundaries they were explicitly tasked with investigating population rather than electors:&quot;", "tags": "", "url": "index.html#4.7169.fmvxl.ub23x.3g7bs.ye87a"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;They shall also inquire into the temporary divisions of counties as constituted by this Act, and as to the places appointed for holding courts for the election of Members for such divisions, with a view to ascertain whether, having regard to the natural and legal divisions of each county, and the distribution of the population therein, any, and what, alterations should be made in such divisions or places.^14&#39;", "tags": "", "url": "index.html#4.2299.7qcbz.0eesq.yixss.v2t8v"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;Similarly the 1885 instructions to the Boundary Commission for England and Wales talked of population:&#39;", "tags": "", "url": "index.html#4.4219.s9_ol.jl8if.xlfm5.zawhw"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;In dealing both with County and Borough divisions, the boundaries of the divisions must be adjusted so that the population, excluding in the case of County division that of the Parliamentary Boroughs, may be proximately equalised and in the arrangements of the divisions special regard shall be had to the pursuits of the population. ^15&#39;", "tags": "", "url": "index.html#4.5842.hijzl.aoerv.zv0-i.wmjak"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;The 1917 Boundary Commissions again used the language of population and stated that &quot;population&quot; was:&#39;", "tags": "", "url": "index.html#4.3848.rfo6_.syu4u.kablp.xgchd"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;The population as estimated by the Register-General for the middle of the year 1914.^16&#39;", "tags": "", "url": "index.html#4.7989.wgw5v.azmju.pz8zt.qoedq"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;The switch to electorate based language can first be seen in a 1934 private members bill that suggested a quota:&#39;", "tags": "", "url": "index.html#4.9020.bunhp.e8ejl.qpb1c.2vtfx"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;Based on the number of registered electors of the United Kingdom of Great Britain and Northern Ireland, other than those of the City of London and the universities, divided by six hundred and fifty.&#39;", "tags": "", "url": "index.html#4.9256.mdcsq.gciwa.lhwae.ob2o3"},
     
     {"title": "UK electorate-based approach", "text": "b&quot;This bill didn&#39;t get far, but the 1944 Speaker&#39;s Conference (which led to the modern system of regular reviews) recommended that:&quot;", "tags": "", "url": "index.html#4.7052.fonmg.0spvg.yd0ot.kjxa7"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;The standard Unit of electorate for each Member of the House of Commons for Great Britain shall be a quota ascertained by divided the total electorate in Great Britain by the total number of seats in Great Britain^17&#39;", "tags": "", "url": "index.html#4.5981.pvtxr.qtt81.yhye-.rdaev"},
     
     {"title": "UK electorate-based approach", "text": "b&quot;The obvious reason for this change in language is that the definitional distance between electorate and population had almost entirely closed. The franchise had been expanded to women in 1928 and so the only people were not the &amp;#8216;electorate&#39; were children and non-citizens. &quot;", "tags": "", "url": "index.html#4.7056.01oqf.mnqb5.mudmd.0eax1"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;There was a precision advantage as well &amp;#8211; there is an exact register of electors. While in 1917 constituency population was based on an estimate, in the House of Commons (Redistribution of Seats) Act 1944 the &quot;electorate&quot; was:&#39;", "tags": "", "url": "index.html#4.5154.qxvzq._auu7.unms7.l6scw"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;The number of persons whose names appear on the parliamentary register of electors for the constituency^18&#39;", "tags": "", "url": "index.html#4.1936.zk0ig.vgtfy.snnwi.ywmmp"},
     
     {"title": "UK electorate-based approach", "text": "b&quot;The problem this leaves for us in the modern day is that this solution may be precise, but it is not accurate. Just because there may be 17,231 people registered in an area, doesn&#39;t mean that there are 17,231 people eligible to be registered, or that that number is constant over time. &quot;", "tags": "", "url": "index.html#4.5682.vjask.t3m0h.ov9qv.segsv"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;In seven case studies the Electoral Commission found that under-registration was higher among 17-24 year-olds, private sector tenants and black and minority ethnic British residents.^19 Their report also found that population movement leads the electoral registers to be around 10% less complete by the following December, with that figure being even higher in inner London boroughs.^20 Whilst it is clear the electoral registers are inaccurate, methods of determining how inaccurate and incomplete they are often are either prohibitively expensive, tied to the census (and so become increasingly less reliable as time passes) or likely to be a victim of the same under-response pattern that led to the original registration problem.^21&#39;", "tags": "", "url": "index.html#4.9757.xgzzs.mixuu.zorpr.aq9gt"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;The switch from household representation to individual electoral registration might in the long run address the issue of inaccuracy for some groups (like private tenants) by making it easier to register when moving. But while a system that makes it easy and quick to register means it is likely that more people will be able to register to vote for elections, the accuracy of those counts several years out is unlikely to improve as these people have little incentive to register. &#39;", "tags": "", "url": "index.html#4.4321.mzvao.e8ejl._t-ad.kf2ld"},
     
     {"title": "UK electorate-based approach", "text": "b&#39;For the 2018 review around 1.75 million people joined the registers between the cut-off of December 2015 and the EU referendum in 2016 (and as these are unevenly distributed, using the later register would result in some regions receiving more seats and others less). While it will probably be rare for the register to increase immediately after an election, that the register can increase by any number sufficient to make a difference in just six months reflects the gulf between registered and potential electors.&#39;", "tags": "", "url": "index.html#4.7360.qa62g.w_vri.3g7bs.8kzek"},
     
     {"title": "UK electorate-based approach", "text": "b&quot;The Electoral Reform Society argue we should switch to a system based on population rather than registered electors &amp;#8211; and this seems like a good idea. The switch from the population metric in the 40s was an attempt to escape the fuzziness of population estimates &amp;#8211; but we&#39;ve trading in known imprecisions for unknown inaccuracies. To increase the accuracy of constituency boundaries, we must embrace less precision. &quot;", "tags": "", "url": "index.html#4.9094.8yege.0nhu0.an7ds.2l__z"},
     
     
     
     {"title": "Equality is about actual voters", "text": "b&quot;Even if constituencies could be built off a perfect source of information about how many people were living where, it wouldn&#39;t remove all the components of inequality. What matters isn&#39;t how many people can vote, but how many people do. Balancing the populations down to 1% is pointless if 50% vote in one and 70% in the other &amp;#8211; a person&#39;s share in the election is different in different places.  In the 2015 UK General Election there was a 30.7% range in turnout between constituencies^22, creating a variation in equal weighting that would remain and undermines efforts to equalize constituency populations. Brookes refers to this turnout component of bias as &amp;#8216;reactive malapportionment&#39; and the tighter you make your requirements, the more this will throw you off.^23 &quot;", "tags": "", "url": "index.html#5.2223.tzk_y.t00i4.l6kfy.cttk4"},
     
     {"title": "Equality is about actual voters", "text": "b&quot;Although aiming for equal shares isn&#39;t a bad idea, current methods to fulfil it aren&#39;t successful enough to make it clear that they deserve obvious primacy over considerations like the &amp;#8216;organic&#39; principle. Tight quotas require precision that just isn&#39;t possible given our data sources. &quot;", "tags": "", "url": "index.html#5.7229.qohgk.ue-t4.pff1k.hbgcm"},
     
     {"title": "Equality is about actual voters", "text": "b&#39;This question is further complicated by the fact that debates over the importance of local ties and population equality are often cloaking arguments about political outcomes &amp;#8211; so this debate is rarely held in good faith. &#39;", "tags": "", "url": "index.html#5.7278.vllfi.n0ztd.spmnd.98hbb"},
     
     {"title": "Equality is about actual voters", "text": "b&#39;Boundaries are Political&#39;", "tags": "", "url": "index.html#5.8795.qkex_.z2fny.hyp8x.kg-y7"},
     
     {"title": "Equality is about actual voters", "text": "b&quot;Arguments about boundaries aren&#39;t really abstract discussion of &amp;#8216;community&#39; vs &amp;#8216;individual&#39; representation &amp;#8211; they&#39;re arguments about outcomes. Drawing one set of lines rather than another results in different people being elected, different governments being formed and different policies being enacted. Boundary drawing in an inherently political act. &quot;", "tags": "", "url": "index.html#5.2907.rsyev.grxmj.ejn_i.4_pst"},
     
     {"title": "Equality is about actual voters", "text": "b&quot;In the UK we might feel superior when looking at the nakedly political US system of line drawing, but in reality our arguments about boundaries are no less political &amp;#8211; we just dress them up in neutral language. Conservatives like boundary reviews and tighter mathematical precision because it&#39;s good for them &amp;#8211; Labour like organic constituencies and less frequent reviews because of the reverse. It&#39;s hard to imagine if the demographic situations was reversed they wouldn&#39;t switch arguments. &quot;", "tags": "", "url": "index.html#5.4819.cpnx3.gaidd.etyp_.b9g7t"},
     
     {"title": "Equality is about actual voters", "text": "b&#39;In fact, we know this is the case because when size inequalities were in the Conservatives favour in the 19th century, Disraeli was opposed to frequent redistributions:&#39;", "tags": "", "url": "index.html#5.3333.itme5.2okfj.lhyba.91giq"},
     
     {"title": "Equality is about actual voters", "text": "b&quot;In thinking about how drawing lines results in different politics it&#39;s important to remember that political equality doesn&#39;t end at equal population. Jonathan Still defined several further criteria for political equality in boundary issues and these include the idea of &amp;#8216;anonymity&#39;.^25 This stated simply is that it shouldn&#39;t matter where in the structure of an election a vote is &amp;#8211; the result should be the same. Swapping voters with another voter should not change the result &amp;#8211; if it does, the election is treating people&#39;s preferences unevenly depending where they are. If you can shuffle the electorate and end up with a different result, you&#39;re not counting the deck fairly. &quot;", "tags": "", "url": "index.html#5.5850.cjy6r.64sbj.vrinc.vfdj-"},
     
     
     
     {"title": "Minority group rights", "text": "b&#39;This issue is especially obvious in treatment of minorities in the US.^26 As the US Supreme Court argued in Reynolds v Sims:&#39;", "tags": "", "url": "index.html#6.4164.a-mjw.xdshc.bb0un.jfrlh"},
     
     {"title": "Minority group rights", "text": "b&#39;&quot;There is more to the right to vote than the right to mark a piece of paper and drop it in a box or the right to pull a lever in a voting booth. The right to vote includes ... the right to have the vote counted at full value without dilution or discount&quot;.^27&#39;", "tags": "", "url": "index.html#6.6094.i7p3z.o8agv.9opsl.vgpda"},
     
     {"title": "Minority group rights", "text": "b&quot;This suggests that minority groups are entitled to have protection against having their vote &amp;#8216;diluted&#39; by the apportionment process. Dilution can take two forms, either being &amp;#8216;packed&#39; into a single district which can result in a large amount of excess votes for their preferred candidates (as every vote over the plurality required to win is a wasted vote that would be more efficient if it was electing a candidate elsewhere), or &amp;#8216;fractured&#39; by splitting the minority group among so many districts that they cannot have an influential effect on any of them.^28 In a typical case it is seen that splitting up an African-American community into several small factions can be an attempt to submerge their voting power and hence deny them their fair representation. However, as this feature is an inherent result of any division of the electorate, hard and fast measurements of what constitutes a harmful racial gerrymander are challenging.&quot;", "tags": "", "url": "index.html#6.7541.dzjue.s0tdd.223fb.lrcil"},
     
     {"title": "Minority group rights", "text": "b&#39;In some cases it has been established that the courts will only reject a plan that is challenged on these grounds if it can be demonstrated that the state could have drawn &quot;an additional, compact majority-minority district&quot;^29, but there is also an argument that majority-minority districts over-concentrate minority voters and so are guilty of &amp;#8216;packing\&#39; and dilute minority voters in another sense. While there is some disagreement over the extent of this, Shotts demonstrates this is at least sometimes true^30, and Lublin and Voss found that racial redistricting cost Democrats (the usual recipient of minority votes) control of at least two state legislatures in the 1990s.^31 Lowenstein and Steinberg argue that &quot;voting strength cannot be characterized as diluted unless it can be compared to a level of strength that is agreed to be normal&quot;^32, and as such dilution cannot be assessed quantitatively if there are no obvious set of conditions that would provide optimal minority representation. &#39;", "tags": "", "url": "index.html#6.4302.esqi5.0d7xb.wkclk.zkjpn"},
     
     
     
     {"title": "The role of ‘neutral&#39; rules", "text": "b&#39;tag:conflict&#39;", "tags": "", "url": "index.html#7.9934.alu_9.diura.riffe.2jmj7"},
     
     {"title": "The role of ‘neutral&#39; rules", "text": "b&quot;While partisan districting is obviously suspicious, &amp;#8216;neutral rules&#39; need to be looked at carefully. Lowenstein and Steinberg argue these are anything but neutral as any particular rule is likely to lead towards a predictable political outcome.^33 While imposing a criteria of compact districts are often seen as a defence against partisan gerrymandering (as this discriminates against the long, lizard-like shape that characterises the gerrymandered district), compact districts are also generally seen to favour Republicans over Democrats because as Democratic votes are more tightly clustered, it will force more wasted votes for Democrats than Republicans.^34 This suspicion of neutral criteria is something that&#39;s borne out by the experience of the Boundary Commissions in the UK. The Boundary Commissions make their decisions entirely on the basis of neutral criteria, but it is clear that various sets of rules give favour to certain parties over others.  &quot;", "tags": "", "url": "index.html#7.4603.-aehq.mv3yl.hwviz.o_0tn"},
     
     {"title": "The role of ‘neutral&#39; rules", "text": "b&#39;As the Boundary Commissions\&#39; includes the opportunity for interested groups to provide feedback and criticism of the provincial boundaries, this is when parties will attempt to influence the inquiry to adopt boundaries that are in their favour. As the Committee cannot consider political outcomes, &quot;many of the political arguments are put to the commissions cloaked in arguments about local ties&quot;.^35 Population movements in the UK have meant that the boundaries become progressively more favourable to Labour as the boundary review becomes more outdated. During the lifetime of constituencies created by the Third Review the pro-Labour bias grew at rate of about two seats a year.^36 Labour often try to make a case for the &amp;#8216;status quo\&#39; under the argument that these constituencies represent natural communities that would be harmed if reallocated.^37 In the Fourth Review, there was an increase in the bias from seven to twelve seats between the provisional and final review showing that the process of reviews could be efficiently exploited in a party\&#39;s favour.^38 &#39;", "tags": "", "url": "index.html#7.6498.mebmd.ew30p.mlegb.a_iiq"},
     
     {"title": "The role of ‘neutral&#39; rules", "text": "b&#39;A typical example was a plan in Nottinghamshire to make &quot;adjustments to 5 of the existing 11 seats, to reduce the disparity in the electorates&quot; that was overturned at the public inquiry, forcing a return to the existing constituency plan because of the breaking of local ties that this proposal would have caused.^39 In return it is not a surprise that the Conservative Party have become increasingly strong advocates of the mathematical principle because commitment to it reduces some of the components of bias against them and implies the need for more frequent redistribution, which limits the gradual increase in bias.&#39;", "tags": "", "url": "index.html#7.2156.zmcry.z4bps.lhmni.mi-lk"},
     
     {"title": "The role of ‘neutral&#39; rules", "text": "b&quot;The removal of the Local Inquiries by the 2011 Act means the new review makes the process substantially quicker and remove a mechanism that reduces mathematical equality. While there are valid arguments in favour both of continuity of representation and equality of representation, that a divide has emerged over a principle where each side is aligned with the side that favours it electorally suggests that not all debates over the rankings of &amp;#8216;neutral&#39; criteria are made in good faith.  &quot;", "tags": "", "url": "index.html#7.9470.tj-u6.6punb.7xenj.oy3zt"},
     
     
     
     {"title": "Can we prioritise competitiveness?", "text": "b&quot;As different political outcomes are inherent there&#39;s an argument we should allow our neutral arbitrators to be aware of that and to try for an apolitical political aim: an increase in competitiveness. As the commissions currently cannot consider political outcomes, they cannot make a judgement that a plan for 10 safe seats with perfectly balanced populations is less desirable than a plan with 10 competitive seats with a less balanced population. &quot;", "tags": "", "url": "index.html#8.8056.2ciym.ylorx.sx8nu.iho8m"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&quot;IPPR have suggested that the commissions be actively tasked with reducing the number of safe seats. While there are practical problems with achieving this, it&#39;s worth thinking about the problems that success would cause. How many should be competitive? How competitive? If you make it too many a very small swing in general sentiment would deliver very large majorities. Is that a desirable outcome? Should the commissions instead create a balance of safe and marginal seats so that majorities are never too large? Is that any better?&quot;", "tags": "", "url": "index.html#8.9025.uc1aq.f-gxu.wyjar.bhbxu"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;Examining a similar idea floated in the US (the &quot;Competitiveness Criterion&quot;) Lowenstein and Steinberg point out that competitive districts are often so because of local factors, and these can change:&#39;", "tags": "", "url": "index.html#8.3871.sp2ev.wcwa5.cymdj.f9wyr"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;An additional problem arises because competitiveness is not a trait that a district has independent of surrounding circumstances, and those circumstances are not stable. In particular, incumbency is ordinarily a major consideration in assessing the competitiveness of a district.&#39;", "tags": "", "url": "index.html#8.9276.2iqe_.zoqo4.w-0m1.muu2p"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;As such, a district with a longer incumbent would require more weighting to be given to its opponent &amp;#8211; who might in turn become the incumbent and need lines changed to limit. And so on. Maintaining competitiveness requires constant maintenance.&#39;", "tags": "", "url": "index.html#8.3875.rrwrh.yobpt.hjdi3.ggwny"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&quot;This then raises further questions: Why is it inherently good that an MP with 70% support should have the lines moved so they have so they have a more reasonable 52% support? There is more of a chance that they&#39;ll be removed &amp;#8211; but also more people unhappy with their representation. All of these competing metrics make working out a coherent plan for competitiveness virtually impossible. &quot;", "tags": "", "url": "index.html#8.3200.uphbz.2_qji.wb8b9.pzgzj"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;We want voters to be presented with an honest choice &amp;#8211; but because winner-take-all electoral systems are so bad at translating sentiment into seats, meddling with the boundaries to try and give them that choice ends up causing different problems downstream. &#39;", "tags": "", "url": "index.html#8.6017.5g55z.jz9f9.9kryo.jmgd7"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;Lowenstein and Steinberg end up arguing that:&#39;", "tags": "", "url": "index.html#8.2161.kc2ro.r9bic.chugn.pwy43"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;Redistricting should be one of the objects of the political struggle, not one of the ground rules.&#39;", "tags": "", "url": "index.html#8.1214.zs2xh.qnes5.vnph4.0eb4b"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&quot;Such a naked defence is of political districting is odd to British eyes because we like to believe that neutral rules keep political impacts at bay - but that it&#39;s naive to think apolitical criteria are a solution is a recurrent idea in US discussions of gerrymandering. Morrill (who is in favour of a competitiveness criterion) argues that:&quot;", "tags": "", "url": "index.html#8.7065._atwu.nwlsx.cple4.amgf4"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;To ignore all political considerations or electoral data, as advocated by Common Cause (1977). Since the purpose of voting for representatives is usually to select persons of a party, this alternative is nonsensical and even dangerous &amp;#8211; nonsensical because it ignores the purposes of governance, dangerous because it can result in severe electoral bias, and hence voter disillusionment.&#39;", "tags": "", "url": "index.html#8.7610.sov3n.7n_rr.ob6bw.2f-ks"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&quot;This isn&#39;t to suggest that things wouldn&#39;t be different if we let politicians draw boundaries how they want &amp;#8211; just less different than you&#39;d think. In arguing against a competitiveness requirement in the UK Johnston, Pattie and Rossiter point out that:&quot;", "tags": "", "url": "index.html#8.6398.b9os8.ilg7e.nzmxz.xywkp"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;Substantial research done more than thirty years ago showed that in many places whatever constituency boundaries were drawn the outcome would be a very similar set of election results. If party X dominates in an area, a city say, then it is very unlikely that party Y can win many seats there, however hard you try to gerrymander the situation: the research showed that &amp;#8211; in the late 1960s/early 1970s &amp;#8211; it was not possible to create a Conservative seat, or even a marginal Labour seat, in either Hull or many London boroughs, and very difficult to create one in Leicester. In most rural shires, by contrast, it was very difficult then to create other than Conservative hegemony.&#39;", "tags": "", "url": "index.html#8.49.jshht.yind3.xyf9i.3z9ce"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;This suggests that even if we scrapped the commissions and let the government create partisan plans, they would struggle to gather much more of an advantage than the neutral commissions themselves allow. &#39;", "tags": "", "url": "index.html#8.6965.txh__.s0tdd.87tjb.hjnp0"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;Is There A Better Way?&#39;", "tags": "", "url": "index.html#8.721.uiamc.jz_dv.ryffq.pl5-e"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;There are a few key principles that have emerged in drawing boundaries:&#39;", "tags": "", "url": "index.html#8.3698.gk_re.6hdgt.uv6x4.mjzas"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;There is value in votes being roughly equally weighted.There is value in representation for a place and unity between layers of government.There is value in stability of boundaries across elections. &#39;", "tags": "", "url": "index.html#8.2336.-hva_.vhwe5.tvjus.fbpdq"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;The problem is here the stricter you are on 1, the more problems you have for 2 and 3. &#39;", "tags": "", "url": "index.html#8.8173.ne9ga.t3m0h.b5bsa.bxg2r"},
     
     {"title": "Can we prioritise competitiveness?", "text": "b&#39;The more important exactly equal constituencies are, the more you will create unnatural groups of places &amp;#8211; and the more often you will have to do it to reflect constantly changing populations. The tighter your criteria, the sooner they will be broken. There is a way out of the problem, we just need to take a different approach to how we equalise constituency.&#39;", "tags": "", "url": "index.html#8.7306.j6qq6.o93ks.sgkax.e1vgg"},
     
     
     
     {"title": "Weighted voting", "text": "b&#39;tag:weightedvoting&#39;", "tags": "", "url": "index.html#9.4170.bkgd8.ew-m-.sxwmq.2jmj7"},
     
     {"title": "Weighted voting", "text": "b&#39;When we say &quot;one person, one vote&quot; we\&#39;re talking about voters. We try to equalise it by making sure each MP covers an equal number of people &amp;#8211; so that each person gets an equal share of them. But this is the wrong way of looking at it. Why should an MP\&#39;s worth be static and voters dynamic? What if we did it the other way round and adjusted the weight of a MPs vote depending on the size of their constituency? What if moving 10,000 people into a constituency increased a MPs voting weight, rather than requiring the line to move?&#39;", "tags": "", "url": "index.html#9.2631.hj-wo.lrrvr.uyas0.-hdcg"},
     
     {"title": "Weighted voting", "text": "b&quot;Banzhaf draws out problems with certain implementations of this, looking at the situation Nassau County&#39;s Board created where certain legislators had far more real legislative power than their share of the vote weight would suggest. If a single member has a high voting weight compared to the other members, they might always hold the ability to decide if a measure passes or fails and this means that the other legislators have effectively no voting power, or that a small number of legislators can dominate out of proportion to their actual representation.^40 This issue can be avoided as long as individual voting weights are still much smaller than a significant percentage of the total power of the chamber &amp;#8211; for instance by limiting the range of weights (akin to limiting the range of population allowed). So the problems Banzhaf describes apply only to small scale implementations of weighted voting and are fixable in the same way Madison argues in Federalist No. 10 that you solve other problems of democracy: you make it bigger. &quot;", "tags": "", "url": "index.html#9.6788.dtvzb.ti5l0.y3osa.dnxzj"},
     
     {"title": "Weighted voting", "text": "b&quot;In this spirit Toplak proposed a system for the US House of Representatives that resolved issues of rounding and mismatches between states by giving representatives a voting weight exactly equivalent to the population they represented.^41 This means exactly equal populations would then be off the table as a boundary issue and &amp;#8216;natural&#39; communities could be more easily represented. The House of Representatives is sufficiently large that there are no voting power concerns and the over-representation of small states (that require at least one seat, but their population is smaller than the average district) would be resolved. &quot;", "tags": "", "url": "index.html#9.4130.etngu.alloi.ozhxi.jovus"},
     
     {"title": "Weighted voting", "text": "b&quot;We don&#39;t even have to be quite that precise to make the work of the boundary commission easier. If we say an MP representing the ideal-sized constituency had a weight of 1, we can allow variation from this by allowing the commissions to create constituencies where MPs had weights from 0.8 to 1.4 (with larger possible in extreme cases). This would end up with most MPs having broadly similar weights (making the sums easier) but making it much easier to fulfil all the principles above. &quot;", "tags": "", "url": "index.html#9.5758.y29i8.-50nj.tjdas.czyic"},
     
     {"title": "Weighted voting", "text": "b&quot;You can have a &amp;#8216;normal&#39; boundary report every few decades, but in between those you simply tweak the numbers to keep populations even. This gives voters equal shares with far less disruption. Constituencies would be stable and more &amp;#8216;natural&#39;, but respond to movements of voters in every election. &quot;", "tags": "", "url": "index.html#9.3340.zxbcm.uj5xu.4bptw.rjdsq"},
     
     
     
     {"title": "Relative Complexity", "text": "b&quot;The clear objection to a weighted voting system is that it seems complicated. But it&#39;s worth thinking about how complicated our current system is by comparison:&quot;", "tags": "", "url": "index.html#10.6154.tstnw.bbvpt.4fcsa.vr_co"},
     
     {"title": "Relative Complexity", "text": "b&#39;Every five years we will have new boundaries. MPs will never represent the same area more than once. There will always be people being moved from one to another for essentially arbitrary reasons. Parliamentary constituencies are disconnected from local governments, resulting in MPs with constituents in several different areas. More alignment might be possible between local authority and parliamentary boundaries &amp;#8211; but only by splitting wards (the lowest building block at this point).  &#39;", "tags": "", "url": "index.html#10.8539.o27ee.p8nep.5yyij.chjdj"},
     
     {"title": "Relative Complexity", "text": "b&#39;Boundary reviews are fiddly work, and strict and constant reviews reduce simplicity is how people relate to their government and how the different layers of government relate to each other. By comparison, having to make an app for whips to count their differently weighted MPs is probably a reasonable compromise. &#39;", "tags": "", "url": "index.html#10.2258.2xpvr.w5ihp.fnbfa.uhl40"},
     
     {"title": "Relative Complexity", "text": "b&quot;It&#39;s also worth remembering the cost of all these reviews. While figures for the current review aren&#39;t available, an FOI request shows the cost of the previous English review in 2011-13 was &amp;#163;4.3 million and the cost of the Northern Ireland review &amp;#163;557,000. From this we can estimate a cost of around &amp;#163;6 million for the complete review. While the 2018 review hoped to reduce costs through digital release and limited print releases, 54% of the 2011-13 costs of the English review were for staff. Even a significant reduction would still be expensive.  &quot;", "tags": "", "url": "index.html#10.9901.pqcmi.ftw5f.uzcjp.sh9wu"},
     
     {"title": "Relative Complexity", "text": "b&quot;A pure numeric adjustment every five years would be significantly cheaper and quicker (achievable in days rather than years). You could even run it off the electoral register as it existed for the election itself &amp;#8211; ensuring representation was working off the most up to date figures possible. A &amp;#8216;normal&#39; reallocation every twenty years (which can work to less strict requirements) would be reducing the long-term costs of redistricting by 75% - at the same time as making nicer constituencies balanced more exactly. &quot;", "tags": "", "url": "index.html#10.3907.zqav9.ardlp.euba5.bixcm"},
     
     
     
     {"title": "Would this make people happy?", "text": "b&quot;This solution technically resolves the tension between the &amp;#8216;organic&#39; and &amp;#8216;mathematical&#39; form of representation. Would it end the debate? Of course not, because this is really an argument about political outcomes. &quot;", "tags": "", "url": "index.html#11.8146.psnwv.fp_1s.ugpqa.knvft"},
     
     {"title": "Would this make people happy?", "text": "b&#39;Rossiter, Johnston and Pattie split the bias resulting from boundaries into two main causes: &#39;", "tags": "", "url": "index.html#11.3482.z9eer.2hmxo.7auqe.blapq"},
     
     {"title": "Would this make people happy?", "text": "b&#39;Difference in average size of constituency &amp;#8211; a party will return more MPs if its support is concentrated in smaller constituencies. Efficiency - a party which avoids piling up huge majorities in its safer constituencies while managing to win a disproportionate number by relatively small margins will benefit from efficacy bias. ^42&#39;", "tags": "", "url": "index.html#11.711.8izue.ngpon.edrmb.wduad"},
     
     {"title": "Would this make people happy?", "text": "b&quot;A weighted vote system is equally (and arguably better) at resolving the issue of bias resulting from different sizes &amp;#8211; but has no effect on efficiency. A party that finds more and more of its voters clustering would receive an MP with a slightly higher voting weight &amp;#8211; but if better distributed might be winning several seats rather than fractionally more of 1. This party will on average have larger constituencies &amp;#8211; and argue that this is unfair to voters. Sure, voters have an equal share of our increased power &amp;#8211; but do they have an equal share of our time? We&#39;re disadvantaged compared to the lower-weighted MPs opposite because they still have more MPs per vote than we do.  This robs us of the expertise and knowledge that a few more real people (not made-up voting weights) would give us. All MPs need the same weight and we should move constituencies around to deal with this.&quot;", "tags": "", "url": "index.html#11.9531.ss1li.cf8dx.rsrbo.yam8j"},
     
     {"title": "Would this make people happy?", "text": "b&#39;If such complaints have merit would depend entirely on how wide the difference in weights was allowed to be &amp;#8211; but the complaint is inevitable. There is no way of dealing with a political allocation that will not have the loser advancing a very principled (but convenient) argument why it should not be so.&#39;", "tags": "", "url": "index.html#11.9700.uuqpq.g34uu.1oqsx.sycbg"},
     
     {"title": "Would this make people happy?", "text": "b&#39;Achieving Equality&#39;", "tags": "", "url": "index.html#11.647.htdtz.bw8_o._8-eb.hqva9"},
     
     {"title": "Would this make people happy?", "text": "b&#39;tag:equality&#39;", "tags": "", "url": "index.html#11.5901.3vgsa.ex95d.0llw7.2jmj7"},
     
     {"title": "Would this make people happy?", "text": "b&#39;Using weighted votes in this way would give the smaller parties (and all those who vote for them and do not receive the representation they deserve) no less cause for complaint. Equal shares is not political equality, votes for different parties will be differently powerful depending where you cast them.  There are some clever things you can do with weighted votes to achieve greater political equality &amp;#8211; but there are also well established electoral systems (several of which already used in the UK in devolved bodies) that would represent substantial improvements in political equality that would mostly negate the problems of boundaries. &#39;", "tags": "", "url": "index.html#11.9566.ns1yn.t6mtn.j7hrh.onhxe"},
     
     {"title": "Would this make people happy?", "text": "b&quot;Boundary reform is ultimately a fight among the two largest parties about which is treating the other more unfairly &amp;#8211; while collectively they hold 86% of the seats with 67% percent of the vote. Arguments from the Conservatives (who hold 51% of the seats on 37% of the vote) that they&#39;re being treated unfairly are a little hollow. Arguments for political equality require arguments for systems that deliver proportional outcomes &amp;#8211; anything less cannot deliver this goal.&quot;", "tags": "", "url": "index.html#11.9351.hbkm1.w5ihp.z9ygz.k9cdd"},
     
     {"title": "Would this make people happy?", "text": "b&#39;Header Image: Gerrymander&#39;", "tags": "", "url": "index.html#11.5606.gvr-v.ye3kc.pgtv8.lz6cs"}
     
     
]};