


var tipuesearch = {"pages": [
     
     
     {"title": "Intro", "text": "&amp;#65279;", "tags": "", "url": "index.html#1.4257.2jmj7.2jmj7.2jmj7.2jmj7"},
     
     
     
     {"title": "Summary", "text": "The current UK law on political misinformation is awkward, restricted to personal character and difficult for the public to access. Regulation of political advertising is possible, but possible regulators see it as a reputational risk to their core role. Like commercial advertising, political adverts contain fact and opinion. Statements of facts can be evaluated in both kinds of advertising. This might have the effect of moving claims into more ambiguous statements. This is still desirable because ambiguity is a signal voters can interpret. There are examples of systems of regulation abroad: South Australia has a legal approach managed by the Electoral CommissionAotearoa New Zealand has successful private regulation run by their advertising standards authority. The UK political scene is combative, with more attacks on the legitimacy of institutions. Any regulation needs to exist on firm grounds.Progress is halted by the impossibility of self-regulation when any one party can derail the process. The goal should instead be a legal backstop similar to what enables commercial advertising regulation. Public funds for designated referendum campaigns should be conditional on following any established system. ", "tags": "", "url": "index.html#2.4777.yikqu.v84ak.ax2wq.-b88p"},
     
     
     
     {"title": "Introduction", "text": "In the 1890s when Parliament was debating if there should be legal remedies for lies told during an election, a fiction hung over the discussion that only victims were in the room. ", "tags": "", "url": "index.html#3.3056.1tbha.wsjum.x9x8l.o6qe_"},
     
     {"title": "Introduction", "text": "When complaining about fake voting records, accusations of atheism, or being &quot;a pirate who had sunk English ships and marooned their crews&quot;, MPs spoke against unseen opponents whose tactics obviously failed, rather than people sitting opposite them in the chamber. It would be convenient that under-handed tactics happen to be ineffective, but it seems more likely (and more serious) that not only do people lie to try to win elections, but sometimes this works. ", "tags": "", "url": "index.html#3.3791.saujk.v_h4a.v8nmj.7g1fo"},
     
     {"title": "Introduction", "text": "The paradox of political reform is that a bad practice is most worth regulating if it helps people win unfairly, while removing a bad practice requires the buy-in of those same winners. These winners have good reason to develop arguments that explain the bad practice is actually good, or at least that regulation would be worse.", "tags": "", "url": "index.html#3.2425.r6cqb.c9cbq.ejmqt.bzlqz"},
     
     {"title": "Introduction", "text": "The case for regulating lies in elections is simple: decisions made on the basis of lies are worse than decisions made on reality. The case against has two major strands. One is concerned with the practicalities. Where is the line between exaggeration and dishonesty? Who is making these decisions? How fast can they make them? What difference will it really make?", "tags": "", "url": "index.html#3.3703.d3djb.c9ikc.egik2.jbnju"},
     
     {"title": "Introduction", "text": "The other strand is philosophical. The question of who could regulate speech in elections is not just difficult, but such a significant intervention it in itself damages democracy. Who can really be trusted to decide what can and can&#39;t be said in elections? If you have someone deciding what you cannot say in elections, is that not as bad as someone saying anything they want? On one side of the argument, political speech is too important to have less regulation than shampoo commercials. On the other, political speech is too important to trust regulators with at all. ", "tags": "", "url": "index.html#3.3083.yak7b.jyuzu.tq9rj.eiopb"},
     
     {"title": "Introduction", "text": "What I want to argue is that the practical objections have answers. It is possible to raise the standards for truth in elections and there are several working systems internationally we can learn from. While not dismissing the philosophical objections, they have the downside that they would be equally valid against systems of regulation that we currently accept. In some cases the exact same arguments were made against reducing dishonesty in commercial advertising. ", "tags": "", "url": "index.html#3.2147.eltwb.igio-.plmzi.mfsgd"},
     
     {"title": "Introduction", "text": "For advocates of reform, waiting for parties to collectively agree to self-regulation has made no progress in the last twenty years, and is not a viable route forward. This idea that self-regulation could emerge is in part based on a rosy understanding of why industries self-regulate through the Advertising Standards Authority (ASA) in the first place: it is an alternative to legal sanctions that would otherwise exist.", "tags": "", "url": "index.html#3.1174.gw3uf.uvltt.zvog_.iynjx"},
     
     {"title": "Introduction", "text": "Legislative change to create these same conditions for political parties is still a high bar, but significantly easier than all-party agreement. ", "tags": "", "url": "index.html#3.8719.mhviw.mcj-y.iocv4.rfmpg"},
     
     {"title": "Introduction", "text": "Specifically, this suggests two goals:", "tags": "", "url": "index.html#3.3518.vp_ge.o7lq7.px6-u.n8rzl"},
     
     {"title": "Introduction", "text": "A legal backstop to enable the ASA (or similar body) to emulate its counterpart in New Zealand and end its exemption for political advertising, with liberal interpretation of political claims to protect the importance of free expression in elections.Enforce this same rule for referendum campaigners by making access to public funds conditional on following the same system as that followed in elections.", "tags": "", "url": "index.html#3.4841.wjezf.gkyzk.pga_1.1oxuk"},
     
     {"title": "Introduction", "text": "The resulting system would have a limited scope, but has benefits in bringing political advertising into step with the public&#39;s expectations and understanding of commercial advertising. ", "tags": "", "url": "index.html#3.505.jqmz8.ugtw3.plmzi.wd2ll"},
     
     {"title": "Introduction", "text": "To explain how we can accomplish this requires knowing more about the past. This essay is the story of how people have wrestled with this problem: how different laws and systems of regulation have worked - and what other options are available.", "tags": "", "url": "index.html#3.7085.gkusk.qatbi.eymau.eolgq"},
     
     
     
     {"title": "Once a Century", "text": "The 2010 election upset a lot of ideas about how elections in the UK should work. The campaigns featured the first public debate between party leaders and the electorate delivered a result that was thought to be impossible: a stable coalition government. ", "tags": "", "url": "index.html#once-a-century"},
     
     {"title": "Once a Century", "text": "Less well known is another political first: an elected MP was removed from the House of Commons for lying to the electorate.", "tags": "", "url": "index.html#4.9982.ratv-.jhvvi.6br_-.jf4zb"},
     
     {"title": "Once a Century", "text": "Six months after polling day Phil Woolas - a former Labour Minister and MP of thirteen years - left the House of Commons because a court declared his election void. The reason? The court had found he lied about the personal character of his opponent and as such had committed an illegal practice. This was surprising because (while this law is occasionally used against councillors) only one other MP has ever run into trouble and that was in 1911. Even that comparison is not strictly fair because in the 1911 case lies featured alongside charges of voter intimidation and bribery. This makes Woolas the first MP to lose his seat solely for misleading statements.^*", "tags": "", "url": "index.html#4.250.zo1ph.qrqe0.mt4fk.w8k5m"},
     
     {"title": "Once a Century", "text": "But was Woolas the first MP to tell a lie and win an election in a century? If (as we might suspect) this is not the case, why does this not happen all the time? Commenting on the case, MP John Mann said:", "tags": "", "url": "index.html#4.4533.7occc.fgkrc.ciw75.dpdiv"},
     
     {"title": "Once a Century", "text": "From looking at the publicity and propaganda that there have been, I think it is factually accurate to say that there have been worse in recent elections from all three main parties than in the case of Mr Woolas, and the candidates in question have won.^*", "tags": "", "url": "index.html#4.2417.aic4j.t1rgg.lctpr.dessz"},
     
     {"title": "Once a Century", "text": "The uniqueness of the Woolas case is strange. What was the difference between him and people who got away with it? What did he do wrong?", "tags": "", "url": "index.html#4.1405.ldq37.ln02i.zx7-f.12jo4"},
     
     {"title": "A man&#39;s honour", "text": "Woolas&#39; specific problem was section 106 of the Representation of the People Act 1983. This reads:", "tags": "", "url": "index.html#a-mans-honour"},
     
     {"title": "A man&#39;s honour", "text": "(106) A person who, or any director of any body or association corporate which &amp;#8212;(a) before or during an election,(b) for the purpose of affecting the return of any candidate at the election,makes or publishes any false statement of fact in relation to the candidate&#39;s personal character or conduct shall be guilty of an illegal practice, unless he can show that he had reasonable grounds for believing, and did believe, that statement to be true.^*", "tags": "", "url": "index.html#4.7404.feebt.irnku.ckuij.wfjgs"},
     
     {"title": "A man&#39;s honour", "text": "As an illegal practice this has the potential to void the results of elections and the Act also has a provision allowing for injunctions that can restrain future publication of these false statements before the election has finished. ", "tags": "", "url": "index.html#4.7169.tkncl.bvapd.b2vuo.p92ya"},
     
     {"title": "A man&#39;s honour", "text": "There is a Victorian feel to this talk of &quot;personal character&quot;. The clause descends from the much older Corrupt and Illegal Practices Act 1895. The debate surrounding the original version of this section makes for interesting reading. While in Woolas&#39; case the idea of injury to the voter would become the more pressing issue, the original intention was focused more on the injury to the candidate and their standing. The Lib-Lab MP Henry Broadhurst made a stirring address to the House making clear the point of the honour at stake:", "tags": "", "url": "index.html#4.2299.p20bl.tno--.d2tpn.otdcw"},
     
     {"title": "A man&#39;s honour", "text": "If they were what they all aspired to be, honourable English Gentlemen, they should all denounce, in the strongest possible terms, such proceedings as the Bill aimed at.^*", "tags": "", "url": "index.html#4.4219.v5ubt.yltba.mvyy6.aeswe"},
     
     {"title": "A man&#39;s honour", "text": "During the debate MPs sounded off with a liturgy of common libels. These commonly included being accused of being an Atheist or of underpaying labourers. But at the more extreme end one said that they had been accused of being &quot;&quot;a pirate who had sunk English ships and marooned their crews&quot;&quot;.^* Herbert Leon complained that he:", "tags": "", "url": "index.html#4.5842.ncu_n.c29wa.5ywja.zqt7s"},
     
     {"title": "A man&#39;s honour", "text": "had been the victim of a slander at the last General Election, when he was accused by a Conservative paper of advocating horse-racing and debauchery on Sundays, and murders committed.^*", "tags": "", "url": "index.html#4.3848.ufgej.qycin.fnztl.6kms2"},
     
     {"title": "A man&#39;s honour", "text": "It being open to debate if gambling or murder was the more serious accusation.", "tags": "", "url": "index.html#4.7989.mremr.1-ccx.plirw.i_yco"},
     
     {"title": "A man&#39;s honour", "text": "Donald Macfarlane claimed that an untrue report about the crew of his yacht poaching salmon (on a Sunday!) was attuned to local sensitivities to have the biggest impact. If his opponents had said that &quot;&quot;he had sent the men of his yacht to carry off half-a-dozen of the lairds&#39; wives &amp;#8230; it would not have had nearly the same effect&quot;&quot;.^*", "tags": "", "url": "index.html#4.9020.byeoe.4plpy.m4b3j.ekzc4"},
     
     {"title": "A man&#39;s honour", "text": "These issues seem fairly unambiguously about personal character but the big complication with the law then (as now) is working out the far murkier area of when and how political activity is distinct from character. There was general agreement that there was indeed a difference, and that tackling political falsehoods might be a problem. Robert Reid argued that:", "tags": "", "url": "index.html#4.9256.y7evd.loffg.ywtjb.5ebsd"},
     
     {"title": "A man&#39;s honour", "text": "Anything that savoured of a political character should not be made a ground for interference with an election. As long as human nature remained what it was, I believe that in elections there would be exaggerations and unfounded statements as to the opinions of people with whom other people did not agree which it would be impossible to avoid, and all they could do was to hope that the electors would have the good sense to take the necessary discount off such statements.^*", "tags": "", "url": "index.html#4.7052.kwtwq.xciqj.yg2z3.8tguh"},
     
     {"title": "A man&#39;s honour", "text": "MPs complained of &quot;black lists&quot; being published. These were fake reports of the votes they had taken in Parliament (the Victorian ancestors of Twitter infographics). But what is the difference between a made-up record of underpaying workers in non-political life and a made-up voting record of supporting &quot;&quot;flogging in the Army and perpetual pensions&quot;&quot;?^* Both are a track record that speak to personal character but the subject of votes in Parliament can&#39;t be treated as anything other than political. Henry Labouchere made this exact point at the time:", "tags": "", "url": "index.html#4.5981.mcxa4.zemuh.ky-n7.l44qa"},
     
     {"title": "A man&#39;s honour", "text": "It was very difficult to draw the line of demarcation between what was political and what was not, in speeches. Hon. Gentlemen opposite, for example, very often accused their opponents of wishing to disintegrate the Empire. Now he thought it was contrary to proper political conduct to &quot;disintegrate the Empire.&quot; That was a personal accusation, and he could well conceive some magistrates holding that a person came under this Act by making such an accusation. On the other hand, were the Tory Party determined to make the Irish slaves to the Saxon for ever and ever? That, again, might be regarded as a personal accusation.^*", "tags": "", "url": "index.html#4.7056.msg0c.gctfk.bshtz.uop-4"},
     
     {"title": "A man&#39;s honour", "text": "Political conduct can and does speak to personal character. This fundamental wrinkle in the law was never adequately resolved, as the Woolas case demonstrates.", "tags": "", "url": "index.html#4.5154.lygq7.uceu_.ls0c5.06ovw"},
     
     {"title": "Broken promises", "text": "Election offences are treated differently than other criminal offences. Instead of being investigated by the police and prosecuted by the crown prosecution service, individuals have to challenge the result directly through an election petition. As the original intention was for one candidate to have recourse against another this makes sense, but it makes prosecutions &quot;&quot;in the public good&quot;&quot; more complicated. In the Woolas case his Liberal Democrat opponent, Elwyn Watkins, submitted a petition that triggered an election court.", "tags": "", "url": "index.html#broken-promises"},
     
     {"title": "Broken promises", "text": "Woolas was initially found guilty of having made three unfactual statements in publications about Watkins. The full documents can be read at the bottom of the decision but to summarise Woolas these statements were:", "tags": "", "url": "index.html#4.5682.yhv6o.s_kq8.rirvq.rgbdx"},
     
     {"title": "Broken promises", "text": "Claiming that Watkins was seeking to woo the vote of Muslims who advocated violence against Woolas;Claiming that Watkins refused to condemn Muslims who advocated violence against Woolas;Claiming that Watkins had broken a promise to live in the constituency.^*", "tags": "", "url": "index.html#4.9757.vcr2j.vmpyk.cv4y1.yfsch"},
     
     {"title": "Broken promises", "text": "The statements were also intermingled with attacks on Watkins&#39; political stances. In the Election Court&#39;s judgement the personal attacks could be separated from the politics:", "tags": "", "url": "index.html#4.4321.6c6hh.c-si8.kph4c.qlold"},
     
     {"title": "Broken promises", "text": "To say that the Petitioner Watkins was aware that an extremist group had threatened violence to his political opponent and had refused to condemn such threats is, in our judgment, an attack on the personal character or conduct of the Petitioner. It is an attack on his &quot;honour&quot; or &quot;purity&quot; because, like the statement in the Examiner, it suggests that he is willing to condone threats of violence in pursuit of personal advantage. That is also an attack on his political conduct (because the advantage sought was an electoral victory) but that does not put the attack outside the protection afforded by section 106 if his personal character is also attacked).^*", "tags": "", "url": "index.html#4.7360.fz6yz.rockq.3ecyd.cmkkr"},
     
     {"title": "Broken promises", "text": "They also argued that attacks on a political campaign could be personal attacks at the same time:", "tags": "", "url": "index.html#4.9094.vasdy.m4nmc.zavu7.x23i9"},
     
     {"title": "Broken promises", "text": "His promise to live in the constituency was &quot;part of the campaign&quot;, made to establish his commitment to the constituency and to establish his credibility with the electorate. However, the statement also relates directly to his personal character or conduct. A person who breaks his promise is untrustworthy. To say that someone is not worthy of trust is to attack his &quot;honour, veracity and purity&quot;. It was described by the Respondent in evidence as a politician&#39;s promise. Whilst we accept that promises made by politicians may not be honoured because of changes in political circumstances, this particular promise cannot fall into any such category. The performance of the Petitioner&#39;s promise was within his control and so a failure to honour it reflected on his personal trustworthiness.^*", "tags": "", "url": "index.html#4.2223.t3fn2.capvd.osxkn.rhye3"},
     
     {"title": "Broken promises", "text": "On judicial review the Divisional Court accepted the first argument but not the second. They upheld that claiming Watkins had condoned violence was an attack on his character but that claiming he broke his promise to live in the constituency was not a personal attack. Or at least not one that was covered by the law:", "tags": "", "url": "index.html#4.7229.mohfs.jumfc.5huyp.ldh_e"},
     
     {"title": "Broken promises", "text": "A statement that the candidate has reneged on his promise to live there does, we accept, cast an imputation on the candidate&#39;s trustworthiness, as the Election Court held, but it is in respect of his trustworthiness in relation to a political position. To hold that such a statement fell within the prohibition would have a significant inhibiting effect on ordinary political debate, as candidates, particular those who have been MPs, are sometimes criticised for going back on promises on a political issue.^*", "tags": "", "url": "index.html#4.7278.3iuvm.kf-hb.ui_n-.iz_pm"},
     
     {"title": "Broken promises", "text": "This reduces what is otherwise a fairly large hole between political conduct and personal character. While a false claim of &quot;promise breaker&quot; does damage character, if the promise was political s.106 is not applicable. The position of the Divisional Court was that &quot;&quot;a court has to make that distinction and decide whether the statement is one as to the personal character or conduct or a statement as to the political position or character of the candidate. It cannot be both&quot;&quot;.^* While the review did very little for Woolas it tightened future grounds for complaint under s.106 considerably.", "tags": "", "url": "index.html#4.8795.alrrf.bryee.kgest.b83xp"},
     
     {"title": "Broken promises", "text": "The review judgement struggles when it tries to put a principle to this distinction:", "tags": "", "url": "index.html#4.2907.12ca5.rc4vw.hkyac.cyciz"},
     
     {"title": "Broken promises", "text": "It was as self evident in 1895 as it is today, given the practical experience of politics in a democracy, that unfounded allegations will be made about the political position of candidates in an election. The statutory language makes it clear that Parliament plainly did not intend the 1895 Act to apply to such statements; it trusted the good sense of the electorate to discount them. However statements as to the personal character of a candidate were seen to be quite different. The good sense of the electorate would be unable to discern whether such statements which might be highly damaging were untrue; a remedy under the ordinary law in the middle of an election would be difficult to obtain.^*", "tags": "", "url": "index.html#4.4819.fdokx.m9bkg.hgitv.90l9v"},
     
     {"title": "Broken promises", "text": "While an accurate reflection of parliamentary intentions (confused as they were) this position makes little logical sense. The court argued that voters need less protection for political untruths because their &quot;&quot;good sense&quot;&quot; is adequate to detect them. They are &quot;&quot;unable to discern&quot;&quot; if damaging claims of a personal nature are true, but can be &quot;&quot;trusted &amp;#8230; to discount&quot;&quot; political ones. But both personal and political claims may be insubstantial or backed with evidence. There is little to distinguish between them in terms of how easily voters can detect falsehoods. ", "tags": "", "url": "index.html#4.3333.7oa9b.6mg5s.ekvrl.eckkf"},
     
     {"title": "Broken promises", "text": "One reason for courts to favour as narrow a view of &quot;personal character&quot; as possible are the practicalities. A broad construction gets into muddy water quickly. As the court put it, it is &quot;&quot;difficult to see how the ordinary cut and thrust of political debate could properly be carried on if such were the width of the prohibition. In any event it would also be difficult to reconcile such a broad construction with the balance that Article 10 Freedom of Expression mandates be achieved&quot;&quot;.^* The courts do not want to push here unless invited to by Parliament.", "tags": "", "url": "index.html#4.2953.5xinz.rkbgg.vdnux.h3loo"},
     
     {"title": "Broken promises", "text": "The law was tested again in 2015 with a petition against Liberal Democrat MP Alistair Carmichael. Although this petition failed (what was described as a &quot;&quot;blatant but simple lie&quot;&quot;^1 was considered primarily political rather than personal), it did widen the previously accepted scope of the law by confirming that &quot;self-talking&quot; (statements about your own personal character that were untrue) could engage the law.^2 This attempt also showed the awkwardness of the petition system, in this case four of Carmichael&#39;s constituents had to crowdsource legal fees before advancing the petition.", "tags": "", "url": "index.html#4.8577.n219v.zqxoj.9olai.h9cj_"},
     
     {"title": "Broken promises", "text": "In addition to the action taken against Alastair Carmicheal, there have been a number of lower-level complaints. In 2015, Lib Dem Greg Mulholland successfully got his opponent to print 15,000 apology leaflets retracting a claim that Mulholland had voted for academy school legislation.^1 In 2019, Jo Swinson won a court order forcing her SNP opponent to withdraw a leaflet accusing her of hypocrisy.^4 In Cambridge, the Conservative candidate Chamali Fernando threatened her opponent with libel action over what he claimed she said at a hustings (with the additional threat of a s.106 action).^2 Nigel Farage even tried to argue that a journalist&#39;s comment on the BBC&#39;s comedy panel show Have I Got News For You was an untrue statement that attacked his character.^3", "tags": "", "url": "index.html#4.5850.iqjct.ydxdp.hwf6q.fucrz"},
     
     {"title": "Broken promises", "text": "Election courts are not particularly good ways of redressing these grievances. They are expensive to pursue, focused on a narrow area of truth, and the outcome is severe. The Carmichael petition may have failed to unseat an MP, but it did broaden the understood scope of the law and uphold the procedure&#39;s existence as more than just a curiosity.  The more elections are accompanied by petitions, the more likely they are to become a regular feature - and prospects for either making election courts less objectionable or less required should appear.", "tags": "", "url": "index.html#4.4164.cfwbn.razjd.facjq.rxnze"},
     
     {"title": "Broken promises", "text": "In their interim report on reforming electoral law, the Law Commission have recommended legislation allowing courts to be able to make protective cost orders so that individuals who bring petitions &quot;&quot;should be heard in the public interest and should not risk financial ruin when doing so&quot;&quot;.^1 However, while the consultation addressed the law concerning false statements, no questions were posed on its wider reform as this would be a more substantial change than a legal tidy-up.^2", "tags": "", "url": "index.html#4.6094.eqpcj.t7rzj.gnuyf.t1hnd"},
     
     {"title": "Broken promises", "text": "The law currently sits uncomfortably. It covers a strange sub-division of possible election lies, is burdensome in that it requires individuals to bring the petition, and severe in that it might remove an MP from office without the prospect of appeal.  For more workable examples of laws controlling false statements we have to look further elsewhere.", "tags": "", "url": "index.html#4.7541.nrj--.azros.i68ah.o_8zw"},
     
     
     
     {"title": "International examples", "text": "Laws that go further than the UK are not particularly common. The US generally goes the other way and tightens libel standards for political speech (see New York Times v Sullivan) - and those states that have had restrictions tend to lose them to constitutional challenges. That said, Australasia has several interesting examples of past and current laws that go further than the UK to control false statements of fact.", "tags": "", "url": "index.html#5.4302.sxpay.dofe1.rgw_o.nmxba"},
     
     {"title": "International examples", "text": "The most recent example is the loss of Ohio&#39;s prohibitions on false statements^1 on first amendment grounds in Susan B. Anthony List, et al. v. Ohio Elections Commission.", "tags": "", "url": "index.html#5.9934.xnp0u.ck-7x.bh0kh.smgum"},
     
     {"title": "Australia", "text": "Australia briefly attempted a federal law that was later abandoned, but in South Australia there is an active prohibition on untruthful statements at the state level. The Electoral Act 1985 contains a offence for:", "tags": "", "url": "index.html#australia"},
     
     {"title": "Australia", "text": "113 (2) A person who authorises, causes or permits the publication of an electoral advertisement (an advertiser) is guilty of an offence if the advertisement contains a statement purporting to be a statement of fact that is inaccurate and misleading to a material extent.^0", "tags": "", "url": "index.html#5.9470.u8q0x.u6f9g.gkdno.-i-fs"},
     
     {"title": "Australia", "text": "This offence can carry a fine. For complainants the first port of call is the Electoral Commission (ECSA), who can then request the advert be withdrawn and/or a retraction published (from a legal point of view compliance here can affect any possible fine). In the event this is not followed, the Electoral Commissioner can go to a court who, if satisfied, have the power to order the same.", "tags": "", "url": "index.html#5.8056.monnb.e6ol4.iabm8.vmvgn"},
     
     {"title": "Australia", "text": "After the election the Court of Disputed Returns can declare an election void &quot;&quot;but only if the Court of Disputed Returns is satisfied, on the balance of probabilities, that the result of the election was affected by that advertising&quot;&quot;.^0 In other words, the scale of the victory matters when interpreting if the election had been affected. There is no such provision in the equivalent UK law. A false statement of fact about a candidate&#39;s personal character is an illegal practice, which unlike administrative breaches of electoral law is not subject to a test of whether it &quot;&quot;materially affected the result of the election&quot;&quot;.^1 Technically speaking, if Woolas had won by a landslide as opposed to 103 votes the legal outcome should have been the same.", "tags": "", "url": "index.html#5.9025.n7gqt.pzbvn.iabm8.sd7gh"},
     
     {"title": "Australia", "text": "It is worth noting that the Electoral Commission in South Australia would not to be involved in this, in their 2010 election report saying:", "tags": "", "url": "index.html#5.3871.nsxf1.0hipx.ninbb.x-q0j"},
     
     {"title": "Australia", "text": "There is a real risk that the Electoral Commissioner will appear to have become politicised if she is involved in a significant decision favouring one party over another in the days immediately prior to the election.^1", "tags": "", "url": "index.html#5.9276.b3lbs.ch37w.-brfn.a3ds1"},
     
     {"title": "Australia", "text": "In addition to integrity concerns it generates a large amount of work for the Commission. On one day &quot;&quot;a ream of paper some 22&amp;#8211;25 cm high was delivered to the commissioner in the form of supporting documentation&quot;&quot;^1 and in the final weeks of the 2010 election complaints were being made &quot;&quot;almost daily. As such, their consideration occupied a significant amount of ECSA staff time&quot;&quot;.^2", "tags": "", "url": "index.html#5.3875.ys-qq.ydxdp.iokzq.f6dam"},
     
     {"title": "Australia", "text": "The Commission argues that very little comes out of this process as &quot;&quot;complaints tend to seize upon statements that could never be proven to the requisite level&quot;&quot; including &quot;&quot;statements of intention or opinion, or general statements of past success or failure in broad terms&quot;&quot;.^1", "tags": "", "url": "index.html#5.3200.73q5b.2eeoi.tzhqk.asue1"},
     
     {"title": "Australia", "text": "In 2014 they suggested removing the provision altogether:", "tags": "", "url": "index.html#5.6017.s-pir.rbzrf.dubc8.gsib5"},
     
     {"title": "Australia", "text": "Consider removing this provision as no other State in Australia has truth in political advertising. The Australian Parliament has determined that the Commonwealth Electoral Act 1918 should not regulate the content of political advertising. ^*", "tags": "", "url": "index.html#5.2161.nzan2.ro6ma.yfyqk.r9e0l"},
     
     {"title": "Australia", "text": "But that isn&#39;t to say complaints are never valid. In 1995 the Labor Party was found guilty of an offence for the following advert:", "tags": "", "url": "index.html#5.1214.c2fin.lvwjg.2qq_d.rjx1d"},
     
     {"title": "Australia", "text": "&quot;Could this be South Australia? If the Brown Liberals win the election South Australia will change in ways you and your kids never imagined.The fact is the Brown Liberals have stated that any school with less than three hundred students will be subject to closure. We have three hundred and sixty three schools with less than three hundred students. That&#39;s a big change.Don&#39;t let it happen. Don&#39;t let Mr Brown bring South Australia down.&quot;", "tags": "", "url": "index.html#5.7065.rqz2m.7tcti.3n_1a.bnou-"},
     
     {"title": "Australia", "text": "This was held to be a misleading interpretation of the Liberal spokesperson&#39;s statement:", "tags": "", "url": "index.html#5.7610.p19cs.wn8jz.u7kwz.2zdm0"},
     
     {"title": "Australia", "text": "&quot;Well. I mean &amp;#8230; we&#39;ve indicated here in South Australia that we&#39;re certainly not going to be closing two hundred schools in South Australia.If there are a small number of schools that have got very small numbers of students, well then under both governments I guess there will continue to be a small program of school closures, but we&#39;re not going to be looking at schools with three hundred students in them.&quot;", "tags": "", "url": "index.html#5.6398.ugcnd.rns04.a1rae.xtjrg"},
     
     {"title": "Australia", "text": "The defence argued that such speech was permissible under conditional freedom of communication, but the case gave the South Australian Supreme Court a chance to defend the interference with free speech the law required:", "tags": "", "url": "index.html#5.49.-cjeb.pekop.dn9yg.r7oy1"},
     
     {"title": "Australia", "text": "That section recognizes that a truly informed elector is one who has not been subjected to deceit or misrepresentations such that the elector might vote contrary to the manner in which that elector would have voted but for the deceit or misrepresentations. Whilst s.113 does interfere with the right of the freedom of speech, it does so for the purpose of protecting the electors from being mislead and deceived. The Act, I think, attempts to balance the concept of freedom of speech and the right to be properly informed.", "tags": "", "url": "index.html#5.6965.83fle.d0pbq.6g5z5.zmr2c"},
     
     {"title": "Australia", "text": "That very few cases get this far reflects that balance at work. Almost all complaints fail or the scope of the action is restricted. In 1998, the court agreed an advertisement had been misleading but judged the impact not to have sufficient to warrant invalidating the election.^1 In 2010, the statement &quot;&quot;soft on crime&quot;&quot; was found to be opinion rather than fact and so could not be judged as misleading at all.^2", "tags": "", "url": "index.html#5.721.1qpyf.kxuvn.djtlg.wiuu6"},
     
     {"title": "Australia", "text": "The UCL&#39;s Constitution Unit report found general political consensus in favour of maintaining the practice:", "tags": "", "url": "index.html#5.3698.m5wgu.vljmf.dffs-.ync99"},
     
     {"title": "Australia", "text": "In the course of our research, we interviewed both the then Attorney General of South Australia, John Rau, who was responsible for electoral law, and the then Shadow Attorney General, Vickie Chapman, who became Attorney General following the state elections in March 2018. We also interviewed the State Secretary of the Labor Party (Reggie Martin) and State Director of the Liberal Party (Sascha Meldrum), who are responsible for ensuring their parties&#39; compliance with electoral law. All of them supported the principle of section 113. Referring to the ban on inaccurate and misleading statements, John Rau, said &amp;#8216;I don&#39;t see that there&#39;s any principled argument against that&#39; . He added that &amp;#8216;stealing office by the tactical utilization of malicious or false material&#39; is wrong. Vickie Chapman said there was no case for abolishing section 113. Sascha Meldrum described it as a &amp;#8216;good thing&#39; to have a deterrent against misleading advertising, saying &amp;#8216;everyone supports the section 113 system in principle&#39; . The Labor government between 2014 and 2018 chose not to adopt the former Electoral Commissioner&#39;s suggestion of repealing the provision, and the Liberal government elected in 2018 maintains the same view^0", "tags": "", "url": "index.html#5.2336.otvsi.rolns.yitf4.k8lyt"},
     
     {"title": "Australia", "text": "Is the South Australian model worth emulating? It certainly creates a large amount of work, which requires resources.Practically speaking, scaling from elections with dozens of seats to hundreds would multiply the work considerably. However the low rate of actual prosecutions should be seen as a sign of success. If the goal of the law is to reduce the number of false statements, claims being submitted every day of an election and passing what is a fairly expansive view of &amp;#8216;fact&#39; seems like a good outcome. ", "tags": "", "url": "index.html#5.8173.l7isx.1bdrg.ss51f.etel2"},
     
     {"title": "Aotearoa New Zealand", "text": "Aotearoa New Zealand has a similar but more restricted law on the books.  In 2002 Section 199a was added to the Electoral Act 1993. This provision applies from two days before the election and theoretically creates a disincentive to pollute the debate at the last minute when there is no time to respond:", "tags": "", "url": "index.html#aotearoa-new-zealand"},
     
     {"title": "Aotearoa New Zealand", "text": "199(a) Every person is guilty of a corrupt practice who, with the intention of influencing the vote of any elector, at any time on polling day before the close of the poll, or at any time on any of the 2 days immediately preceding polling day, publishes, distributes, broadcasts, or exhibits, or causes to be published, distributed, broadcast, or exhibited, in or in view of any public place a statement of fact that the person knows is false in a material particular.^*", "tags": "", "url": "index.html#5.4170.mckfr.zmlni.axyg1.tz_vw"},
     
     {"title": "Aotearoa New Zealand", "text": "For a sense of the political context it&#39;s worth noting that there was originally a companion to this amendment that created a criminal libel standard throughout the entire campaign, but that was removed after opposition in the media and from parliament. There was also opposition voiced against the two day rule - Warren Kyd of the National Party argued:", "tags": "", "url": "index.html#5.2631.kkjmm.ympvh.sc4yq.vsuxc"},
     
     {"title": "Aotearoa New Zealand", "text": "If a person says his or her party will increase pensions, spend more on education, and reduce tax - a statement that is clearly pretty exaggerated, but does occur at election time - does that mean that he or she could be guilty of a corrupt practice and lose his or her seat? ... If one went to the court, one could presumably upset an election, and a member could lose his or her seat as a result of exaggerating, or singing the bull a bit, when electioneering.", "tags": "", "url": "index.html#5.6788.awgqx.qsezy.t2bvz.ktf6x"},
     
     {"title": "Aotearoa New Zealand", "text": "This provision has never been used. The then-Secretary of Justice told the Select Committee investigating the bill that prosecutors and the courts would be reluctant to get involved in political controversy by pursuing prosecutions.^*", "tags": "", "url": "index.html#5.4130.oxw8p.zgeme.9ax1e.x5qzg"},
     
     {"title": "Aotearoa New Zealand", "text": "A challenge by New Zealand First leader Winston Peters, led to an expansion of coverage (where the court found that material remaining on a website in the last few days may be in scope), but an amendment was made to the law to ensure it only applied to new material.^0", "tags": "", "url": "index.html#5.5758.jhv0e.tyf7p.hnpya.cgtel"},
     
     {"title": "Aotearoa New Zealand", "text": "The principle that the period immediately prior to an election deserves a backstop seems reasonable but from a UK perspective it seems strange that it exists at all. There is a wider cultural aspect to consider and it turns out that both Australia and New Zealand have a very different history of private regulation of electoral advertising. This might explain why the UK is awkwardly dealing with historical legislation while Australia and New Zealand have experimented with the issue in recent decades. The idea that electoral advertising can be regulated is, while definitely not universally accepted, part of the conversation around elections in these countries, but is not in the UK.", "tags": "", "url": "index.html#5.3340.rk9xy.uq1iz.iqyqg.5rvfc"},
     
     
     
     {"title": "Private regulation", "text": "Many countries have codes of practices for advertising and organisations that mediate disputes to keep problems out of the courts and prevent the need for a government enforcement agency. In the UK commercial advertising is regulated by Ofcom for broadcast and the Advertising Standards Authority (ASA) for other forms of advertising.", "tags": "", "url": "index.html#6.6154.81i_c.owfcj.bv9z0.iaub9"},
     
     {"title": "Private regulation", "text": "While some of their counterparts in other countries have a truth checking duty for political advertising, this has never been the case in the UK. The ASA has had greater involvement in political advertising in the past. Up until 1999 political advertisements existed in a halfway house where the ASA protected personal character but did not hold political to the same criteria on accuracy (mirroring the legal distinction). After 1999 the ASA moved away from this, leading to the current situation where no one has the authority to judge the content of election adverts at all.", "tags": "", "url": "index.html#6.8539.twbxc.vqwtt.govkw.sszio"},
     
     {"title": "Private regulation", "text": "The spark that led to the change came in 1996, when the ASA ruled against a Conservative Party advert. The ad was part of the Conservatives&#39; &quot;New Labour, New Danger&quot; campaign and featured Labour leader Tony Blair with a pair of red demonic eyes. It received 167 complaints and the ASA asked for the advert not be used again, finding that:", "tags": "", "url": "index.html#6.2258.7qzvd.2n8qn.njp7f.04-vl"},
     
     {"title": "Private regulation", "text": "Although it did not consider that readers in general would think the advertisement attributed satanic qualities to Tony Blair, the Authority reminded the advertisers that the Codes prohibited the portrayal, without permission, of politicians in an adverse or offensive way. Because it considered that the advertisement depicted Tony Blair as sinister and dishonest, the Authority asked for it not to be used again.^1", "tags": "", "url": "index.html#6.9901.ff2k_.ss3jv.vhmi1.yopmy"},
     
     {"title": "Private regulation", "text": "The full finding is no longer available online, reproduced below:", "tags": "", "url": "index.html#6.3907.1fb7b.jz7yu.n0ual.krqpy"},
     
     {"title": "Private regulation", "text": "The fallout from failures of complaints by other parties after Demon Eyes led to the Committee of Advertising Practice (CAP) wanting to end the halfway house arrangement one way or the other. With no clear agreement among political parties on if the ASA should continue in its current role, they opted in favour of staying out of political disputes as &quot;&quot;we are an unelected body and have no desire to become involved in the democratic process&quot;&quot;.^* It was not their core mission and it was an awkwardness they could avoid. When the code was next revised it introduced a provision to close the issue. The relevant section of the code now reads:", "tags": "", "url": "index.html#6.9566.aszno.4cqeh.3dk1a.nrgwt"},
     
     {"title": "Private regulation", "text": "7.1 Claims in marketing communications, whenever published or distributed, whose principal function is to influence voters in a local, regional, national or international election or referendum are exempt from the Code.^0", "tags": "", "url": "index.html#6.9351.zfmu_.5vyqw.anjrr.hmqiv"},
     
     {"title": "Private regulation", "text": "But the expectation was never that this would be the end of the matter. The CAP suggested that the regulation of party adverts should continue - but not by them. The baton was taken up by the Neill Report who advised that the &quot;&quot;political parties should seek to agree, in association with the advertising industry, a code of best practice for political advertising in the non-broadcast media&quot;&quot;.^1 After investigating the matter the Electoral Commission found the prospects for any self-regulation scheme to be dismal. While the Liberal Democrats were in support of a code, Labour failed to respond to the consultation and the Conservatives&#39; statement put it bluntly:", "tags": "", "url": "index.html#6.5606.oybuz.8whyl.bwyd3.mqbil"},
     
     {"title": "Private regulation", "text": "In the context of the Conservative Party being the largest party of local government in Britain and the Official Opposition in Parliament, it would not be viable for a voluntary code to exist without our participation and cross-party consent. As a result, we respectfully submit to the Commission that any proposals for a voluntary code are not workable.^*", "tags": "", "url": "index.html#6.2998.nfwdd.rolns.4ygrr.ygxho"},
     
     {"title": "Private regulation", "text": "This quote sits alone on the last page of the report before the Commission&#39;s own conclusions - the logic is undeniable. The Commission concluded that &quot;&quot;having considered again the case for a code, it is clear that the difficulties of implementing any such code mean that, to all intents and purposes, it would be impractical&quot;&quot;.^*", "tags": "", "url": "index.html#6.4852.fkyty.so8sw.rdowh.zcrc_"},
     
     {"title": "Private regulation", "text": "We have to be aware of some institutional self-interest in this conclusion. If the ASA was not interested in the responsibility, then the most viable candidate for the role was the Electoral Commission. In fact the ASA (and a few others) suggested as much in their responses:", "tags": "", "url": "index.html#6.3174.rkb0g.y2yr8.k92vt.7baim"},
     
     {"title": "Private regulation", "text": "It is hard to see who other than the Electoral Commission itself would be in a position to adjudicate on breaches of any code for election advertising.^*", "tags": "", "url": "index.html#6.2708.76bb-.zm36j.-tgqf.nv3gn"},
     
     {"title": "Private regulation", "text": "And (for the same reasons as the ASA) the Electoral Commission did not want to get involved:", "tags": "", "url": "index.html#6.9111.z9kkn.yqlcc.gqpf8.kxuj1"},
     
     {"title": "Private regulation", "text": "We do not consider that it would be appropriate for the Commission to be the arbiter for disputes relating to political advertising. This is principally because of the risk that the Commission&#39;s independence might be compromised or be perceived to be compromised by such a role. To have to adjudicate on controversial advertising within the heat of an electoral campaign, probably within a very short timeframe, has inherent dangers which it could not accept given the fundamental importance for the Commission of maintaining strict impartiality in all of its areas of work.^1&amp;#8230; It is not a role that The Electoral Commission would be prepared to assume.^2", "tags": "", "url": "index.html#6.1853.ycws6.3fmkj.6k0d1.yph4b"},
     
     {"title": "Private regulation", "text": "In fact, the Electoral Commission repeated this argument after the AV referendum:", "tags": "", "url": "index.html#6.3709.gvpwp.cwntp.hgahn.2aj1w"},
     
     {"title": "Private regulation", "text": "We do not think that any role in policing the truthfulness of referendum campaign arguments would be appropriate for the Commission. It would be very likely to draw the Commission into political debate, significantly affecting the perception of our independent role, and posing substantial operational and reputational risks. We therefore invite the Government and Parliament to confirm that a role of this nature would be inappropriate for the Commission. ^1", "tags": "", "url": "index.html#6.2755.vn8o0.3fmkj.hxruz.ee-ga"},
     
     {"title": "Private regulation", "text": "While the relevant organisations can see the abstract benefits of someone taking the role, they also believe it would impact negatively on their core functions.", "tags": "", "url": "index.html#6.1146.0yllk.lu48o.l4h97.dmjzq"},
     
     {"title": "Private regulation", "text": "While there are reasonable arguments to be had about the merits of policing the content of political ads, it is a problem that the public as a whole is unaware they have less protection in this area than others. While it is semi-common knowledge among political campaigners that political ads are outside the jurisdiction of the ASA, 2018 polling commissioned by The Coalition for Reform in Political Advertising and Full Fact found that only 14% were aware that political adverts do not follow the same rules as other advertisers. Over double that (35%) believed they did follow the same rules &amp;#8212; with the remainder not knowing.^0", "tags": "", "url": "index.html#6.7045.cat6h.uoubj.lcjhz.vzpuh"},
     
     {"title": "Private regulation", "text": "The same poll asked if it should be a legal requirement, with 84% said that they thought it should be. While both potential regulators and regulatees have significant reservations and objections, there is general support that such a system should exist (with a significant minority believing it already does). Although this polling may change if asked to evaluate more concrete proposals, the concerns of the public about what protections they should have in elections should also be seen as significant. c", "tags": "", "url": "index.html#6.9764.ccxgb.9snfy.ty81v.6f8uc"},
     
     {"title": "The international picture", "text": "In Australia broadcast adverts used to be judged for accuracy by the Federation of Australian Commercial Television Stations (FACTS). This required campaigns &quot;&quot;to provide sheaves of material proving their claims&quot;&quot;.^0 In one example the Liberal Party successfully argued that FACTS should not show a Labor Party advert that talked about the &quot;last chance&quot; to save Telstra (a publicly-owned telecommunication company) from privatisation because &quot;&quot;it was impossible to say whether or not it was in fact the last chance to save Telstra&quot;&quot;.^2 This was a strong standard.", "tags": "", "url": "index.html#the-international-picture"},
     
     {"title": "The international picture", "text": "However FACTS&#39; interventions here turned out to be based on a mistaken interpretation of a Trade Practice Act. They were never supposed to be judging political adverts and everyone involved had put up with this for essentially no reason. As such FACTS stopped judging political ads in 2002.^1", "tags": "", "url": "index.html#6.8915.e4yo_._l13y.59jbe.yirio"},
     
     {"title": "The international picture", "text": "In New Zealand, the Broadcast Standards Authority (BSA) and Advertising Standards Authority (ASA) both have rules about political accuracy. These recognise that judging election adverts is hard and leeway has to be given to avoid undue interference in the political process. The BSA&#39;s Election Code of Broadcasting Practice allows that:", "tags": "", "url": "index.html#6.650.ze1to.hqoe7.xndsx.lgtvt"},
     
     {"title": "The international picture", "text": "In recognition of the special context of general elections, broadcasting standards such as fairness and accuracy will be applied to election programmes in a manner that respects the importance of free political expression and debate.^*", "tags": "", "url": "index.html#6.7216.i2e4h.azdzk.sq5lb.covhe"},
     
     {"title": "The international picture", "text": "The BSA say that they &quot;&quot;get comparatively few complaints about election programmes, and even fewer are upheld&quot;&quot; and volunteered eight complaints during the 2011 election of which none were upheld.^1", "tags": "", "url": "index.html#6.5634.7bqoa.ek_l1.18pxq.bl-sx"},
     
     {"title": "The international picture", "text": "The NZ Advertising Standards Authority (ASA) similarly deals with complaints about political advertising. False statements are covered under Rule 2:", "tags": "", "url": "index.html#6.1532.gngiz.jrgxr.ziqqb.a3prw"},
     
     {"title": "The international picture", "text": "Truthful Presentation - Advertisements should not contain any statement or visual presentation or create an overall impression which directly or by implication, omission, ambiguity or exaggerated claim is misleading or deceptive, is likely to deceive or mislead the consumer, makes false and misleading representation, abuses the trust of the consumer or exploits his/her lack of experience or knowledge. (Obvious hyperbole, identifiable as such, is not considered to be misleading).^*", "tags": "", "url": "index.html#6.8641.nks9b.qkecc.ddwej.zidqk"},
     
     {"title": "The international picture", "text": "With rule 11 of the Code of Ethics giving protection to expression of opinion in advocacy advertising:", "tags": "", "url": "index.html#6.62.zi8pr.jbvas.bv9z0.s-cob"},
     
     {"title": "The international picture", "text": "Expression of opinion in advocacy advertising is an essential and desirable part of the functioning of a democratic society. Therefore such opinions may be robust. However, opinion should be clearly distinguishable from factual information. The identity of an advertiser in matters of public interest or political issue should be clear.^*", "tags": "", "url": "index.html#6.2086.1iofa.i0zuu.mas4a.jqw-2"},
     
     {"title": "The international picture", "text": "Rule 11 is interpreted through advocacy principles to encourage liberal interpretation of the rules for political advertising, reflecting the idea that this an area where caution is needed.^* But how does this work out in practice?", "tags": "", "url": "index.html#6.5102.zsuzd.73wce.dffs-.9uhyz"},
     
     {"title": "The international picture", "text": "In the 2008 election three complaints were upheld. The first was an issue about false claims about rival parties. A leaflet for the ACT party claiming to be the only party &quot;&quot;totally opposed to an&quot;&quot; Emissions Trading Scheme was delivered to a candidate for the Family Party, who also claimed that policy. ACT&#39;s response was to argue that the Family Party would not gain any seats and that the &quot;&quot;ACT Party is the only party that voted against the passing of the bill in parliament and will be the only party elected to parliament after the election that will oppose it.&quot;&quot; The complaint was upheld (with a minority agreeing with ACT that in terms of the practicality of NZ elections they were the &quot;only&quot; party).^1 This parallels nicely with the 2015 UK election where the Greens and UKIP both insisted they were the only party to oppose HS2 - such claims would run into problems in New Zealand.^2", "tags": "", "url": "index.html#6.2004.gaizx.3qium.1dcyh.rkr1f"},
     
     {"title": "The international picture", "text": "The second upheld complaint was a technical issue concerning the accuracy of a Labour advert accusing Prime Minister John Key of planning to cut KiwiSaver (a savings scheme) in half. The ASA found that he was only halving minimum contributions (and that employee and employer could &quot;&quot;elect to contribute more&quot;&quot;) so the advertisement was misleading as to actual National Party policy. The complainant argued in their appeal that the employer tax exemption would be capped at the new minimum,so as a practical reality continued higher employer contributions seemed unlikely. But &quot;likely result of policy&quot; was not considered to be the same thing as &quot;policy&quot;.^*", "tags": "", "url": "index.html#6.6699.4rtcc.vs5l0.p0rvc.env1t"},
     
     {"title": "The international picture", "text": "The third upheld complaint was an argument about whether saying &#39;&quot;Safe&quot; New Zealand is now almost three times more violent than the US!&#39; was an accurate statement. While neither complainant nor advertiser provided any statistical evidence to either prove or reject the claim, the ASA decided that the burden to prove the claim rested with the advertiser and upheld the complaint.^*", "tags": "", "url": "index.html#6.4953.wfqpo.ob6fp._lrm_.bicuy"},
     
     {"title": "The international picture", "text": "From a rejected complaint we can see that campaigners have a ready understanding of the phrase &quot;technically correct&quot;. This complaint involved a letter that contrasted Winston Peters (leader of the New Zealand First Party) with the Conservative Party, and the complaint argued that Peters stance on smacking was being misrepresented. The letter pushed opposition to an &quot;&quot;anti-smacking Law&quot;&quot; as a point of difference between the two parties as it was &quot;&quot;one of Winston&#39;s own MPs that first proposed an anti-smacking law and a majority of Winston&#39;s party voted for Sue Bradford&#39;s anti-smacking legislation&quot;&quot;.Winston Peters actually voted against the law - but the substance of fact is technically correct and the ASA rejected that aspect of the complaint.^*", "tags": "", "url": "index.html#6.4420.uqvhf.squ1w._lrm_.en-pb"},
     
     {"title": "The international picture", "text": "Looking at the UK&#39;s 2011 AV referendum, Renwick and Lamb found that &quot;&quot;politicians and campaigners on both sides became adept at producing statements that were strictly speaking correct, nevertheless likely to mislead&quot;&quot;.^1 In all elections there are plenty of electoral claims that are deliberately misleading but might escape a factual monitor unscathed. ", "tags": "", "url": "index.html#6.9271._ursu.p4l4w.yj9wi.ic7ug"},
     
     {"title": "The international picture", "text": "In coverage of New Zealand&#39;s referendums there is an example of where the ASA&#39;s liberal advocacy rules win out over strict technical correctness. In the 2011 referendum on whether to retain the mixed member proportional representation (MMP) voting system, a complaint about the anti-MMP campaign&#39;s statement that &quot;&quot;Minor parties decide who is the PM&quot;&quot; was found to be acceptable (it being likely but not necessarily true) &quot;&quot;taking into account the provision for robust advocacy advertising&quot;&quot;.^*", "tags": "", "url": "index.html#6.9799.ccpwj.r8pqa.1tmj7.5iequ"},
     
     {"title": "The international picture", "text": "On the same complaint the Electoral Commission interestingly tried to intervene (under the aegis of the education role they&#39;d been given) to ban the ad on the grounds it was moving the debate on to issues unrelated to the campaign (number of MPs in Parliament) - this was understandably resisted by Vote for Change (anti-MMP) as the Electoral Commission had no real standing to intervene.", "tags": "", "url": "index.html#6.1282.srm3p.vblsn.duoqp.jenek"},
     
     {"title": "The international picture", "text": "The existence of such a system attracts does attract petty complaints, during the 2016 flag referendum the ASA received a complaint that &#39;the image of the Union Jack on the existing flag was &quot;graphically altered to be less attractive&quot; and was smaller than the proposed flag&#39;^1 and another that an ad &quot;&quot;went against the democratic process by using celebrities to advocate for a change&quot;&quot;.^2", "tags": "", "url": "index.html#6.7712.oicgz.gd6ry.qrysq.qyvyu"},
     
     {"title": "The international picture", "text": "But trivial complaints are the price for the ability to intervene on valid ones. In a local referendum about fluoridation of the drinking water a sign that stated &quot;&quot;Why drink toxic waste when you can brush your teeth? Fluoride OUT&quot;&quot; was ruled as unacceptable as:", "tags": "", "url": "index.html#6.8566.tq4mo.dmte7.fs46c.e-6tk"},
     
     {"title": "The international picture", "text": "It implied fluoridated water as toxic which went beyond the provision of robust opinion allowed for under the rules of advocacy advertising. The Complaints Board said the advertisement presented an opinion as a statement of fact in manner that was likely to exploit consumers&#39; lack of knowledge and had unjustifiably played on fear.^1", "tags": "", "url": "index.html#6.6021.3gknk.wyt6u.tpdos.isrpr"},
     
     {"title": "The international picture", "text": "From the New Zealand experience of an ASA that intervenes in political advertising we can see that the task is not inherently impossible, but neither does it create a perfect environment of political truth. Sufficiently crafty campaigns have plenty of room for sleights of hand that are legally permissible. But it is not pointless either. Claims can and do run into trouble, and are barred from further display.", "tags": "", "url": "index.html#6.600.vlr9v.0gki-.7qkph.icc-7"},
     
     {"title": "New technology changing the discussion", "text": "Changing technology changes how people experience and campaign in elections and surfaces campaigning issues that are accepted as common practice. For instance, greater visibility of adverts through social media led to the long-running issue of &#39;Lib Dem bar charts&#39; becoming something worth mainstream discussion, and of asking the party leader to comment on.^0^1", "tags": "", "url": "index.html#new-technology-changing-the-discussion"},
     
     {"title": "New technology changing the discussion", "text": "The up-ending of the advertising (and journalism) industries by large tech companies like Google and Facebook have led to old issues being restated in new ways. What is established practice becomes more contentious when announced by a tech giant. At the start of the 2019 UK election, Facebook announced that it would not fact-check ads run by political parties or election candidates. Omitted from stories about this is that Facebook is acting as every other advertisers and the ASA does in this regard, political ads are not policed on factual claims.", "tags": "", "url": "index.html#6.5251.efsxy._wj0k.z-lap.k2vqm"},
     
     {"title": "New technology changing the discussion", "text": "The story is framed around anger at Facebook rather than approaching it from the angle that Facebook is behaving as an unremarkable advertiser in a UK election. This leads to what would be, in the other context, interesting opinions for politicians to have: ", "tags": "", "url": "index.html#6.5498.mcelu.loebl.gk5yq.n9wll"},
     
     {"title": "New technology changing the discussion", "text": "Damian Collins, a Conservative member of Parliament who has been spearheading parliamentary hearings on Facebook, told CNN Business Friday: &quot;People shouldn&#39;t be able to spread disinformation during election campaigns just because they are paying Facebook to do so.&quot; ^0", "tags": "", "url": "index.html#6.2554.gbvbj.2sce6.yb5p-.7xj1k"},
     
     {"title": "New technology changing the discussion", "text": "This is hard to disagree with, but is also a principle that goes wider. Why should you be able to spread misinformation just because you paid anyone for newspaper ads, billboard space, or leaflet printing? That there should be some limits on this is a principle that applies to every other industry except our governance industry. Changing conversations around regulation of political advertising are not just led by contentious elections, but a consolidation of advertising and political power by new industries. ", "tags": "", "url": "index.html#6.8149.hkyxh.ksc2b.x7q8b.89fwy"},
     
     
     
     {"title": "Practicalities", "text": "Models from abroad show that regulating political advertisement is not inherently impossible and working examples exist. But are there reasons unique to the UK&#39;s political context that mean a similar system could not be used here?", "tags": "", "url": "index.html#7.9185.gybpe.6mw96.e1n_j.gkyid"},
     
     {"title": "Fact vs opinion", "text": "While respecting the high priority the Electoral Commission places on its political impartiality, their arguments are risk-averse towards this end. The case that regulation is flat-out impossible (rather than undesirable) does not hold.", "tags": "", "url": "index.html#fact-vs-opinion"},
     
     {"title": "Fact vs opinion", "text": "For instance, one argument made in their 2004 report is that the whole idea is impractical because political claims are too subjective:", "tags": "", "url": "index.html#7.8479.a0i3y.or60c.9ipsh.dm_hw"},
     
     {"title": "Fact vs opinion", "text": "It would seem inappropriate and impractical to seek to control misleading or untruthful advertising, given the often subjective nature of political claims.^*", "tags": "", "url": "index.html#7.7783.yih6y.xaszk.nmu8o.-ezs8"},
     
     {"title": "Fact vs opinion", "text": "This is special pleading for the uniqueness of political advertising. As the CAP argued in their submission, &quot;&quot;all advertising involves subjectivity and ... political advertising is not a special case in this regard&quot;&quot;.^1 In reality a great deal of factual claims can be isolated from opinion and judged separately.", "tags": "", "url": "index.html#7.3668.qiavq.vffwe.cgye_.2u3fp"},
     
     {"title": "Fact vs opinion", "text": "We can see this in a system already in place in the UK. Adverts about petitions can be political but not related to elections or referendums. As such the ASA can, and does, make rulings about them. This gives some idea as to what a world in which the ASA judged election ads would look like.", "tags": "", "url": "index.html#7.3409.qbwtp.qfjw3.2pkye.ha9r9"},
     
     {"title": "Fact vs opinion", "text": "One advert taken out by &amp;#8216;Coalition For Marriage Ltd&#39; is especially interesting. This ad asked people to sign a petition &quot;&quot;in favour of keeping the definition of marriage unchanged&quot;&quot; - with the fact that &quot;&quot;70% of people say keep marriage as it is. Source: ComRes poll for Catholic Voices&quot;&quot;. The ASA didn&#39;t uphold a complaint about this statistic and went into detail as to why it didn&#39;t find the &quot;&quot;70%&quot;&quot; figure misleading - finding it was an accurate summary of the poll the advert cited. This represents a limited but practical judgement of a fairly typical kind of political claim.^* ", "tags": "", "url": "index.html#7.4872.cqgch.rcokf.nkhyv.au-yv"},
     
     {"title": "Fact vs opinion", "text": "In another adjudication involving a &amp;#8216;Restore Justice Campaign&#39; the ASA upheld a complaint about an online banner stating &quot;&quot;IN 1964 MPS ABOLISHED HANGING&quot;&quot; on frame 1, &quot;&quot;THE MURDER RATE HAS DOUBLED&quot;&quot; on frame 2 and &quot;&quot;SIGN THE HM Government Directgov E-PETITION&quot;&quot; on frame 3.", "tags": "", "url": "index.html#7.534.gqokx.eb9rf.n0whj.gtnz9"},
     
     {"title": "Fact vs opinion", "text": "The complainant raised two issues: a) the statistic that the murder rate had doubled, and b) the implication that abolishing hanging had caused the rise. The ASA upheld the first complaint but not the second - demonstrating that it was able to distinguish between factual content and opinion.^* Political advertising is already dealt with in the UK - just on a very limited scale.", "tags": "", "url": "index.html#7.6177.pqqmw.rvdkv.trpf3.t9cha"},
     
     {"title": "Human rights", "text": "One of the reasons the CAP gave for avoiding regulation of political advertising was the implementation of the Human Rights Act in 1998. However as a result of cases decided since then there is good reason to believe this isn&#39;t a barrier to all interventions.", "tags": "", "url": "index.html#human-rights"},
     
     {"title": "Human rights", "text": "Part of Phil Woolas&#39; defence was to refer to his right under the European Convention of Human Rights ECHR to free expression. The Election Court held that there was no right to false statements if that undermined the right to free elections, quoting the 1911 North Lough case&#39;s interpretation of the law:", "tags": "", "url": "index.html#7.2587.eob5m.1dy2n.sw-kx.gbror"},
     
     {"title": "Human rights", "text": "The primary protection of this statute was the protection of the constituency against acts which would be fatal to freedom of election. There would be no true freedom of election, no real expression of the opinion of the constituency, if votes were given in consequence of the dissemination of a false statement as to the personal character or conduct of a candidate...^*", "tags": "", "url": "index.html#7.2412.tsxcb.fjaey.rcg7g.chm8w"},
     
     {"title": "Human rights", "text": "In their judicial review the Divisional Court specifically prioritised the ECHR rights of voters over Woolas&#39; Article 10 rights:", "tags": "", "url": "index.html#7.4246.dg2s0.0gr46.f_hur.shcmw"},
     
     {"title": "Human rights", "text": "Dishonest statements are aimed at the destruction of the rights of the public to free elections (Article 3 of the First Protocol) and the right of each candidate to his reputation (Article 8 (1)). Article 10 does not protect a right to publish statements which the publisher knows to be false.^*", "tags": "", "url": "index.html#7.6983.za9jc.radbn.3hngt.l6pai"},
     
     {"title": "Human rights", "text": "This argument relies on Article 17, which is designed to prevent one right being used towards the &quot;&quot;destruction&quot;&quot; of another. Jacob Rowbottom argues that this approach is extreme (effectively placing &quot;&quot;dishonest speech alongside holocaust denial and neo-Nazi speech&quot;&quot;) and instead argues that the restrictions in section 2 of Article 10 are sufficient in themselves to justify interventions against misleading speech.^* Either way:", "tags": "", "url": "index.html#7.3539.2bzwy.od4ky.idoeh.qumly"},
     
     {"title": "Human rights", "text": "The position of the British courts appears to give the legislature considerable power to restrict dishonest statements in elections without falling foul of Article 10.^*", "tags": "", "url": "index.html#7.4250.qncpr.0aaiy.0yz1v.y91hw"},
     
     {"title": "Human rights", "text": "As explored earlier the ECHR did make the court nervous about too expansive a view of the existing law, but it should not be taken as a given that the ECHR inherently empowers candidates or campaigners to overcome any restraints of law. British systems are perfectly capable of making this decision, when guided by legislation. ", "tags": "", "url": "index.html#7.6974.mv57a.ghomx.d2dqj.h2oo7"},
     
     {"title": "Speed", "text": "Another argument made is that there are special time pressures involved in political advertising that make judgements impossible. However, a great amount of political adverts could be dealt with at the pace everyone else works to. The last successful political ASA complaint (Demon Eyes) was made a year before the next general election. In the AV referendum the contested &amp;#163;250 million figure was first introduced in February before a May vote. There&#39;s nothing inherently unworkable about dealing with these kinds of claims well before the vote.", "tags": "", "url": "index.html#speed"},
     
     {"title": "Speed", "text": "But what about a matter in the last weeks of the campaign? The New Zealand ASA has a solution to this problem: they do it quicker. On complaints made in the run-up to an election the following procedure is used:", "tags": "", "url": "index.html#7.3876.rwixy._-bu7.mf4pv.hvxoa"},
     
     {"title": "Speed", "text": "The Chairman also ruled that the matter be dealt with immediately, as the General Election was pending. Accordingly, an urgent Complaints Board meeting was called, and the Advertiser given approximately 24 hours in which to respond.^*", "tags": "", "url": "index.html#7.5839.mpva8.-9nbk.p0k8k.qlvmu"},
     
     {"title": "Speed", "text": "In South Australia the Electoral Commission similarly tries to resolve the issue quickly:", "tags": "", "url": "index.html#7.4015.berxc.16zi_.1oeu5.glcxz"},
     
     {"title": "Speed", "text": "ECSA aims to resolve most issues within 3&amp;#8211;4 days. In cases where conflicting evidence and counter submissions occur, matters may take some 1&amp;#8211;2 weeks to resolve. Where there is the likelihood of prosecution action, this may extend the resolution for some months.^*", "tags": "", "url": "index.html#7.9714.x_nrp.z8ul7.f_k13.4vhzf"},
     
     {"title": "Speed", "text": "Towards the very end you could certainly argue there is not much point doing anything at all, but this special time pressure applies to a very small part of the campaign. That some adverts might not be able to be judged in time does not mean that regulating political advertising three months or a year beforehand is pointless. A false claim repeated for an entire year before an election is more of a problem than one made at the very last minute. Given the general perception that political advertising is no less regulated than any other, people might reasonably conclude that the ad would not be allowed to be re-used if it was not true. ", "tags": "", "url": "index.html#7.4722.u2z5i.5jpxn.jnrcd.su6e5"},
     
     {"title": "Trust the electorate", "text": "An idea that keeps coming up is that we already have a body in place to judge if claims are true: the electorate. The courts argue that voters are miraculously more able to judge misleading claims about politics than they are about people. Similarly the Conservative Party argued in their submission to the Electoral Commission that &quot;&quot;if electors are unhappy with the tone of political advertising they are well placed to voice that disapproval and withdraw their support for any political party engaging in such behaviour. In this context, self regulation already exists&quot;&quot;.^1", "tags": "", "url": "index.html#trust-the-electorate"},
     
     {"title": "Trust the electorate", "text": "In their 2019 submission to a House of Lords Select Committee, the party similarly argued: ", "tags": "", "url": "index.html#7.3353.ov4tj.czfia.wso4e.-yzvd"},
     
     {"title": "Trust the electorate", "text": "We do not believe it would be beneficial to try to create some &amp;#8216;political truth commission&#39;. Rather, the Government should ensure that there is an independent free press to facilitate robust political debate and scrutiny by the press and public. ^0", "tags": "", "url": "index.html#7.5761.ptgi9.3fmkj.nz011.qfzhm"},
     
     {"title": "Trust the electorate", "text": "But as an Australian report on political advertising pointed out, this is a historically familiar argument and it was &quot;&quot;once also alleged that the market would operate to allow consumers to ascertain the truth about products&quot;&quot;.^1 If the public truly are the best judge of the truth of claims, we should ask not just whether an ASA-like body should police political claims, but whether the ASA should exist at all.", "tags": "", "url": "index.html#7.6984.vqyv4.ky5zw.h4udo.dl9a6"},
     
     {"title": "Trust the electorate", "text": "Defending a ban on broadcast political advertising, Lord Bingham argued that the playing field should be level in terms of what arguments were present, but that working out which argument was best should be left to the public:", "tags": "", "url": "index.html#7.638.rzsas.k4zew.ufadg.iqbu5"},
     
     {"title": "Trust the electorate", "text": "The fundamental rationale of the democratic process is that if competing views, opinions and policies are publicly debated and exposed to public scrutiny the good will over time drive out the bad and the true prevail over the false. It must be assumed that, given time, the public will make a sound choice when, in the course of the democratic process, it has the right to choose. But it is highly desirable that the playing field of debate should be so far as practicable level. This is achieved where, in public discussion, differing views are expressed, contradicted, answered and debated. ^1", "tags": "", "url": "index.html#7.5206.jp5jy.mzohc.1lx6w.u4enx"},
     
     {"title": "Trust the electorate", "text": "The underlying idea is that bad information, whether maliciously or innocently entered into the debate, can be corrected with good information. In an active and vigorous political culture, lies will be punished and truth will rise to the top.", "tags": "", "url": "index.html#7.6528.3vsxr.kd7uq.egbon.tgb5f"},
     
     {"title": "Trust the electorate", "text": "The problem is that this is clearly not working. In the 2016 EU referendum Ipsos MORI found that the public were &quot;&quot;more often very wrong on some of the key issues fundamental to the debate&quot;&quot;.^*  During the 2019 election,the fact-checking charity Full Fact conducted a survey on a set of statements that had previously been fact-checked and found that of the false statements, &quot;&quot;at least a quarter of survey respondents thought that each was true&quot;&quot;.^1 Looking at true statements, only around half thought they were true. While that half as many people believed false facts as true facts is good, but this is far from an effective filter.", "tags": "", "url": "index.html#7.7561.5ccde.t3m0h.xfz5g.5zhia"},
     
     {"title": "Political culture", "text": "UCL&#39;s Constitution Unit report makes the important point that the systems in South Australia and New Zealand exist in a political culture that has broadly not opposed them:", "tags": "", "url": "index.html#political-culture"},
     
     {"title": "Political culture", "text": "At least in the political cultures that we have been analysing &amp;#8211; those of South Australia and New Zealand &amp;#8211; significant political actors have not sought to undermine confidence in the bodies responsible for upholding these rules. Major political parties sometimes indicate disagreement with specific decisions, but they have not sought to turn the regulators into political footballs. Nor have newspapers or other media actors. ... This was essential to the effective operation of the system: had significant voices worked to undermine the regulators, the latter could not have done their job effectively. We &amp;#8211; and all those working within the UK system with whom we have spoken &amp;#8211; find it unimaginable that the same would apply in the UK.^0", "tags": "", "url": "index.html#7.1137.lbywg.xgjwk.hvx1z.mbsyt"},
     
     {"title": "Political culture", "text": "The (to put it politely) combative nature of political culture in the UK raises serious questions about transposing institutions from other countries. For instance, the actions of the Electoral Commission during and after the EU referendum have been questioned by both sides in long running arguments about expenses disclosures and limits. This has included multiple attempts at judicial reviews, and a mixture of successful and unsuccessful appeals against decisions.^0^1", "tags": "", "url": "index.html#7.761.gluhv.k0dlq.34u54.a71ux"},
     
     {"title": "Political culture", "text": "This has recently resulted in calls from former Vote Leave staff, that not only were the decisions wrong, but that the commission should be abolished.^2 The MP Peter Bone similarly asked as part of Prime Minsters&#39; Questions in June 2020:", "tags": "", "url": "index.html#7.9841.32h6r.fwt5y.2ylcg.gmstk"},
     
     {"title": "Political culture", "text": "Prime Minister, for the sake of democracy, will you ensure that that politically corrupt, totally biased and morally bankrupt quango is abolished?^0", "tags": "", "url": "index.html#7.81.nkf6d.1qks1.nse6u.kw56v"},
     
     {"title": "Political culture", "text": "Similarly in 2017 a Conservative MP accused the Electoral Commission of &quot;&quot;smearing the reputations of various Conservative politicians and their agents. It is clear that those who lead the Electoral Commission who followed and allowed this action to take place are politically-motivated and biased - actions that have rendered this organisation wholly unfit-for-purpose.&quot;&quot;^0", "tags": "", "url": "index.html#7.5033.6prpu.jl8if.w3n6l.p_dpv"},
     
     {"title": "Political culture", "text": "This is the kind of response that justifies caution about expanding the role of the Commission into the even more contentious area of political truth, at the expense of its core responsibilities.", "tags": "", "url": "index.html#7.3133.ncyul.un0yy.k0hfp.gmamd"},
     
     
     
     {"title": "Paths forward", "text": "It is worth stating clearly that the most likely road ahead is no change. While there is public support for regulation, there is little prospect of support from major parties, and while regulators in a private capacity think it might be a good idea, organisationally no one wants the job.^0 The courts police a strange subset of complaints. The ASA is a private body who would rather not get involved in elections. The Electoral Commission is a public body who want to avoid the perception of bias. Ultimately this all comes back to Parliament, unless MPs either legislate or create a code of self-regulation no one is willing to intercede further.", "tags": "", "url": "index.html#8.7378.7likk.0hipx.g35_m.r8ssh"},
     
     {"title": "The options", "text": "The possible paths that might exist include the legalistic Australian approach or a New Zealand-esque system of self-regulation. The Australian approach would be an expansion of current law to encompass political misleading statements, but would also introduce a proportionality requirement with regards to whether the statements in question could actually have affected the election. This could also be designed to allow challenges to election material without involving the courts by empowering the Electoral Commission to make initial judgements.", "tags": "", "url": "index.html#the-options"},
     
     {"title": "The options", "text": "The New Zealand system instead deals with misleading statements formally but not legally. An implementation of this would require a code of conduct between parties that a body like the ASA could enforce. As the sanctions are far weaker than voiding elections, a greater number of claims would be likely to be judged.", "tags": "", "url": "index.html#8.9101.oyeuq.sceug.abv8h.g6vrr"},
     
     {"title": "The options", "text": "Related to this question is whether the Electoral Commission or the ASA would be better suited for the job. Neither is comfortable with the idea, but in general the role seems more similar to the existing skill set of the ASA than the Electoral Commission. ", "tags": "", "url": "index.html#8.5467.rvlk1.cvahv.oqprz.d8abj"},
     
     {"title": "The options", "text": "Practically, the ASA has experience dealing with separating fact from opinion in commercial advertising and, despite claims to the contrary, political advertising is not all that different. It makes more sense to expand the scope (and resources) of the job the ASA is doing than to graft a new role onto the Electoral Commission.", "tags": "", "url": "index.html#8.1018.vtt_g.b4izm.bh0kh.kevra"},
     
     {"title": "The options", "text": "As a result of the ASA&#39;s work in commercial advertising the public have an expectation that factual content is policed and a learned understanding of the ways more dubious facts are presented to comply with this. This might undermine the public&#39;s defences against political misinformation. A claim that would have to be marked with an asterisk and suspicious small-print by an airline can be stated boldly by a political advertiser. That a majority of people are unaware that the same standards do not apply is a problem that arguably sits with the ASA. ", "tags": "", "url": "index.html#8.4756.yu9km.2yxwp.3dlls.y1unp"},
     
     {"title": "The options", "text": "Alternatively, as the Lords Select Committee on Democracy and Digital Technologies suggested, a new body could be created with the input of several organisations.^0 The creation of which would be a reflection that considerable resources need to be dedicated to the operation of a system, but would also not have the ASA&#39;s pre-existing reputation for neutrality. The enabling steps for such an organisation would be similar to what would be required to enable the ASA, so the approach below remains relevant in either case.", "tags": "", "url": "index.html#8.8665.hrmsx.4to79.qqyh8.p9xhw"},
     
     {"title": "Providing a backstop for private regulation", "text": "The problem of regulating political advertising is sometimes framed as the difficulty of getting politicians to self-regulate like the other industries that accept the verdicts of the ASA.", "tags": "", "url": "index.html#providing-a-backstop-for-private-regulation"},
     
     {"title": "Providing a backstop for private regulation", "text": "As Lord Currie (the chair of the ASA) said in evidence to a Lords Select Committee in 2019, &quot;we are a collective self-regulatory system. We rely on the buy-in of the people we regulate to comply with the system&quot;.^0", "tags": "", "url": "index.html#8.2444.giirp.klwdc.uxkvs.buu0l"},
     
     {"title": "Providing a backstop for private regulation", "text": "While true, this is also being generous. While the ASA is a system of self-regulation, it is more accurate to say it is a system of self-regulation accepted as an alternative to the legal action that would otherwise result. ", "tags": "", "url": "index.html#8.875.rfg8d.isrsc.u-x3v.7zgmc"},
     
     {"title": "Providing a backstop for private regulation", "text": "When a company opts out of &#39;self regulation&#39;, the ASA can and does escalate through the legal backstop (currently The Consumer Protection from Unfair Trading Regulations 2008). For example, in 2018 FreeFusion Ltd refused to amend its website to comply with an ASA judgement. The ASA referred to trading standards and this led to a successful prosecution.  The law defers to &quot;established means&quot; (e.g. self-regulation through the ASA), but remains present as a stick to ensure compliance. ", "tags": "", "url": "index.html#8.1847.cz5fa.c7smn.hhl5n.niblk"},
     
     {"title": "Providing a backstop for private regulation", "text": "Aside from the limited law around character, there is not an equivalent legal threat to persuade political parties of the virtues of being part of a voluntary system of regulation. While British courts have leeway to restrict misleading speech under law, what has not been seen to date is how willing they would be to apply this to private actors enforcing restrictions extra-legally. As decisions made by the ASA have been found to be subject to judicial review, stepping too far beyond their legal backstop would invite challenge. ", "tags": "", "url": "index.html#8.6052.13vry.uyxyl.ykwfr.efitx"},
     
     {"title": "Providing a backstop for private regulation", "text": "The New Zealand ASA shows that regulation without legal basis can be successful, but this depends on a political culture of no one complaining about it. The cautionary tale of FACTS in Australia shows that regulation without rooted support is fragile. Fundamentally our political culture is hostile to the idea and would fight against action outside a legal or agreed arrangement.", "tags": "", "url": "index.html#8.2574.lqlkx.sceug.kykql.igjim"},
     
     {"title": "Providing a backstop for private regulation", "text": "A goal of law as a backstop shifts the nature of the problem. As the Conservative Party noted correctly in 2002, in an area with only a few big players, one hold-out can derail the entire process of self-regulation. But the creation of a legal backstop does not need the consent of all the players, it just needs a majority in Parliament. This is a difficult, but substantially easier goal.", "tags": "", "url": "index.html#8.3590.g9vzo.qatsu.tr66u.p60lj"},
     
     {"title": "Providing a backstop for private regulation", "text": "What would this legislative backstop look like? It might make sense to construct a weak version of South Australia&#39;s law. By weak, this means avoiding the idea that misleading advertising is an &quot;illegal practice&quot; (which implies the ability to overturn the results of an election), focusing solely on the idea that misleading statements of fact could be subject to an injunction, and that enforcement should defer to &quot;established emans&quot;. ", "tags": "", "url": "index.html#8.5059.mzm9e.jahxv.lgv9j.wyprz"},
     
     {"title": "Providing a backstop for private regulation", "text": "The existence of this backstop would hopefully be sufficient to compel agreement on a code of conduct. It is also more secure against future insurgent parties or candidates, who may exist outside any self-regulated consensus. ", "tags": "", "url": "index.html#8.4984.dykfd.gd6ry.-svkh.zsyoq"},
     
     {"title": "Code of practice", "text": "What might a code of practice between political parties look like? New Zealand&#39;s working system can provide a model for discussion, especially the idea of advocacy principles that require political advertisement be dealt with &quot;&quot;liberally&quot;&quot;, while still being able to close down demonstrably untrue statements of facts. The following are drawn from the NZ ASA&#39;s rules and adapted for the UK&#39;s rights context:", "tags": "", "url": "index.html#code-of-practice"},
     
     {"title": "Code of practice", "text": "That Article 10 of the ECHR, in granting the right of freedom of expression, allows advertisers to impart information and opinions but that in exercising that right what was factual information and what was opinion should be clearly distinguishable.That the right of freedom of expression as stated in Article 10 is not absolute as there could be an infringement of other people&#39;s rights. Care should be taken to ensure that this does not occur.That the Codes fetter the right granted by Article 10 to ensure there is fair play between all parties on controversial issues. Therefore in advocacy advertising and particularly on political matters the spirit of the Code is more important than technical breaches. People have the right to express their views and this right should not be unduly or unreasonably restricted by Rules.That robust debate in a democratic society is to be encouraged by the media and advertiser and that the Codes should be interpreted liberally to ensure fair play by the contestants.That it is essential in all advocacy advertisements that the identity of the advertiser is clear.", "tags": "", "url": "index.html#8.6376.wygpl.hf-ks.ybur_.venl4"},
     
     {"title": "Code of practice", "text": "This provides a reasonable and common sense approach to political speech, in which its special role in democratic society is protected with additional leeway, but voters also gain protection from the most obvious false statements of fact.", "tags": "", "url": "index.html#8.4780.ivrck.zgeme.rgw_o.gnkqg"},
     
     {"title": "Conditions for designated status in referendums", "text": "As referendum campaigns are by their nature temporary they have far less incentive to abide by instructions to withdraw adverts or avoid repeating claims. However, it is worth remembering that the benefits of becoming the designated campaign on one side of the issue are substantial. For the EU referendum designated campaigns received:", "tags": "", "url": "index.html#conditions-for-designated-status-in-referendums"},
     
     {"title": "Conditions for designated status in referendums", "text": "A higher spending limit of &amp;#163;7 million One free distribution of information to votersThe use of certain public roomsReferendum campaign broadcastsA grant of up to &amp;#163;600,000, to be used for certain spending including the administration costs associated with setting up and running a referendum campaign and the costs associated with the TV broadcasts and free mailing to voters that they are entitled to as lead campaignersA dedicated page in the Commission&#39;s public information booklet which will be distributed to all households in the UK (in both English language and bilingual English/Welsh language versions)The inclusion in the booklet of a link to a page on the campaigner&#39;s website, which should include their opinion on what will happen in the event of either referendum result.^*", "tags": "", "url": "index.html#8.5709.c4pcn.p6-b1.uq7rw.dkaa0"},
     
     {"title": "Conditions for designated status in referendums", "text": "Given how much public money is spent distributing the arguments of the campaign, it seems reasonable to require (as suggested by Renwick) that this funding be conditional on abiding by a code of conduct that creates some protections for the electorate.^*", "tags": "", "url": "index.html#8.2115.vv-d0.ivdqz.taaow.efarf"},
     
     {"title": "Conditions for designated status in referendums", "text": "When there is no expectation that campaigners are being honest with the public the democratic polity is damaged. We need to create structures that incentivise the short-term organisations that run referendum campaigns to campaign in such a way that society is better off as a result of the campaign, regardless of the outcome of the vote. As such, either by amending the Political Parties, Elections and Referendums Act 2000 or conditionally in legislation enabling future referendums, designated campaigns should be required to agree to a code of conduct. This code should be simple, providing a small backstop on factual claims and making abiding the decisions of independent bodies like the ASA a requirement of continued preferential status. ", "tags": "", "url": "index.html#8.1646.o7_cj.ckrwq.ih8kw.gnvug"},
     
     
     
     {"title": "Conclusion", "text": "Arguments against promoting truth in political advertising are not unanswerable. Systems that manage this exist, function, and are viable alternatives to our current approach of doing very little. At the same time, the scale and political culture of the UK present obstacles not encountered by those systems and this needs to be reflected in approach. ", "tags": "", "url": "index.html#9.5929.nu9eo.grxmj.aqk3v.i5fwi"},
     
     {"title": "Conclusion", "text": "While giving greater leeway to political adverts than commercial adverts is reasonable, the current gulf between political and commercial regulation is too large. A better balance between protecting the electorate from lies and protecting them from undemocratic paternalism is achievable.", "tags": "", "url": "index.html#9.7253.fuxdz.qg6qt.z0jdq.233f0"},
     
     {"title": "Conclusion", "text": "The question of how to resolve this has endlessly been referred to the impossibility of cross-party agreement, but this ignores that self-regulation of commercial advertising exists in the shadow of potential legal action. Rather than chasing this agreement, the goal should be the creation of the minimal legal backstop. This would encourage the development of agreed processes and standards (enforced by the ASA or a similar organisation). This should not be concerned with over-turning elections, but aimed at the fast removal of clear false statements of fact. ", "tags": "", "url": "index.html#9.9602.jclbu.dwksd.wdund.za7iu"},
     
     {"title": "Conclusion", "text": "This is far from a solution to &#39;lying&#39; in politics. These rules have not magically created truthful environments when implemented, simply created opportunities for redress in a wider set of circumstances. But just because deceit has always been a problem in democracy does not mean we have to accept the extent of it.", "tags": "", "url": "index.html#9.9570.hwlpj.9ffx0.agtsv.tjsij"},
     
     {"title": "Acknowledgements", "text": "This document is an expansion of a section of a 2012 MSc dissertation. It was initially published in 2016, and was updated in June 2019. The 2016 version can be read here.", "tags": "", "url": "index.html#acknowledgements"},
     
     {"title": "Acknowledgements", "text": "The title image is made up of election leaflets submitted to electionleaflets.org and a US Geological Survey image the mosaic image was created with AndreaMosiac.", "tags": "", "url": "index.html#9.727.18q-u.m9lka.wv0tr.svx6a"}
     
     
]};