


var tipuesearch = {"pages": [
     
     
     {"title": "Intro", "text": "&amp;#65279;", "tags": "", "url": "index.html#1.4257.2jmj7.2jmj7.2jmj7.2jmj7"},
     
     
     
     {"title": "Introduction", "text": "That people might lie and mislead to win elections isn&#39;t really a surprise - there&#39;s nothing modern about the idea. Looking back at historical elections for a quiet era of civility is often a disappointment, revealing personal attacks and misinformation that would make even today&#39;s lowest spin doctor blush. Disinformation makes democracy worse, but it&#39;s always been there - what can you really do about it?", "tags": "", "url": "index.html#2.4777.aoikz._d9ps.or8-g.5aq9i"},
     
     {"title": "Introduction", "text": "On the other hand it would once have been said you can&#39;t do much about the snake oil salesman - but we&#39;ve made progress at clawing back advertising space for the public good. If a product is marketed as a high-tech water-finding device but turns out to be a stick, you can challenge the advert. Your complaint will be dealt with formally; serious people will sit in a room and review the evidence and, if they agree with you, will stop that company from re-running the advert. It&#39;s not perfect, but it&#39;s much better than nothing. ", "tags": "", "url": "index.html#2.3056.1vq7e.8xkac.ri44d.ryfjk"},
     
     {"title": "Introduction", "text": "We have no such protection during elections. If someone says on their  leaflet that a proposal is going to cost hundreds of millions (when it won&#39;t), or that they voted to protect the local hospital (when they didn&#39;t) there&#39;s nowhere you can go. You can put it on Facebook, you can go door to door and tell everyone - but there is nothing you can do to stop them printing it again, and again.", "tags": "", "url": "index.html#2.3791.jxawv.n7prp.dsiwj.0adto"},
     
     {"title": "Introduction", "text": "Despite the obvious importance of voters being informed, we hold the claims of politicians and campaigners to a far lower standard than we do shampoo commercials. ", "tags": "", "url": "index.html#2.2425.zznkg.kkjyk.4wijm.utvub"},
     
     {"title": "Introduction", "text": "Fixing this is complicated. It&#39;s all very well saying voters should be told the truth, but who&#39;s going to decide what the truth is? Retired politicians? Judges?", "tags": "", "url": "index.html#2.3703.6qrkj.z9vlh.1t8se.bs0ix"},
     
     {"title": "Introduction", "text": "This is a hard problem - but it isn&#39;t an unsolvable one. We can raise the standards for truth in elections and there are several working systems internationally we can learn from. ", "tags": "", "url": "index.html#2.3083.csdnc.ynn0e.notlh.9c4y3"},
     
     {"title": "Introduction", "text": "Specifically, we should aim for two changes:", "tags": "", "url": "index.html#2.2147.bqja5.o7lq7.z0bvs.o5dol"},
     
     {"title": "Introduction", "text": "The Advertising Standards Authority should emulate its counterpart in New Zealand and end its exemption for political advertising. This would allow political advertising to be judged by the same system as any other advertising - but with liberal interpretation of political claims to protect the vital role of free expression in elections. Enforce this same rule for referendum campaigners by making access to public funds conditional on respecting the judgements of the ASA.", "tags": "", "url": "index.html#2.1174._akdd.icsrj.dgozy.wgbom"},
     
     {"title": "Introduction", "text": "To explain how we can accomplish this I&#39;m going to tell you the story of how people have tried to tackle the problem in the past: what our current laws mean, why we have them - and what other options are available.", "tags": "", "url": "index.html#2.8719.a99m6.qatbi.eymau.j4-9d"},
     
     
     
     {"title": "Once a Century", "text": "The 2010 election upset a lot of notions about how elections in the UK should work. The campaigns featured the first public debate between party leaders and the electorate delivered a result that was thought to be impossible in the UK: a stable coalition government. ", "tags": "", "url": "index.html#once-a-century"},
     
     {"title": "Once a Century", "text": "In addition to these was another break from history: an elected MP was removed from the House of Commons for lying to the electorate.", "tags": "", "url": "index.html#3.4841.xrsw9.ydxdp.6br_-.rlwoo"},
     
     {"title": "Once a Century", "text": "Six months after polling day Phil Woolas - a former Labour Minister and MP of thirteen years - left the House of Commons because a court declared his election void. The reason? The court had found he lied about the personal character of his opponent and as such had committed an illegal practice. This was surprising because (while this law is occasionally used against councillors) only one other MP has ever run into trouble and that was in 1911. Even that comparison isn&#39;t strictly fair because in the 1911 case lies featured alongside charges of voter intimidation and bribery. This makes Woolas the first MP to lose his seat solely for misleading statements.^*", "tags": "", "url": "index.html#3.505.ex0m7.qrqe0.mt4fk.hk_ed"},
     
     {"title": "Once a Century", "text": "But was Woolas the first MP to tell a lie and win an election in a century? If (as we might suspect) this is not the case, why doesn&#39;t this happen all the time? Commenting on the case, MP John Mann said:", "tags": "", "url": "index.html#3.7085.fes13.fgkrc.ciw75.6kfjy"},
     
     {"title": "Once a Century", "text": "From looking at the publicity and propaganda that there have been, I think it is factually accurate to say that there have been worse in recent elections from all three main parties than in the case of Mr Woolas, and the candidates in question have won.^*", "tags": "", "url": "index.html#3.2083.aic4j.t1rgg.lctpr.dessz"},
     
     {"title": "Once a Century", "text": "Even assuming it&#39;s not half as bad at that, the uniqueness of the Woolas case is strange. What was the difference between him and people who got away with it? What did he do wrong?", "tags": "", "url": "index.html#3.9982.drdoj.nijf3.zx7-f.leczr"},
     
     {"title": "A Man&#39;s Honour", "text": "Woolas&#39; specific problem was running afoul of section 106 of the Representation of the People Act 1983. This reads:", "tags": "", "url": "index.html#a-mans-honour"},
     
     {"title": "A Man&#39;s Honour", "text": "(106) A person who, or any director of any body or association corporate which &amp;#8212;(a) before or during an election,(b) for the purpose of affecting the return of any candidate at the election,makes or publishes any false statement of fact in relation to the candidate&#39;s personal character or conduct shall be guilty of an illegal practice, unless he can show that he had reasonable grounds for believing, and did believe, that statement to be true.^*", "tags": "", "url": "index.html#3.4533.feebt.irnku.ckuij.wfjgs"},
     
     {"title": "A Man&#39;s Honour", "text": "As an illegal practice this has the potential to void the results of elections and the Act also has a provision allowing for injunctions that can restrain future publication of these false statements before the election has finished. ", "tags": "", "url": "index.html#3.2417.tkncl.bvapd.b2vuo.p92ya"},
     
     {"title": "A Man&#39;s Honour", "text": "There&#39;s quite a Victorian feel to this talk of &quot;personal character&quot; and indeed the clause descends from the much older Corrupt and Illegal Practices Act 1895. The debate surrounding the original version of this section makes for interesting reading. While in Woolas&#39; case the idea of injury to the voter would become the more pressing issue, the original intention was focused more on the injury to the candidate and their standing. The Lib-Lab MP Henry Broadhurst made a stirring address to the House making clear the point of the honour at stake:", "tags": "", "url": "index.html#3.1405.au8tx.9bjlp.d2tpn.tlget"},
     
     {"title": "A Man&#39;s Honour", "text": "If they were what they all aspired to be, honourable English Gentlemen, they should all denounce, in the strongest possible terms, such proceedings as the Bill aimed at.^*", "tags": "", "url": "index.html#3.4313.v5ubt.yltba.mvyy6.aeswe"},
     
     {"title": "A Man&#39;s Honour", "text": "During the debate MPs sounded off with a liturgy of common libels. These commonly included being accused of being an Atheist or of underpaying labourers - but at the more extreme end one said that they had been accused of being &quot;&quot;a pirate who had sunk English ships and marooned their crews&quot;&quot;.^* Herbert Leon complained that he:", "tags": "", "url": "index.html#3.7404.bzzyk.c29wa.5ywja.zqt7s"},
     
     {"title": "A Man&#39;s Honour", "text": "had been the victim of a slander at the last General Election, when he was accused by a Conservative paper of advocating horse-racing and debauchery on Sundays, and murders committed.^*", "tags": "", "url": "index.html#3.7169.ufgej.qycin.fnztl.6kms2"},
     
     {"title": "A Man&#39;s Honour", "text": "(It being open to debate if gambling or murder was the more serious accusation.)", "tags": "", "url": "index.html#3.2299.mremr.zj7tg.dbfnk.oaelq"},
     
     {"title": "A Man&#39;s Honour", "text": "Donald Macfarlane claimed that an untrue report about the crew of his yacht poaching salmon (on a Sunday!) was attuned to local sensitivities to have the biggest impact. If his opponents had said that &quot;&quot;he had sent the men of his yacht to carry off half-a-dozen of the lairds&#39; wives &amp;#8230; it would not have had nearly the same effect&quot;&quot;.^*", "tags": "", "url": "index.html#3.4219.byeoe.4plpy.m4b3j.ekzc4"},
     
     {"title": "A Man&#39;s Honour", "text": "These issues seem fairly unambiguously about personal character but the big complication with the law then - as now - is working out the far murkier area of when and how political activity is distinct from character. There was general agreement that there was indeed a difference, and that tackling political falsehoods might be a problem. Robert Reid argued that:", "tags": "", "url": "index.html#3.5842.z1rtp.loffg.ywtjb.ocud_"},
     
     {"title": "A Man&#39;s Honour", "text": "Anything that savoured of a political character should not be made a ground for interference with an election. As long as human nature remained what it was, I believe that in elections there would be exaggerations and unfounded statements as to the opinions of people with whom other people did not agree which it would be impossible to avoid, and all they could do was to hope that the electors would have the good sense to take the necessary discount off such statements.^*", "tags": "", "url": "index.html#3.3848.kwtwq.xciqj.yg2z3.8tguh"},
     
     {"title": "A Man&#39;s Honour", "text": "MPs complained of &quot;black lists&quot; being published - fake reports of the votes they had taken in Parliament (the Victorian ancestors of twitter infographics). But what is the difference between a made-up record of underpaying workers in non-political life and a made-up voting record of supporting &quot;&quot;flogging in the Army and perpetual pensions&quot;&quot;?^* Both are a track record that speak to personal character but the subject of votes in Parliament can&#39;t be treated as anything other than political. Henry Labouchere made this exact point at the time:", "tags": "", "url": "index.html#3.7989.qpdji.zemuh.ky-n7.ft21y"},
     
     {"title": "A Man&#39;s Honour", "text": "It was very difficult to draw the line of demarcation between what was political and what was not, in speeches. Hon. Gentlemen opposite, for example, very often accused their opponents of wishing to disintegrate the Empire. Now he thought it was contrary to proper political conduct to &quot;disintegrate the Empire.&quot; That was a personal accusation, and he could well conceive some magistrates holding that a person came under this Act by making such an accusation. On the other hand, were the Tory Party determined to make the Irish slaves to the Saxon for ever and ever? That, again, might be regarded as a personal accusation.^*", "tags": "", "url": "index.html#3.9020.msg0c.gctfk.bshtz.uop-4"},
     
     {"title": "A Man&#39;s Honour", "text": "Political conduct can and does speak to personal character. This fundamental wrinkle in the law was never adequately resolved - as the Woolas case demonstrates.", "tags": "", "url": "index.html#3.9256.lisie.uceu_.ls0c5.06ovw"},
     
     {"title": "Broken Promises", "text": "Election offences are treated differently than other criminal offences. Instead of being investigated by the police and prosecuted by the government, individuals have to challenge the result directly through an election petition. As the original intention was for one candidate to have recourse against another this makes sense, but it makes prosecutions &quot;&quot;in the public good&quot;&quot; more complicated. In the Woolas case his Liberal Democrat opponent, Elwyn Watkins, submitted a petition that triggered an election court.", "tags": "", "url": "index.html#broken-promises"},
     
     {"title": "Broken Promises", "text": "Woolas was initially found guilty of having made three unfactual statements in publications about Watkins. The full documents can be read at the bottom of the decision but to summarise Woolas these statements were:", "tags": "", "url": "index.html#3.5981.yhv6o.s_kq8.rirvq.rgbdx"},
     
     {"title": "Broken Promises", "text": "Claiming that Watkins was seeking to woo the vote of Muslims who advocated violence against Woolas;Claiming that Watkins refused to condemn Muslims who advocated violence against Woolas;Claiming that Watkins had broken a promise to live in the constituency.^*", "tags": "", "url": "index.html#3.7056.vcr2j.vmpyk.cv4y1.yfsch"},
     
     {"title": "Broken Promises", "text": "The statements were also intermingled with attacks on Watkins&#39; political stances. In the Election Court&#39;s judgement the personal attacks could be separated from the politics:", "tags": "", "url": "index.html#3.5154.6c6hh.c-si8.kph4c.qlold"},
     
     {"title": "Broken Promises", "text": "To say that the Petitioner Watkins was aware that an extremist group had threatened violence to his political opponent and had refused to condemn such threats is, in our judgment, an attack on the personal character or conduct of the Petitioner. It is an attack on his &quot;honour&quot; or &quot;purity&quot; because, like the statement in the Examiner, it suggests that he is willing to condone threats of violence in pursuit of personal advantage. That is also an attack on his political conduct (because the advantage sought was an electoral victory) but that does not put the attack outside the protection afforded by section 106 if his personal character is also attacked).^*", "tags": "", "url": "index.html#3.1936.fz6yz.rockq.3ecyd.cmkkr"},
     
     {"title": "Broken Promises", "text": "They also argued that attacks on a political campaign could be personal attacks at the same time:", "tags": "", "url": "index.html#3.5682.vasdy.m4nmc.zavu7.x23i9"},
     
     {"title": "Broken Promises", "text": "His promise to live in the constituency was &quot;part of the campaign&quot;, made to establish his commitment to the constituency and to establish his credibility with the electorate. However, the statement also relates directly to his personal character or conduct. A person who breaks his promise is untrustworthy. To say that someone is not worthy of trust is to attack his &quot;honour, veracity and purity&quot;. It was described by the Respondent in evidence as a politician&#39;s promise. Whilst we accept that promises made by politicians may not be honoured because of changes in political circumstances, this particular promise cannot fall into any such category. The performance of the Petitioner&#39;s promise was within his control and so a failure to honour it reflected on his personal trustworthiness.^*", "tags": "", "url": "index.html#3.9757.t3fn2.capvd.osxkn.rhye3"},
     
     {"title": "Broken Promises", "text": "On judicial review the Divisional Court accepted the first argument but not the second. They upheld that claiming Watkins had condoned violence was an attack on his character but that claiming he broke his promise to live in the constituency was not a personal attack - or at least not one that was covered by the law:", "tags": "", "url": "index.html#3.4321.sxyer.jumfc.5huyp.ldh_e"},
     
     {"title": "Broken Promises", "text": "A statement that the candidate has reneged on his promise to live there does, we accept, cast an imputation on the candidate&#39;s trustworthiness, as the Election Court held, but it is in respect of his trustworthiness in relation to a political position. To hold that such a statement fell within the prohibition would have a significant inhibiting effect on ordinary political debate, as candidates, particular those who have been MPs, are sometimes criticised for going back on promises on a political issue.^*", "tags": "", "url": "index.html#3.7360.3iuvm.kf-hb.ui_n-.iz_pm"},
     
     {"title": "Broken Promises", "text": "This reduces what is otherwise a fairly large hole between political conduct and personal character. While a false claim of &quot;promise breaker&quot; does damage character, if the promise was political s.106 is not applicable. The position of the Divisional Court was that &quot;&quot;a court has to make that distinction and decide whether the statement is one as to the personal character or conduct or a statement as to the political position or character of the candidate. It cannot be both&quot;&quot;.^* While the review did very little for Woolas it tightened future grounds for complaint under s.106 considerably.", "tags": "", "url": "index.html#3.9094.alrrf.bryee.kgest.b83xp"},
     
     {"title": "Broken Promises", "text": "The review judgement falls down a bit when it tries to put a principle to this distinction:", "tags": "", "url": "index.html#3.2223.zok14.rc4vw.hkyac.w7-6v"},
     
     {"title": "Broken Promises", "text": "It was as self evident in 1895 as it is today, given the practical experience of politics in a democracy, that unfounded allegations will be made about the political position of candidates in an election. The statutory language makes it clear that Parliament plainly did not intend the 1895 Act to apply to such statements; it trusted the good sense of the electorate to discount them. However statements as to the personal character of a candidate were seen to be quite different. The good sense of the electorate would be unable to discern whether such statements which might be highly damaging were untrue; a remedy under the ordinary law in the middle of an election would be difficult to obtain.^*", "tags": "", "url": "index.html#3.7229.fdokx.m9bkg.hgitv.90l9v"},
     
     {"title": "Broken Promises", "text": "While an accurate reflection of parliamentary intentions (confused as they were) this position makes little logical sense. The court essentially argues that voters need less protection for political untruths because their &quot;&quot;good sense&quot;&quot; is adequate to detect them. They are &quot;&quot;unable to discern&quot;&quot; if damaging claims of a personal nature are true, but can be &quot;&quot;trusted &amp;#8230; to discount&quot;&quot; political ones. But both personal and political claims may be insubstantial or backed with evidence. There is little to distinguish between them as classes in terms of how easily voters can detect falsehoods. ", "tags": "", "url": "index.html#3.7278.vvln-.6mg5s.ekvrl.kgksi"},
     
     {"title": "Broken Promises", "text": "One reasons for courts to favour as narrow a view of &quot;personal character&quot; as possible are the practicalities. A broad construction gets into muddy water quickly; as the court put it, it is &quot;&quot;difficult to see how the ordinary cut and thrust of political debate could properly be carried on if such were the width of the prohibition. In any event it would also be difficult to reconcile such a broad construction with the balance that Article 10 Freedom of Expression mandates be achieved&quot;&quot;.^* The courts don&#39;t want to push here unless invited to by Parliament, and that seems unlikely to happen.", "tags": "", "url": "index.html#3.8795.66xlr.rkbgg.ofkgi.0oeqh"},
     
     {"title": "Broken Promises", "text": "The law was tested again in 2015 with a petition against Liberal Democrat MP Alistair Carmichael. Although this petition failed (what was described as a &quot;&quot;blatant but simple lie&quot;&quot;^1 was considered primarily political rather than personal), it did widen the previous accepted scope of the law by confirming that &quot;self-talking&quot; (statements about your own personal character that were untrue) could engage the law.^2 This attempt also showed the awkwardness of the petition system - in this case four of Carmichael&#39;s constituents had to crowdsource legal fees before advancing the petition.", "tags": "", "url": "index.html#3.2907.yfcad.zqxoj.9olai.h9cj_"},
     
     {"title": "Broken Promises", "text": "The law currently sits uncomfortably. It covers a strange sub-division of possible election lies; is burdensome in that it requires individuals to bring the petition; and severe in that might remove an MP from office without the prospect of appeal. No-one would draft anything like it today and no-one has any intention of re-visiting or re-purposing it in the near future.", "tags": "", "url": "index.html#3.4819.4gppr.azros.sefe9.fgfal"},
     
     {"title": "Broken Promises", "text": "For more workable examples of laws controlling false statements we have to look further afield.", "tags": "", "url": "index.html#3.3333.0k7gr.qzb0s.2xlix.yf9oq"},
     
     
     
     {"title": "Laws Elsewhere", "text": "Laws that go further than the UK aren&#39;t particularly common. The US generally goes the other way and tightens libel standards for political speech (see New York Times v Sullivan) - and those states that have had restrictions tend to lose them to constitutional challenges. That said, Australasia has several interesting examples of past and current laws that go further than the UK to control false statements of fact.", "tags": "", "url": "index.html#4.2953.wabug.dofe1.rgw_o.tawwp"},
     
     {"title": "Laws Elsewhere", "text": "The most recent example is the loss of Ohio&#39;s prohibitions on false statements^1 on first amendment grounds in Susan B. Anthony List, et al. v. Ohio Elections Commission.", "tags": "", "url": "index.html#4.8577.xnp0u.ck-7x.bh0kh.smgum"},
     
     {"title": "Australia", "text": "Australia briefly attempted a federal law that was later abandoned - but in South Australia there is an active prohibition on untruthful statements at the state level. The Electoral Act 1985 contains a offence for:", "tags": "", "url": "index.html#australia"},
     
     {"title": "Australia", "text": "113 (2) A person who authorises, causes or permits the publication of an electoral advertisement (an advertiser) is guilty of an offence if the advertisement contains a statement purporting to be a statement of fact that is inaccurate and misleading to a material extent.^0", "tags": "", "url": "index.html#4.7541.u8q0x.u6f9g.gkdno.-i-fs"},
     
     {"title": "Australia", "text": "This offence can carry a fine. For complainants the first port of call is the Electoral Commission (ECSA), who can then request the advert be withdrawn and/or a retraction published (from a legal point of view compliance here can affect any possible fine). In the event this is not followed, the Electoral Commissioner can go to a court who, if satisfied, have the power to order the same.", "tags": "", "url": "index.html#4.4302.monnb.e6ol4.iabm8.vmvgn"},
     
     {"title": "Australia", "text": "After the election the Court of Disputed Returns can declare an election void &quot;&quot;but only if the Court of Disputed Returns is satisfied, on the balance of probabilities, that the result of the election was affected by that advertising&quot;&quot;.^0 In other words, the scale of the victory matters when interpreting if the election had been affected. There is no such provision in the equivalent UK law. A false statement of fact about a candidate&#39;s personal character is an illegal practice, which unlike administrative breaches of electoral law isn&#39;t subject to a test of whether it &quot;&quot;materially affected the result of the election&quot;&quot;.^1 Technically speaking, if Woolas had won by a landslide as opposed to 103 votes the legal outcome should have been the same.", "tags": "", "url": "index.html#4.9934.ng998.pzbvn.iabm8.sex1i"},
     
     {"title": "Australia", "text": "It&#39;s worth noting that the Electoral Commission in South Australia would really like not to be involved in this:", "tags": "", "url": "index.html#4.4603.xdk8z.y6a-y.fqwqk.um8an"},
     
     {"title": "Australia", "text": "There is a real risk that the Electoral Commissioner will appear to have become politicised if she is involved in a significant decision favouring one party over another in the days immediately prior to the election.^1", "tags": "", "url": "index.html#4.6498.b3lbs.ch37w.-brfn.a3ds1"},
     
     {"title": "Australia", "text": "In addition to integrity concerns it generates a lot of work for the Commission. On one day &quot;&quot;a ream of paper some 22&amp;#8211;25 cm high was delivered to the commissioner in the form of supporting documentation&quot;&quot;^1 and in the final weeks of the 2010 election complaints were being made &quot;&quot;almost daily. As such, their consideration occupied a significant amount of ECSA staff time&quot;&quot;.^2", "tags": "", "url": "index.html#4.2156.6v1yw.ydxdp.iokzq.fhx4m"},
     
     {"title": "Australia", "text": "The Commission argues that very little comes out of this process as &quot;&quot;complaints tend to seize upon statements that could never be proven to the requisite level&quot;&quot; including &quot;&quot;statements of intention or opinion, or general statements of past success or failure in broad terms&quot;&quot;.^1", "tags": "", "url": "index.html#4.9470.73q5b.2eeoi.tzhqk.asue1"},
     
     {"title": "Australia", "text": "But that isn&#39;t to say complaints are never valid. In 1995 the Labor Party was found guilty of an offence for the following advert:", "tags": "", "url": "index.html#4.8056.c2fin.lvwjg.2qq_d.rjx1d"},
     
     {"title": "Australia", "text": "&quot;Could this be South Australia? If the Brown Liberals win the election South Australia will change in ways you and your kids never imagined.The fact is the Brown Liberals have stated that any school with less than three hundred students will be subject to closure. We have three hundred and sixty three schools with less than three hundred students. That&#39;s a big change.Don&#39;t let it happen. Don&#39;t let Mr Brown bring South Australia down.&quot;", "tags": "", "url": "index.html#4.9025.rqz2m.7tcti.3n_1a.bnou-"},
     
     {"title": "Australia", "text": "This was held to be a misleading interpretation of the Liberal spokesperson&#39;s statement:", "tags": "", "url": "index.html#4.3871.p19cs.wn8jz.u7kwz.2zdm0"},
     
     {"title": "Australia", "text": "&quot;Well. I mean &amp;#8230; we&#39;ve indicated here in South Australia that we&#39;re certainly not going to be closing two hundred schools in South Australia.If there are a small number of schools that have got very small numbers of students, well then under both governments I guess there will continue to be a small program of school closures, but we&#39;re not going to be looking at schools with three hundred students in them.&quot;", "tags": "", "url": "index.html#4.9276.ugcnd.rns04.a1rae.xtjrg"},
     
     {"title": "Australia", "text": "The defence argued that such speech was permissible under conditional freedom of communication, but the case gave the South Australian Supreme Court a chance to defend the interference with free speech the law required:", "tags": "", "url": "index.html#4.3875.-cjeb.pekop.dn9yg.r7oy1"},
     
     {"title": "Australia", "text": "That section recognizes that a truly informed elector is one who has not been subjected to deceit or misrepresentations such that the elector might vote contrary to the manner in which that elector would have voted but for the deceit or misrepresentations. Whilst s.113 does interfere with the right of the freedom of speech, it does so for the purpose of protecting the electors from being mislead and deceived. The Act, I think, attempts to balance the concept of freedom of speech and the right to be properly informed.", "tags": "", "url": "index.html#4.3200.83fle.d0pbq.6g5z5.zmr2c"},
     
     {"title": "Australia", "text": "That very few cases get this far reflects that balance at work. Almost all complaints fail or the scope of the action is restricted. In 1998, the court agreed an advertisement had been misleading but judged the impact not to have sufficient to warrant invalidating the election.^1 In 2010, the statement &quot;&quot;soft on crime&quot;&quot; was found to be opinion rather than fact and so couldn&#39;t be judged as misleading at all.^2", "tags": "", "url": "index.html#4.6017.qvaac.kxuvn.djtlg.vys4y"},
     
     {"title": "Australia", "text": "Is the South Australian model worth emulating? It certainly creates a lot of work and the mutual complaint culture reminds us that structural solutions can struggle to fix cultural problems. Practically speaking, scaling from elections with dozens of seats to hundreds would multiply the work considerably. However the low rate of actual prosecutions should be seen as a sign of success. If the goal of the law is to reduce the number of false statements, claims being submitted every day of an election and passing what is a fairly expansive view of &amp;#8216;fact&#39; seems like a good outcome. ", "tags": "", "url": "index.html#4.2161.cyur-.1bdrg.ss51f.bflzw"},
     
     {"title": "New Zealand", "text": "New Zealand has a similar but more restricted law on the books.  In 2002 Section 199a was added to the Electoral Act 1993. This provision kicks in two days before the election and theoretically creates a disincentive to pollute the debate at the last minute when there is no time to respond:", "tags": "", "url": "index.html#new-zealand"},
     
     {"title": "New Zealand", "text": "199(a) Every person is guilty of a corrupt practice who, with the intention of influencing the vote of any elector, at any time on polling day before the close of the poll, or at any time on any of the 2 days immediately preceding polling day, publishes, distributes, broadcasts, or exhibits, or causes to be published, distributed, broadcast, or exhibited, in or in view of any public place a statement of fact that the person knows is false in a material particular.^*", "tags": "", "url": "index.html#4.7065.mckfr.zmlni.axyg1.tz_vw"},
     
     {"title": "New Zealand", "text": "For a sense of the political context it&#39;s worth noting that there was originally a companion to this amendment that created a criminal libel standard throughout the entire campaign, but that was removed after opposition in the media and from parliament. There was also opposition voiced against  the two day rule - Warren Kyd of the National Party argued:", "tags": "", "url": "index.html#4.7610.hcmqw.ympvh.sc4yq.vsuxc"},
     
     {"title": "New Zealand", "text": "If a person says his or her party will increase pensions, spend more on education, and reduce tax - a statement that is clearly pretty exaggerated, but does occur at election time - does that mean that he or she could be guilty of a corrupt practice and lose his or her seat? ... If one went to the court, one could presumably upset an election, and a member could lose his or her seat as a result of exaggerating, or singing the bull a bit, when electioneering.", "tags": "", "url": "index.html#4.6398.awgqx.qsezy.t2bvz.ktf6x"},
     
     {"title": "New Zealand", "text": "That this provision has never been invoked isn&#39;t a huge surprise, given that the Secretary of Justice told the Select Committee investigating the bill that prosecutors and the courts would be reluctant to get involved in political controversy by pursuing prosecutions.^*", "tags": "", "url": "index.html#4.49.tr_nb.99ewt.9ax1e.2vhec"},
     
     {"title": "New Zealand", "text": "As the provision was directed explicitly against New Zealand First, it&#39;s ironic that the scope of future action may have been increased by a recent decision in favour of NZ First leader Winston Peters. ", "tags": "", "url": "index.html#4.6965.nhsjg.re3zz.kfguy.alj9g"},
     
     {"title": "New Zealand", "text": "STEPHEN FRANKS (ACT NZ): I looked back at some other information we had, and realised that the New Zealand First tactic of deliberately raising contentious or unsubstantiated issues immediately before an election was a pernicious practice.^*", "tags": "", "url": "index.html#4.721.fguw6.1nxs6.tmnqn.ilr55"},
     
     {"title": "New Zealand", "text": "Peters challenged the Electoral Commission&#39;s decision not to refer two advertisements he believed violated 119a to the police - one of which (a Conservative Party pamphlet) had previously been held by New Zealand&#39;s Advertising Standards Authority to contain &quot;&quot;a substantive error of fact&quot;&quot;. While the ASA instructed that the ad should be changed (we&#39;ll get onto the role the NZ ASA play in political advertisements later), the original pamphlet remained unaltered on the Conservative Party website. The Electoral Commission argued that:", "tags": "", "url": "index.html#4.8173.kfw8h.lqvdx.ywtjb._-j2p"},
     
     {"title": "New Zealand", "text": "In the Electoral Commission&#39;s view, putting aside whether or not the other elements of the offence were made out, section 199A of the Act does not apply to the items at issue because they were not first published within the required time period.^0", "tags": "", "url": "index.html#4.7306.yqy8j.1a_bp.8700z.nad4g"},
     
     {"title": "New Zealand", "text": "Peters&#39; representative argued in response that material published on a website is not &quot;published&quot; at the time of upload, but &quot;published&quot; whenever it is accessed - and the judge agreed with this interpretation. This case did not lead to action with regard to the materials in question, but did establish a principle that the law might (and there seems to be wiggle room given an actual case) apply to any materials that remain accessible, rather than any simply released in the last few days. At the very least, the Electoral Commission are more likely now to refer complaints in the window to the police - raising the probability the law will actually be tested.", "tags": "", "url": "index.html#4.4170.lneqf.t4idk.fiqua.hbwey"},
     
     {"title": "New Zealand", "text": "The principle that the period immediately prior to an election deserves a backstop seems reasonable enough (the worst you can really say is &quot;why bother?&quot;) but from a UK perspective it seems strange that it exists at all. There is a wider cultural aspect to consider and it turns out that both Australia and New Zealand have a very different history of private regulation of electoral advertising. This might explain why the UK is awkwardly dealing with Victorian-era legislation while Australia and New Zealand have experimented with the issue in recent decades. The idea that electoral advertising can be regulated is, while definitely not universally accepted, part of the conversation around elections in these countries in a way it just isn&#39;t in the UK.", "tags": "", "url": "index.html#4.2631.938dy.uq1iz.iqyqg.echks"},
     
     
     
     {"title": "Private Regulation", "text": "Many countries have codes of practices for advertising and organisations that mediate disputes to keep problems out of the courts and prevent the need for a government enforcement agency. In the UK commercial advertising is regulated by Ofcom for broadcast and the Advertising Standards Authority (ASA) for other forms of advertising.", "tags": "", "url": "index.html#5.6788.81i_c.owfcj.bv9z0.iaub9"},
     
     {"title": "Private Regulation", "text": "While some of their counterparts in other countries have a truth checking duty for political advertising, this has never been the case in the UK. The ASA has had greater involvement in political advertising in the past &amp;#8212; up until 1999 political advertisements existed in a halfway house where the ASA protected personal character but did not hold political to the same criteria on accuracy (mirroring the legal distinction). After 1999 the ASA moved away from this, leading to the current situation where no one has the authority to judge the content of election adverts at all.", "tags": "", "url": "index.html#5.4130.-vy0g.vqwtt.govkw.sszio"},
     
     {"title": "Private Regulation", "text": "The spark that led to the change came in 1996, when the ASA ruled against a Conservative Party advert. The ad was part of the Conservatives&#39; &quot;New Labour, New Danger&quot; campaign and featured Labour leader Tony Blair with a pair of red demonic eyes. It received 167 complaints and the ASA asked for the advert not be used again, finding that:", "tags": "", "url": "index.html#5.5758.7qzvd.2n8qn.njp7f.04-vl"},
     
     {"title": "Private Regulation", "text": "Although it did not consider that readers in general would think the advertisement attributed satanic qualities to Tony Blair, the Authority reminded the advertisers that the Codes prohibited the portrayal, without permission, of politicians in an adverse or offensive way. Because it considered that the advertisement depicted Tony Blair as sinister and dishonest, the Authority asked for it not to be used again.^1", "tags": "", "url": "index.html#5.3340.ff2k_.ss3jv.vhmi1.yopmy"},
     
     {"title": "Private Regulation", "text": "The full finding is no longer avaliable online, reproduced below:", "tags": "", "url": "index.html#5.6154.q11hb.jz7yu.n0ual.krqpy"},
     
     {"title": "Private Regulation", "text": "The fallout from failures of complaints by other parties after Demon Eyes led to the Committee of Advertising Practice (CAP) wanting to end the halfway house arrangement one way or the other. With no clear agreement among political parties on if the ASA should continue in its current role, they opted in favour of staying out of political disputes as &quot;&quot;we are an unelected body and have no desire to become involved in the democratic process&quot;&quot;.^* It was not their core mission and it was an awkwardness they could avoid. When the code was next revised it introduced a provision to close the issue. The relevant section of the code now reads:", "tags": "", "url": "index.html#5.9531.aszno.4cqeh.3dk1a.nrgwt"},
     
     {"title": "Private Regulation", "text": "7.1 Claims in marketing communications, whenever published or distributed, whose principal function is to influence voters in a local, regional, national or international election or referendum are exempt from the Code.^0", "tags": "", "url": "index.html#5.9700.zfmu_.5vyqw.anjrr.hmqiv"},
     
     {"title": "Private Regulation", "text": "But the expectation was never that this would be the end of the matter. The CAP suggested that the regulation of party adverts should continue - but not by them. The baton was taken up by the Neill Report who advised that the &quot;&quot;political parties should seek to agree, in association with the advertising industry, a code of best practice for political advertising in the non-broadcast media&quot;&quot;.^1 After investigating the matter the Electoral Commission found the prospects for any self-regulation scheme to be dismal. While the Liberal Democrats were in support of a code, Labour failed to respond to the consultation and the Conservatives&#39; statement put it bluntly:", "tags": "", "url": "index.html#5.647.oybuz.8whyl.bwyd3.mqbil"},
     
     {"title": "Private Regulation", "text": "In the context of the Conservative Party being the largest party of local government in Britain and the Official Opposition in Parliament, it would not be viable for a voluntary code to exist without our participation and cross-party consent. As a result, we respectfully submit to the Commission that any proposals for a voluntary code are not workable.^*", "tags": "", "url": "index.html#5.5901.nfwdd.rolns.4ygrr.ygxho"},
     
     {"title": "Private Regulation", "text": "This quote sits alone on the last page of the report before the Commission&#39;s own conclusions - the logic is undeniable. The Commission concluded that &quot;&quot;having considered again the case for a code, it is clear that the difficulties of implementing any such code mean that, to all intents and purposes, it would be impractical&quot;&quot;.^*", "tags": "", "url": "index.html#5.9566.fkyty.so8sw.rdowh.zcrc_"},
     
     {"title": "Private Regulation", "text": "We have to be aware of a bit of institutional self-interest in this conclusion. If the ASA wasn&#39;t interested in the responsibility, then the most viable candidate for role was the Electoral Commission. In fact the ASA (and a few others) suggested as much in their responses:", "tags": "", "url": "index.html#5.9351.bbvgs.y2yr8.k92vt.rlnd_"},
     
     {"title": "Private Regulation", "text": "It is hard to see who other than the Electoral Commission itself would be in a position to adjudicate on breaches of any code for election advertising.^*", "tags": "", "url": "index.html#5.5606.76bb-.zm36j.-tgqf.nv3gn"},
     
     {"title": "Private Regulation", "text": "And (for the same reasons as the ASA) the Electoral Commission really didn&#39;t want to get involved:", "tags": "", "url": "index.html#5.2998.l-298.yqlcc.gqpf8.jh_lt"},
     
     {"title": "Private Regulation", "text": "We do not consider that it would be appropriate for the Commission to be the arbiter for disputes relating to political advertising. This is principally because of the risk that the Commission&#39;s independence might be compromised or be perceived to be compromised by such a role. To have to adjudicate on controversial advertising within the heat of an electoral campaign, probably within a very short timeframe, has inherent dangers which it could not accept given the fundamental importance for the Commission of maintaining strict impartiality in all of its areas of work.^1&amp;#8230; It is not a role that The Electoral Commission would be prepared to assume.^2", "tags": "", "url": "index.html#5.4852.ycws6.3fmkj.6k0d1.yph4b"},
     
     {"title": "Private Regulation", "text": "In fact, the Electoral Commission repeated this argument after the AV referendum:", "tags": "", "url": "index.html#5.3174.gvpwp.cwntp.hgahn.2aj1w"},
     
     {"title": "Private Regulation", "text": "We do not think that any role in policing the truthfulness of referendum campaign arguments would be appropriate for the Commission. It would be very likely to draw the Commission into political debate, significantly affecting the perception of our independent role, and posing substantial operational and reputational risks. We therefore invite the Government and Parliament to confirm that a role of this nature would be inappropriate for the Commission. ^1", "tags": "", "url": "index.html#5.2708.vn8o0.3fmkj.hxruz.ee-ga"},
     
     {"title": "Private Regulation", "text": "The Electoral Commission seem unaware of the practice in South Australia (indeed, the report relies on what turns out to be an incorrect study saying there is no regulation abroad). But if they should ever discover their antipodal counterparts,  the first order of business would probably be to send someone to pick up the horror stories. They really don&#39;t want anything to do with this.", "tags": "", "url": "index.html#5.9111.de0pk.0nhu0.rsrbo.pi7pp"},
     
     {"title": "The International Picture", "text": "In Australia broadcast adverts used to be judged for accuracy by the Federation of Australian Commercial Television Stations (FACTS). This required campaigns &quot;&quot;to provide sheaves of material proving their claims&quot;&quot;.^0 In one example the Liberal Party successfully argued that FACTS should not show a Labor Party advert that talked about the &quot;last chance&quot; to save Telstra (a publicly-owned telecommunication company) from privatisation because &quot;&quot;it was impossible to say whether or not it was in fact the last chance to save Telstra&quot;&quot;.^2 This was a strong standard.", "tags": "", "url": "index.html#the-international-picture"},
     
     {"title": "The International Picture", "text": "However FACTS&#39; interventions here turned out to be based on a mistaken interpretation of a Trade Practice Act - they were never supposed to be judging political adverts and everyone involved had put up with this for essentially no reason. As such FACTS stopped judging political ads in 2002.^1", "tags": "", "url": "index.html#5.3709._ntbz._l13y.59jbe.yirio"},
     
     {"title": "The International Picture", "text": "In New Zealand both the Broadcast Standards Authority (BSA) and Advertising Standards Authority (ASA) have rules about political accuracy. These recognise that judging election adverts is hard and leeway has to be given to avoid undue interference in the political process. The BSA&#39;s Election Code of Broadcasting Practice allows that:", "tags": "", "url": "index.html#5.2755.88_j9.hqoe7.xndsx.4flc8"},
     
     {"title": "The International Picture", "text": "In recognition of the special context of general elections, broadcasting standards such as fairness and accuracy will be applied to election programmes in a manner that respects the importance of free political expression and debate.^*", "tags": "", "url": "index.html#5.1146.i2e4h.azdzk.sq5lb.covhe"},
     
     {"title": "The International Picture", "text": "The BSA say that they &quot;&quot;get comparatively few complaints about election programmes, and even fewer are upheld&quot;&quot; and volunteered eight complaints during the 2011 election of which none were upheld.^1", "tags": "", "url": "index.html#5.7045.7bqoa.ek_l1.18pxq.bl-sx"},
     
     {"title": "The International Picture", "text": "The NZ Advertising Standards Authority (ASA) similarly deal with complaints about political advertising. False statements are covered under Rule 2:", "tags": "", "url": "index.html#5.9764.89kr_.jrgxr.ziqqb.a3prw"},
     
     {"title": "The International Picture", "text": "Truthful Presentation - Advertisements should not contain any statement or visual presentation or create an overall impression which directly or by implication, omission, ambiguity or exaggerated claim is misleading or deceptive, is likely to deceive or mislead the consumer, makes false and misleading representation, abuses the trust of the consumer or exploits his/her lack of experience or knowledge. (Obvious hyperbole, identifiable as such, is not considered to be misleading).^*", "tags": "", "url": "index.html#5.9126.nks9b.qkecc.ddwej.zidqk"},
     
     {"title": "The International Picture", "text": "With rule 11 of the Code of Ethics giving protection to expression of opinion in advocacy advertising:", "tags": "", "url": "index.html#5.8915.zi8pr.jbvas.bv9z0.s-cob"},
     
     {"title": "The International Picture", "text": "Expression of opinion in advocacy advertising is an essential and desirable part of the functioning of a democratic society. Therefore such opinions may be robust. However, opinion should be clearly distinguishable from factual information. The identity of an advertiser in matters of public interest or political issue should be clear.^*", "tags": "", "url": "index.html#5.650.1iofa.i0zuu.mas4a.jqw-2"},
     
     {"title": "The International Picture", "text": "Rule 11 is interpreted through advocacy principles to encourage liberal interpretation of the rules for political advertising - reflecting the idea that this an area where caution is needed.^* But how does this work out in practice?", "tags": "", "url": "index.html#5.7216.tasi1.73wce.dffs-.9uhyz"},
     
     {"title": "The International Picture", "text": "In the 2008 election three complaints were upheld. The first was an issue about false claims about rival parties. A leaflet for the ACT party claiming to be the only party &quot;&quot;totally opposed to an&quot;&quot; Emissions Trading Scheme was delivered to a candidate for the Family Party, who also claim that policy. ACT&#39;s response was to argue that the Family Party would not gain any seats and that the &quot;&quot;ACT Party is the only party that voted against the passing of the bill in parliament and will be the only party elected to parliament after the election that will oppose it.&quot;&quot; The complaint was upheld (with a minority agreeing with ACT that in terms of the practicality of NZ elections they were the &quot;only&quot; party).^1 This parallels nicely with the 2015 UK election where the Greens and UKIP both insisted they were the only party to oppose HS2 - such claims would run into problems in New Zealand.^2", "tags": "", "url": "index.html#5.5634.bql3x.3qium.1dcyh.rkr1f"},
     
     {"title": "The International Picture", "text": "The second upheld complaint was a technical issue concerning the accuracy of a Labour advert accusing Prime Minister John Key of planning to cut KiwiSaver (a savings scheme) in half. The ASA found that he was only halving minimum contributions (and that employee and employer could &quot;&quot;elect to contribute more&quot;&quot;) so the advertisement was misleading as to actual National Party policy. The complainant argued in their appeal that the employer tax exemption would be capped at the new minimum,so as a practical reality continued higher employer contributions seemed unlikely. But &quot;likely result of policy&quot; was not considered to be the same thing as &quot;policy&quot;.^*", "tags": "", "url": "index.html#5.1532.4rtcc.vs5l0.p0rvc.env1t"},
     
     {"title": "The International Picture", "text": "The third upheld complaint was an argument about whether saying &#39;&quot;Safe&quot; New Zealand is now almost three times more violent than the US!&#39; was an accurate statement. While neither complainant nor advertiser provided any statistical evidence to either prove or reject the claim, the ASA decided that the onus to prove the claim rested with the advertiser and upheld the complaint.^*", "tags": "", "url": "index.html#5.8641.dfgcb.ob6fp._lrm_.q5dbl"},
     
     {"title": "The International Picture", "text": "If we look at a rejected complaint we can see that campaigners have a ready understanding of the phrase &quot;technically correct&quot;. This complaint involved a letter that contrasted Winston Peters (leader of the New Zealand First Party) with the Conservative Party, and the complaint argued that Peters stance on smacking was being misrepresented. The letter pushed opposition to an &quot;&quot;anti-smacking Law&quot;&quot; as a point of difference between the two parties as it was &quot;&quot;one of Winston&#39;s own MPs that first proposed an anti-smacking law and a majority of Winston&#39;s party voted for Sue Bradford&#39;s anti-smacking legislation&quot;&quot;. Winston Peters actually voted against the law - but the substance of fact is technically correct and the ASA rejected that aspect of the complaint.^* Looking at the UK&#39;s 2011 AV referendum, Renwick and Lamb found that &quot;&quot;politicians and campaigners on both sides became adept at producing statements that were strictly speaking correct, nevertheless likely to mislead&quot;&quot;^1 - in all elections there are plenty of electoral claims that are deliberately misleading but might escape a factual monitor unscathed. ", "tags": "", "url": "index.html#5.62.qxdix.xympn.yj9wi.sxcmv"},
     
     {"title": "The International Picture", "text": "In coverage of New Zealand&#39;s referendums we can find an example of where the ASA&#39;s liberal advocacy rules win out over strict technical correctness. In the 2011 referendum on whether to retain the mixed member proportional representation (MMP) voting system, a complaint about the anti-MMP campaign&#39;s statement that &quot;&quot;Minor parties decide who is the PM&quot;&quot; was found to be acceptable (it being likely but not necessarily true) &quot;&quot;taking into account the provision for robust advocacy advertising&quot;&quot;.^*", "tags": "", "url": "index.html#5.2086.xowqt.r8pqa.1tmj7.jcyu4"},
     
     {"title": "The International Picture", "text": "On the same complaint the Electoral Commission interestingly tried to intervene (under the aegis of the education role they&#39;d been given) to ban the ad on the grounds it was moving the debate on to issues unrelated to the campaign (number of MPs in Parliament) - this was understandably resisted by Vote for Change (anti-MMP) as the Electoral Commission had no real standing to intervene.", "tags": "", "url": "index.html#5.5102.srm3p.vblsn.duoqp.jenek"},
     
     {"title": "The International Picture", "text": "Of course the existence of such a system attracts petty complaints, during the 2016 flag referendum the ASA received a complaint that &#39;the image of the Union Jack on the existing flag was &quot;graphically altered to be less attractive&quot; and was smaller than the proposed flag&#39;^1 and another that an ad &quot;&quot;went against the democratic process by using celebrities to advocate for a change&quot;&quot;.^2", "tags": "", "url": "index.html#5.2004.ekney.8zp7x.qrysq.pwbqi"},
     
     {"title": "The International Picture", "text": "But trivial complaints are the price for the ability to intervene on valid ones. In a local referendum about fluoridation of the drinking water a sigh that stated &quot;&quot;Why drink toxic waste when you can brush your teeth? Fluoride OUT&quot;&quot; was ruled as unacceptable as:", "tags": "", "url": "index.html#5.6699.yridv.dmte7.fs46c.e-6tk"},
     
     {"title": "The International Picture", "text": "It implied fluoridated water as toxic which went beyond the provision of robust opinion allowed for under the rules of advocacy advertising. The Complaints Board said the advertisement presented an opinion as a statement of fact in manner that was likely to exploit consumers&#39; lack of knowledge and had unjustifiably played on fear.^1", "tags": "", "url": "index.html#5.4953.3gknk.wyt6u.tpdos.isrpr"},
     
     {"title": "The International Picture", "text": "From the New Zealand experience of an ASA that intervenes in political advertising we can see that the task isn&#39;t inherently impossible - but neither does it automatically create a perfect environment of political truth. Sufficiently crafty campaigns have plenty of room for sleights of hand that refrain from outright fabrication. That said, neither is it pointless: claims can and do run into trouble, and are barred from further display.", "tags": "", "url": "index.html#5.4420.vwv_d.0gki-.7qkph.epek8"},
     
     
     
     {"title": "Practicalities", "text": "We&#39;ve seen that regulating political advertisement isn&#39;t inherently impossible and working examples exist. But are there reasons unique to the UK&#39;s political context that mean a stronger system couldn&#39;t be used here?", "tags": "", "url": "index.html#6.9271.iu-6w.auxvg.e1n_j.30q2r"},
     
     {"title": "Fact vs Opinion", "text": "While respecting the high priority the Electoral Commission places on its political impartiality, we can also see that their arguments are risk-adverse towards this end. Their case that regulation is flat-out impossible is a suspect given working systems elsewhere. ", "tags": "", "url": "index.html#fact-vs-opinion"},
     
     {"title": "Fact vs Opinion", "text": "For instance, one argument made in their 2004 report is that the whole idea is impractical because political claims are too subjective:", "tags": "", "url": "index.html#6.1282.a0i3y.or60c.9ipsh.dm_hw"},
     
     {"title": "Fact vs Opinion", "text": "It would seem inappropriate and impractical to seek to control misleading or untruthful advertising, given the often subjective nature of political claims.^*", "tags": "", "url": "index.html#6.7712.yih6y.xaszk.nmu8o.-ezs8"},
     
     {"title": "Fact vs Opinion", "text": "This is special pleading for the uniqueness of political advertising. As the CAP argued in their submission, &quot;&quot;all advertising involves subjectivity and ... political advertising is not a special case in this regard&quot;&quot;.^1 In reality a great deal of factual claims can be isolated from opinion and judged separately.", "tags": "", "url": "index.html#6.8566.qiavq.vffwe.cgye_.2u3fp"},
     
     {"title": "Fact vs Opinion", "text": "We can see this in a system already in place in the UK. Adverts about petitions can be political but not related to elections or referendums - and as such the ASA can, and does, make rulings about them. This gives us some idea as to what a world in which the ASA judged election ads would look like.", "tags": "", "url": "index.html#6.6021.7jeqy.qfjw3.2pkye.mnhu6"},
     
     {"title": "Fact vs Opinion", "text": "One advert taken out by &amp;#8216;Coalition For Marriage Ltd&#39; is especially interesting. This ad asked people to sign a petition &quot;&quot;in favour of keeping the definition of marriage unchanged&quot;&quot; - with the fact that &quot;&quot;70% of people say keep marriage as it is. Source: ComRes poll for Catholic Voices&quot;&quot;. The ASA didn&#39;t uphold a complaint about this statistic and went into detail as to why it didn&#39;t find the &quot;&quot;70%&quot;&quot; figure misleading - finding it was an accurate summary of the poll the advert cited. This represents a limited but practical judgement of a fairly typical kind of political claim.^* ", "tags": "", "url": "index.html#6.600.cqgch.rcokf.nkhyv.au-yv"},
     
     {"title": "Fact vs Opinion", "text": "In another adjudication involving a &amp;#8216;Restore Justice Campaign&#39; the ASA upheld a complaint about an online banner stating &quot;&quot;IN 1964 MPS ABOLISHED HANGING&quot;&quot; on frame 1, &quot;&quot;THE MURDER RATE HAS DOUBLED&quot;&quot; on frame 2 and &quot;&quot;SIGN THE HM Government Directgov E-PETITION&quot;&quot; on frame 3.", "tags": "", "url": "index.html#6.107.gqokx.eb9rf.n0whj.gtnz9"},
     
     {"title": "Fact vs Opinion", "text": "The complainant raised two issues: a) the statistic that the murder rate had doubled, and b) the implication that abolishing hanging had caused the rise. The ASA upheld the first complaint but not the second - demonstrating that it was able to distinguish between factual content and opinion.^* Political advertising is already dealt with in the UK - just on a very limited scale.", "tags": "", "url": "index.html#6.5251.pqqmw.rvdkv.trpf3.t9cha"},
     
     {"title": "Human Rights", "text": "One of the reasons the CAP gave for avoiding regulation of political advertising was the implementation of the Human Rights Act in 1998. However as a result of cases decided since then there is good reason to believe this isn&#39;t a barrier to all interventions.", "tags": "", "url": "index.html#human-rights"},
     
     {"title": "Human Rights", "text": "Part of Phil Woolas&#39; defence was to refer to his right under the European Convention of Human Rights ECHR to free expression. The Election Court held that there was no right to false statements if that undermined the right to free elections, quoting the 1911 North Lough case&#39;s interpretation of the law:", "tags": "", "url": "index.html#6.2554.eob5m.1dy2n.sw-kx.gbror"},
     
     {"title": "Human Rights", "text": "The primary protection of this statute was the protection of the constituency against acts which would be fatal to freedom of election. There would be no true freedom of election, no real expression of the opinion of the constituency, if votes were given in consequence of the dissemination of a false statement as to the personal character or conduct of a candidate...^*", "tags": "", "url": "index.html#6.8149.tsxcb.fjaey.rcg7g.chm8w"},
     
     {"title": "Human Rights", "text": "In their judicial review the Divisional Court specifically prioritised the ECHR rights of voters over Woolas&#39; Article 10 rights:", "tags": "", "url": "index.html#6.9185.dg2s0.0gr46.f_hur.shcmw"},
     
     {"title": "Human Rights", "text": "Dishonest statements are aimed at the destruction of the rights of the public to free elections (Article 3 of the First Protocol) and the right of each candidate to his reputation (Article 8 (1)). Article 10 does not protect a right to publish statements which the publisher knows to be false.^*", "tags": "", "url": "index.html#6.8742.za9jc.radbn.3hngt.l6pai"},
     
     {"title": "Human Rights", "text": "This argument relies on Article 17, which is designed to prevent one right being used towards the &quot;&quot;destruction&quot;&quot; of another. Jacob Rowbottom argues that this approach might be a bit extreme (effectively placing &quot;&quot;dishonest speech alongside holocaust denial and neo-Nazi speech&quot;&quot;) and instead argues that the restrictions in section 2 of Article 10 are sufficient in themselves to justify interventions against misleading speech.^* But either way:", "tags": "", "url": "index.html#6.8479.ueqv7.od4ky.idoeh.4mljh"},
     
     {"title": "Human Rights", "text": "The position of the British courts appears to give the legislature considerable power to restrict dishonest statements in elections without falling foul of Article 10.^*", "tags": "", "url": "index.html#6.7783.qncpr.0aaiy.0yz1v.y91hw"},
     
     {"title": "Human Rights", "text": "As we saw earlier the ECHR did make the court nervous about too expansive a view of the existing law, but it shouldn&#39;t be taken as a given that the ECHR inherently empowers candidates or campaigners to overcome any restraints of law. British systems are still perfectly capable of making this decision - if there was the will to do so.", "tags": "", "url": "index.html#6.3668.csfle.y-q-v.xjntj.w3pb0"},
     
     {"title": "Speed", "text": "Another argument made is that there are special time pressures involved in political advertising that make judgements impossible. This, again, is politicians arguing that their business is a special case when a great amount of political adverts could be dealt with at the pace everyone else works to. The last successful political ASA complaint (Demon Eyes) was made a year before the next general election. In the AV referendum the contested &amp;#163;250 million figure was first introduced in February before a May vote. There&#39;s nothing inherently unworkable about dealing with these kinds of claims well before the vote.", "tags": "", "url": "index.html#speed"},
     
     {"title": "Speed", "text": "But what about a matter in the last weeks of the campaign? How could those possibly be dealt with in time? The New Zealand ASA has a cunning solution to this problem: they just do it quicker. On complaints made in the run-up to an election the following procedure is used:", "tags": "", "url": "index.html#6.4872.pgdmn._-bu7.mf4pv.k4eww"},
     
     {"title": "Speed", "text": "The Chairman also ruled that the matter be dealt with immediately, as the General Election was pending. Accordingly, an urgent Complaints Board meeting was called, and the Advertiser given approximately 24 hours in which to respond.^*", "tags": "", "url": "index.html#6.534.mpva8.-9nbk.p0k8k.qlvmu"},
     
     {"title": "Speed", "text": "In South Australia the Electoral Commission similarly tries to resolve the issue quickly:", "tags": "", "url": "index.html#6.6177.berxc.16zi_.1oeu5.glcxz"},
     
     {"title": "Speed", "text": "ECSA aims to resolve most issues within 3&amp;#8211;4 days. In cases where conflicting evidence and counter submissions occur, matters may take some 1&amp;#8211;2 weeks to resolve. Where there is the likelihood of prosecution action, this may extend the resolution for some months.^*", "tags": "", "url": "index.html#6.8228.x_nrp.z8ul7.f_k13.4vhzf"},
     
     {"title": "Speed", "text": "Towards the very end you could certainly argue there&#39;s not much point doing anything at all (what&#39;s the value of restraining an advert with only days to go?) but this special time pressure applies to a very small part of the campaign. That some adverts might not be able to be judged in time does not mean that regulating political advertising three months or a year beforehand is pointless. A false claim repeated for an entire year before an election is arguably more of a problem than one made at the very last minute. After all, they wouldn&#39;t let them keep saying it if it wasn&#39;t true.", "tags": "", "url": "index.html#6.2587.fxhrx.5jpxn.qpoic.w1tok"},
     
     {"title": "Trust the People", "text": "An idea that keeps coming up is the notion that we already have a body in place to judge if claims are true: the electorate. As we have seen the courts argue that voters are miraculously more able to judge misleading claims about politics than they are about people. Similarly the Conservative Party argued in their submission to the Electoral Commission that &quot;&quot;if electors are unhappy with the tone of political advertising they are well placed to voice that disapproval and withdraw their support for any political party engaging in such behaviour. In this context, self regulation already exists&quot;&quot;.^1", "tags": "", "url": "index.html#trust-the-people"},
     
     {"title": "Trust the People", "text": "However, as an Australian report on political advertising pointed out, this is a historically familiar argument and it was &quot;&quot;once also alleged that the market would operate to allow consumers to ascertain the truth about products&quot;&quot;.^1 If the public truly are the best judge of the veracity of claims, we should ask not just whether an ASA-like body should police political claims, but whether the ASA should exist at all. It&#39;s one thing to argue that there are no suitable judges for the democratic process - quite another that the electorate are especially well-placed to do the role.", "tags": "", "url": "index.html#6.4246.chfjp.slkva.ixbvn.s_x_h"},
     
     {"title": "Trust the People", "text": "Defending a ban on broadcast political advertising, Lord Bingham argued that the playing field should be level in terms of what arguments were present, but that working out which argument was best should be left to the public:", "tags": "", "url": "index.html#6.6983.rzsas.k4zew.ufadg.iqbu5"},
     
     {"title": "Trust the People", "text": "The fundamental rationale of the democratic process is that if competing views, opinions and policies are publicly debated and exposed to public scrutiny the good will over time drive out the bad and the true prevail over the false. It must be assumed that, given time, the public will make a sound choice when, in the course of the democratic process, it has the right to choose. But it is highly desirable that the playing field of debate should be so far as practicable level. This is achieved where, in public discussion, differing views are expressed, contradicted, answered and debated. ^1", "tags": "", "url": "index.html#6.3539.jp5jy.mzohc.1lx6w.u4enx"},
     
     {"title": "Trust the People", "text": "The underlying idea is that bad information, whether maliciously or innocently entered into the debate, can be corrected with good information. In an active and vigorous political culture, lies will be punished and truth will rise to the top.", "tags": "", "url": "index.html#6.4250.3vsxr.kd7uq.egbon.tgb5f"},
     
     {"title": "Trust the People", "text": "There is a growing body of evidence that the electorate is not at all good at replacing incorrect facts with correct ones. In the 2016 EU referendum Ipsos MORI found that the public were &quot;&quot;more often very wrong on some of the key issues fundamental to the debate&quot;&quot;.^* Was this a failure of the campaigns? Perhaps, but correcting misinformation people have learned is incredibly difficult. Once someone has learned a piece of information, it appears that information is both hard to remove and attempts to do so can reinforce the initial incorrect knowledge. When you set out to debunk something there is a real risk of making the situation worse.", "tags": "", "url": "index.html#6.6974.llxdt.tno--.cjdel.qao8t"},
     
     {"title": "Trust the People", "text": "While a person may initially seem to understand that a fact is false after being exposed to counter-information, given time the knowledge that the fact is false will decay and the initial fact is reinforced. For example a standard &quot;&quot;Facts &amp; Myths&quot;&quot; flyer on vaccinations had an incredibly short period of effectiveness - after just 30 minutes the flyer had impaired &quot;&quot;participants&#39; attitudes towards vaccination intentions, relative to controls who read no flyer at all.&quot;&quot; ^1", "tags": "", "url": "index.html#6.9647.ekujk.dqhln.zcmpc.irr3e"},
     
     {"title": "Trust the People", "text": "Studies examining &quot;adwatches&quot; (Segments on US news programmes checking the factuality of political adverts) similarly found that &quot;&quot;the effects of the adwatches on interpretation of the ad seem to decay quickly. Accuracy in interpretation of the ad drops off as time elapses between the adwatch and the posttest&quot;&quot;. Importantly this isn&#39;t just a case of the adwatch being forgotten as &quot;&quot;people remembered what the adwatch said and retained its attitudinal implications but not the inferences they were supposed to draw&quot;&quot;.^2", "tags": "", "url": "index.html#6.3876.asdi1.--95w.zwnab.wp2p2"},
     
     {"title": "Trust the People", "text": "This is all on the face of it a bit fatal to our idea that public discourse can be an effective sorter for truth. Political information runs into further hurdles as a person accepting or rejecting information can depend on their existing partisan allegiance - statements &quot;&quot;from an unlikely source can ... increase citizens&#39; willingness to reject reject rumors, regardless of their own political predilections&quot;&quot;^1. In the the US health care debate, addressing the &quot;death panel&quot; rumour with a counterargument posed by a Republican politician increased the rates it was rejected by both Republicans and Democrats.^2", "tags": "", "url": "index.html#6.5839.slbky.5yvmy.8pmwh.xlfdq"},
     
     {"title": "Trust the People", "text": "So while it is possible to make some headway against an untrue claim, if the original untrue claim is going to be repeated over and over again any fact check is going to lose its effectiveness.  Claim and rebuttal is an asymmetric game - to maintain a level playing field in spite of this requires a robust referee. ", "tags": "", "url": "index.html#6.4015.fgmsd.pduw4.9ohxi.znqqp"},
     
     {"title": "Trust the People", "text": "This brings us back to the unavoidable practical problem - no one wants the job. The courts police a strange subset of complaints. The ASA is a private body who would rather not get involved in elections. The Electoral Commission is a public body who want to avoid the perception of bias. Ultimately this all comes back to Parliament, unless MPs either legislate or create a code of self-regulation no one is willing to intercede further.", "tags": "", "url": "index.html#6.9714.vkvum.jndbn.g35_m.r_c6a"},
     
     
     
     {"title": "Where does this leave us?", "text": "While the problem of getting people who don&#39;t want to be regulated to agree to be regulated remains, there is slow cultural change on this issue. The Woolas trial seems to have had some effect on how candidates engage with each other - in the 2015 campaign, &quot;&quot;what you are saying is not true&quot;&quot; has on several occasions crossed into &quot;&quot;and I will make you stop saying it.&quot;&quot;", "tags": "", "url": "index.html#where-does-this-leave-us"},
     
     {"title": "Where does this leave us?", "text": "In addition to the action taken against Alastair Carmicheal, there have been a number of lower-level complaints. The Lib Dem Greg Mulholland successfully got his opponent to print 15,000 apology leaflets retracting a claim that Mulholland had voted for academy school legislation.^1 In Cambridge, the Conservative candidate Chamali Fernando threatened her opponent with libel action over what he claimed she said at a hustings (with the additional threat of a s.106 action).^2 Nigel Farage even tried to argue that a journalist&#39;s comment on the BBC&#39;s comedy panel show Have I Got News For You was an untrue statement that attacked his character.^3", "tags": "", "url": "index.html#7.7024.qclbv.ydxdp.hwf6q.p4yhu"},
     
     {"title": "Where does this leave us?", "text": "Election courts are not particularly good ways of redressing these grievances. They&#39;re expensive to pursue, focused on a narrow area of truth, and the outcome is severe. The Carmichael petition may have failed to unseat an MP, but it did broaden the understood scope of the law and uphold the procedure&#39;s existence as more than just a curiosity.  The more elections are accompanied by petitions, the more likely they are to become a regular feature - and prospects for either making election courts less objectionable or less required should appear. In their interim report on reforming electoral law, the Law Commission have recommended legislation allowing courts to be able to make protective cost orders so that individuals who bring petitions &quot;&quot;should be heard in the public interest and should not risk financial ruin when doing so&quot;&quot;.^1 However, while the consultation addressed the law concerning false statements, no questions were posed on its wider reform as this would be a more substantial change than a legal tidy-up.^2", "tags": "", "url": "index.html#7.3353.f5ndy.razjd.gnuyf.tzbc4"},
     
     {"title": "The Options", "text": "We can roughly divide possible paths into the legalistic Australian approach or a New Zealand-esque system of self-regulation. The Australian approach would be an expansion of current law to encompass political misleading statements, but would also introduce a proportionality requirement with regards to whether the statements in question could actually have affected the election. This could also be designed to allow challenges to election material without involving the courts by empowering the Electoral Commission to make initial judgements.", "tags": "", "url": "index.html#the-options"},
     
     {"title": "The Options", "text": "The New Zealand system instead deals with misleading statements formally but not legally. An implementation of this would require a code of conduct between parties that a body like the ASA could enforce. As the sanctions are far weaker than voiding elections, a greater number of claims would be likely to be judged.", "tags": "", "url": "index.html#7.6984.oyeuq.sceug.abv8h.g6vrr"},
     
     {"title": "The Options", "text": "This ultimately comes down to whether the Electoral Commission or the ASA would be better suited for the job. The South Australian example suggests that the Electoral Commission would never be entirely comfortable with the role. On the other hand the ASA has experience dealing with separating fact from opinion in commercial advertising and, despite claims to the contrary, political advertising isn&#39;t all that different. It makes more sense to expand the scope of the job the ASA is doing anyway than to graft a new role (that civil servants would be uncomfortable with) onto the Electoral Commission. ", "tags": "", "url": "index.html#7.638.myf6d.gcswh.oqprz.3azvb"},
     
     {"title": "The Options", "text": "The next step is to get an idea of what this code of conduct should look like. Here we should steal shamelessly from New Zealand&#39;s working system, especially the idea of advocacy principles that require political advertisement be dealt with &quot;&quot;liberally&quot;&quot; - while still being able to close down demonstrably untrue statements of facts. ", "tags": "", "url": "index.html#7.5206.npnr-.znhwt.-xvsx.xitd9"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "As political parties are regular players in the advertising game it is absolutely right that they be subject to the same regulation system as everyone else. We have a cartel of governance-providers who are colluding to hide their claims from the same scrutiny that applies to every other industry - this shouldn&#39;t be accepted.", "tags": "", "url": "index.html#ending-the-asa-exemption-for-political-advertising"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "As a result of the ASA&#39;s work in commercial advertising the public have an expectation that factual content is policed and a learned understanding of the ways more dubious facts are presented to comply with this. Ironically this undermines some of the public&#39;s defences against political misinformation. A claim that would have to be marked with an asterisk and suspicious small-print by an airline can be stated bold as day by a political advertiser. By existing and not policing political advertising the ASA oddly makes the situation worse than if it did nothing at all.", "tags": "", "url": "index.html#7.7561.ownsd.2yxwp.tghwy.iulun"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "As such we need, somehow, to amend section 7 of the CAP code to end the exemption for political advertising. But to do this requires a lot of upstream work to give the ASA greater freedom of action.", "tags": "", "url": "index.html#7.1435.bgfuh.llunb.u7z-e.nctdr"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "It&#39;s tempting to hope for the ASA to come out fighting - after all they&#39;re not without measures to enforce compliance. However, this would in reality be an extraordinary combative approach from the ASA. While we&#39;ve seen British courts give leeway to restrict misleading speech under law, what we haven&#39;t seen to date is how willing they would be to apply this to private actors enforcing restrictions extra-legally. As decisions made by the ASA have been found to be subject to judicial review, stepping too far beyond the aegis of the legal backstop would invite challenge. While the resulting legal arguments would be very interesting, it&#39;s understandable for the ASA to want to avoid &quot;interesting&quot; legal cases.", "tags": "", "url": "index.html#7.1137.sgkx9.ub23x.2hrc-.opm1q"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "An interesting, but not particularly useful, avenue of action: A return to the pre-1999 status quo - with restrictions on misleading statements about personal character that reflect the legal distinction - seems likely to survive review given the cases decided since that were robust against ECHR-based arguments. But given the limited scope of action this allows, it&#39;s unclear that it&#39;s a hill worth convincing the ASA to die on. ", "tags": "", "url": "index.html#7.761.i6bse.-4bcp.gzqtx.rc0rg"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "The NZ ASA shows that regulation without legal basis can be successful, but this ultimately depends on a political culture of no one complaining about it. The cautionary tale of FACTS in Australia shows that regulation without rooted support is fragile. Fundamentally our political culture is hostile to the idea and, as there is no legal or institutional stick to beat it with, the culture needs to be persuaded to reform itself. ", "tags": "", "url": "index.html#7.9841.q0flj.vylc9.ukkv3.tx3k3"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "So we&#39;re back in the old problem where the easiest hope is that the parties can be persuaded to agree on self-regulation to empower the ASA to deal with disputes - something that there was little interest in last time around.", "tags": "", "url": "index.html#7.81.sofld.jviu-.pgceo.gxiug"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "But to be positive about it, the situation is different now. Successive high-profile issues with misleading claims have pushed the issue towards the mainstream. Rejection of self-regulation would now have to be slightly louder (and more damaging) than quietly not responding to a consultation. ", "tags": "", "url": "index.html#7.5033.2ytcn.7myac.x7-ci.4vruv"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "We&#39;re also in a better situation to skip past &quot;&quot;can this work?&quot;&quot; and &quot;&quot;what would this even look like?&quot;&quot; because we can refer to working examples that were not previously part of the debate. We can lift the NZ ASA language for advocacy advertising and ask &quot;&quot;why is this not good enough for you?&quot;&quot;", "tags": "", "url": "index.html#7.3133.w_bld.dn1gj.rj7vq.eeyic"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "Relevant sections of NZ ASA Codes of practice:", "tags": "", "url": "index.html#7.7378.i_hyi._4uda.dffs-.ujtwa"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "This rule should be interpreted through advocacy principles that reflect priority needs to be given to freedom of expression during elections. The following are drawn from the NZ ASA&#39;s rules and adapted for the UK&#39;s rights context:", "tags": "", "url": "index.html#7.5467.5jnmb.o7u8z.wcx2y.bp9hv"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "That Article 10 of the European Convention of Human Rights, in granting the right of freedom of expression, allows advertisers to impart information and opinions but that in exercising that right what was factual information and what was opinion should be clearly distinguishable.That the right of freedom of expression as stated in Article 10 is not absolute as there could be an infringement of other people&#39;s rights. Care should be taken to ensure that this does not occur.That the Codes fetter the right granted by Article 10 to ensure there is fair play between all parties on controversial issues. Therefore in advocacy advertising and particularly on political matters the spirit of the Code is more important than technical breaches. People have the right to express their views and this right should not be unduly or unreasonably restricted by Rules.That robust debate in a democratic society is to be encouraged by the media and advertiser and that the Codes should be interpreted liberally to ensure fair play by the contestants.That it is essential in all advocacy advertisements that the identity of the advertiser is clear.", "tags": "", "url": "index.html#7.1018.pw165.hf-ks.ybur_.vkfi7"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "This provides a reasonable and common sense approach to political speech, in which its special role in democratic society is protected with additional leeway  - but voters also gain protection from the most obvious false statements of fact. ", "tags": "", "url": "index.html#7.4756._kzux.zgeme.wdund.gnkqg"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "But even if reform&#39;s hand is stronger there are still substantial structural obstacles. As the Conservative Party noted correctly in the last round; in an area with only a few big players, one hold-out can derail the entire process of self-regulation.", "tags": "", "url": "index.html#7.8665.bszew.b5m9k.mxfdv.ar4lm"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "As such we need to consider what a legislative backstop that would allow the ASA to take action would look like. To ease passage it might make sense to construct a weak version of South Australia&#39;s law. By weak, I mean avoiding the idea that misleading advertising is an &quot;illegal practice&quot; (which implies the ability to overturn the results of an election), focusing solely on the idea that misleading statements of fact could be subject to an injunction. This would rarely be used, but provides the backstop necessary for the ASA to take action. ", "tags": "", "url": "index.html#7.7140.ntstn.llunb.wlahn.lnmi_"},
     
     {"title": "Ending the ASA Exemption for Political Advertising", "text": "Ideally fear of this approach would be sufficient to compel self-regulation, but there are inherent advantages to a legislative approach. Self-regulation with only a few large players requires everyone to agree - legislation only requires one party with a majority. It is also more secure against future insurgent parties or candidates, who may exist outside any self-regulated consensus. ", "tags": "", "url": "index.html#7.2444.qxakk.kpvok.-svkh.e7ask"},
     
     {"title": "Make Designated Status Conditional in Referendums", "text": "As referendum campaigns are by their nature temporary they have far less incentive to abide by instructions to withdraw adverts or avoid repeating claims. If there is no long-term, the long-term sanctions are less of a deterrent. However, it is worth remembering that the benefits of becoming the designated campaign on one side of the issue are substantial. For the EU referendum designated campaigns received:", "tags": "", "url": "index.html#make-designated-status-conditional-in-referendums"},
     
     {"title": "Make Designated Status Conditional in Referendums", "text": "A higher spending limit of &amp;#163;7 million One free distribution of information to votersThe use of certain public roomsReferendum campaign broadcastsA grant of up to &amp;#163;600,000, to be used for certain spending including the administration costs associated with setting up and running a referendum campaign and the costs associated with the TV broadcasts and free mailing to voters that they are entitled to as lead campaignersA dedicated page in the Commission&#39;s public information booklet which will be distributed to all households in the UK (in both English language and bilingual English/Welsh language versions)The inclusion in the booklet of a link to a page on the campaigner&#39;s website, which should include their opinion on what will happen in the event of either referendum result.^*", "tags": "", "url": "index.html#7.1847.c4pcn.p6-b1.uq7rw.dkaa0"},
     
     {"title": "Make Designated Status Conditional in Referendums", "text": "Given how much public money is spent distributing the arguments of the campaign, it seems reasonable to require (as Alan Renwick suggests^*) that this funding be conditional on abiding by a code of conduct that creates some protections for the electorate. ", "tags": "", "url": "index.html#7.6052.aotju.ivdqz.dxsf1.zoocs"},
     
     {"title": "Make Designated Status Conditional in Referendums", "text": "To point fingers, when Vote Leave applied for designated status for the 2016 EU referendum they said that they &quot;&quot;intend to campaign in such a way that we will also create a valuable legacy for the UK&#39;s democratic process&quot;&quot;^*.", "tags": "", "url": "index.html#7.2574.h5x23.dzc0y.uk8l_.jn79a"},
     
     {"title": "Make Designated Status Conditional in Referendums", "text": "After the fact it&#39;s hard to see how the misinformation in this referendum did anything but undermine the long-term trust in democratic campaigning in the UK. When there is no expectation that campaigners are being honest with the public the democratic polity is damaged. We need to create structures that incentivise the short-term organisations that run referendum campaigns to campaign in such a way that we are better off as a result of the campaign - regardless of the outcome of the vote. ", "tags": "", "url": "index.html#7.3590.kw-ef.pzbvn.rsrke.zaukg"},
     
     {"title": "Make Designated Status Conditional in Referendums", "text": "As such, either by amending the Political Parties, Elections and Referendums Act 2000 or conditionally in legislation enabling future referendums, designated campaigns should be required to agree to a code of conduct. This code should be simple, providing a small backstop on factual claims and making abiding the decisions of independent bodies like the ASA a requirement of continued preferential status.", "tags": "", "url": "index.html#7.5059.xyv_r.mlbcf.aovmq.jtdce"},
     
     {"title": "Make Designated Status Conditional in Referendums", "text": "The exact language here would probably be similar to that used in The Consumer Protection from Unfair Trading Regulations 2008 19(4) - requiring deference to control through &quot;established means&quot; (e.g. self-regulation through the ASA).", "tags": "", "url": "index.html#7.4984.sofpl.eca6f.ndjv7.xqqom"},
     
     {"title": "Change", "text": "While individual candidates have discovered the appeal of having a method of redress, this isn&#39;t a change that will emerge naturally from our current political culture. We will need to campaign for and demand it from the outside. ", "tags": "", "url": "index.html#change"},
     
     {"title": "Change", "text": "Arguments against promoting truth in political advertising are not unanswerable. Systems that manage this exist, function, and are viable alternatives to our current approach of doing very little. While giving greater leeway to political adverts than commercial adverts is reasonable, the current gulf between political and commercial regulation is enormous. A better balance between protecting the electorate from lies and protecting them from undemocratic paternalism is perfectly achievable.", "tags": "", "url": "index.html#7.6376.3rwxc.grxmj.z0jdq.jsitq"},
     
     {"title": "Change", "text": "What I&#39;ve proposed is far from a solution to lying in politics - in fact it might seem hopelessly inadequate in comparison to the problem. We need to be careful with the idea that structural approaches can &quot;fix&quot; political culture. These rules have not magically created truthful environments when implemented, simply created opportunities for redress in a wider set of circumstances. But just because deceit has always been a problem in democracy does not mean we have to accept the extent of it - even a single malicious incorrect statement removed from play improves the quality of the election. &quot;&quot;We can make elections slightly better&quot;&quot; isn&#39;t a fantastic rallying cry. But we can, and we should. ", "tags": "", "url": "index.html#7.4780.sbizs.ra2d4.h9nzg.preje"},
     
     {"title": "Acknowledgements", "text": "This ebook is an expansion of a section of a 2012 MSc dissertation. Thanks should go to the many people who gave notes and corrections to make it far less error-filled than it might have been.", "tags": "", "url": "index.html#acknowledgements"},
     
     {"title": "Acknowledgements", "text": "The title image is made up of election leaflets for the 2015 General Election submitted to electionleaflets.org and the mosaic image was created with AndreaMosiac.", "tags": "", "url": "index.html#7.5709.nqm-c.m9lka.wv0tr.5lv6y"}
     
     
]};